{
  "hash": "b1bfc84807515a4876cf6de224ac04b2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 06: Comparing Groups with JAMOVI\"\nsubtitle: \"Date: October 1, 2026\"\nfooter:  \"[course-website](https://dharaden.github.io/psyc640/)\"\nlogo: \"images/640_hex.png\"\nformat:\n  revealjs:\n    theme: [default, brand, clean.scss]\n    multiplex: false\n    transition: fade\n    slide-number: true\n    incremental: false\n    chalkboard: true\n    overview: false\n    scrollable: true\n    code-line-numbers: true\neditor: visual\nexecute:\n  echo: true\n  freeze: auto\n---\n\n## Today...\n\n**Groups, as lines**\n\n- Why a t-test *is* a regression (we prove it properly this time)\n- Dummy coding: how software turns a group into a number\n- Three or more groups: ANOVA is the same machine\n- Why not just run a bunch of t-tests?\n- Effect size: *d*, R², and which one to report\n\n::: callout-note\nThis is the **JAMOVI** version. Same data, same numbers, same conclusions as the R deck — only the buttons change.\n:::\n\n------------------------------------------------------------------------\n\n## Where we left off\n\nLast week, in Part C of the activity:\n\n::: incremental\n- You ran a **t-test** on two groups and got *t* = −2.29, *p* = .022\n- You put the same grouping variable in **Factors** in Linear Regression and got **the same** *t* and *p*\n- The **intercept** turned out to be one group's mean, and the **estimate** the difference between the means\n:::\n\n. . .\n\nToday: *why*, and what happens when there are **three** groups.\n\n------------------------------------------------------------------------\n\n## Our data: you, more or less 😴\n\nBack to the **TIPI dataset** from Week 3 — 99 students, their personality scores, and how much they sleep.\n\n<a href=\"../files/data/final_tipi.csv\" download=\"final_tipi.csv\">Download the TIPI data (.csv)</a>\n\n> ☰ **Menu → Open → Browse →** `final_tipi.csv`\n\nWe need a **year group** variable. In the **Data** tab:\n\n> **Compute** → new variable `year_group` →\n>\n> `IF(year_school == 1, \"First year\", IF(year_school == 2, \"Sophomore\", \"Junior+\"))`\n\nThen set `year_group` to **Nominal**.\n\n> **Research question:** Do students further along in school sleep differently than first-years?\n\n# Part 1: Two Groups\n\n------------------------------------------------------------------------\n\n## Start with two\n\nFilter the sophomores out for a moment: **Data → Filters →**\n\n```\nyear_group != \"Sophomore\"\n```\n\n> **Analyses → Exploration → Descriptives** · `hours_of_sleep` split by `year_group`\n\n| Group | N | Mean | SD |\n|-------------------|-------------------|-------------------|-------------------|\n| First year | 39 | **6.13** | 1.28 |\n| Junior+ | 37 | **6.92** | 0.64 |\n\nJuniors and above sleep about **0.79 hours** — roughly 47 minutes — more per night. Is that more than noise?\n\n------------------------------------------------------------------------\n\n## The test you already know\n\n> **Analyses → T-Tests → Independent Samples T-Test**\n>\n> Dependent Variable: `hours_of_sleep` · Grouping Variable: `year_group`\n>\n> Tick **Student's**, **Welch's**, **Mean difference**, **Effect size**\n\n| Test | statistic | df | p | Mean difference | Cohen's d |\n|------------|------------|------------|------------|------------|------------|\n| Student's t | **−3.38** | 74 | **0.001** | −0.79 | **−0.78** |\n| Welch's t | −3.43 | 56.5 | 0.001 | −0.79 |  |\n\n------------------------------------------------------------------------\n\n## The same question as a line\n\n> **Analyses → Regression → Linear Regression**\n>\n> Dependent Variable: `hours_of_sleep` · **Factors:** `year_group`\n\n| Predictor | Estimate | SE | t | p |\n|-------------|-------------|-------------|-------------|-------------|\n| Intercept | **6.13** | 0.164 | 37.5 | \\< .001 |\n| Junior+ – First year | **0.79** | 0.234 | **3.38** | **0.001** |\n\n. . .\n\n::: callout-important\nSame *t* (the sign just depends on which group comes first). Same *p*. The t-test is a regression with **one categorical predictor**.\n:::\n\n------------------------------------------------------------------------\n\n## But how do you put a *group* in an equation?\n\n$$\\hat{Y_i} = b_0 + b_1X_i$$\n\n$X$ has to be a **number**. \"Junior+\" is not a number.\n\n. . .\n\nSo JAMOVI makes one. **Dummy coding**:\n\n| Group | coded as |\n|------------------|------------------|\n| First year (reference) | **0** |\n| Junior+ | **1** |\n\nThat's it — and it is why the estimate is labeled **\"Junior+ – First year\"**.\n\n------------------------------------------------------------------------\n\n## Read the equation twice\n\n$$\\widehat{sleep} = 6.13 + 0.79(junior^+)$$\n\n::::: columns\n::: {.column width=\"50%\"}\n**First year** → plug in 0\n\n$$6.13 + 0.79(0) = 6.13$$\n\nThe **intercept** is the mean of the reference group.\n:::\n\n::: {.column width=\"50%\"}\n**Junior+** → plug in 1\n\n$$6.13 + 0.79(1) = 6.92$$\n\nThe **estimate** is the **difference** between the group means.\n:::\n:::::\n\n. . .\n\nA \"line\" through a predictor with two values can only ever produce **two** predicted values: the two group means.\n\n------------------------------------------------------------------------\n\n## Who is the reference group?\n\nJAMOVI uses the **first level** of the factor — alphabetically, \"First year\".\n\n> **Linear Regression → Reference Levels**\n\nSwitch the reference to Junior+ and watch:\n\n- The intercept becomes **6.92**\n- The estimate flips to **−0.79**\n- *t*, *p*, R² and every residual **do not move**\n\n. . .\n\nSame model, different starting point.\n\n------------------------------------------------------------------------\n\n## What about Welch?\n\nJAMOVI shows **Student's** and **Welch's** side by side. Linear Regression always assumes **equal variances** — the Student's version.\n\n. . .\n\nLook back at those SDs: **1.28** for first-years, **0.64** for juniors+. The first-years are twice as spread out.\n\n::: callout-note\nThat is exactly the situation Welch was built for. Here the groups are nearly the same size (39 vs 37), so the two tests agree — but with unequal *n* **and** unequal spread, they would not. Know which one you ran.\n:::\n\n------------------------------------------------------------------------\n\n## Effect size: two flavors\n\n::::: columns\n::: {.column width=\"50%\"}\n**From the t-test panel**\n\nCohen's *d* = **0.78**\n\nThe difference in standard deviations. \"How separated are the groups?\"\n:::\n\n::: {.column width=\"50%\"}\n**From Linear Regression → Model Fit**\n\nR² = **.133**\n\nProportion of variance in sleep accounted for by group. \"How much does knowing the group help?\"\n:::\n:::::\n\n. . .\n\nSame model. Report *d* for a two-group comparison; R² scales up to everything we do next.\n\n------------------------------------------------------------------------\n\n## 🛠️ Activity Stop 1: Same Question, Three Ways\n\n::: callout-tip\n**Part A: Follow along** · \\~20 min · Pairs\n:::\n\nNew data — the Pokémon set from your in-class check:\n\n- Run the t-test, then the regression, on the same two groups\n- Find the intercept in the group means\n- Flip the reference group and predict what will change **before** you run it\n\n[Open the activity](../class-activities/wk6_groups.html){.button target=\"_blank\"}\n\n------------------------------------------------------------------------\n\n## ☕ Break {background-color=\"#C9ADE0\"}\n\n**10 minutes**\n\nWhen we come back: **three** groups.\n\n# Part 2: Three or More Groups\n\n------------------------------------------------------------------------\n\n## Put the sophomores back\n\nTurn the filter off (click the eye icon) and run Descriptives again:\n\n| Group | N | Mean | SD |\n|-------------------|-------------------|-------------------|-------------------|\n| First year | 39 | **6.13** | 1.28 |\n| Sophomore | 23 | **6.48** | 0.90 |\n| Junior+ | 37 | **6.92** | 0.64 |\n\n. . .\n\nSophomores land in the middle. Now we have **three** means — and three possible comparisons.\n\n------------------------------------------------------------------------\n\n## Why not just run three t-tests? 🤔\n\nfirst-year vs sophomore · first-year vs junior+ · sophomore vs junior+\n\n. . .\n\nEach test has a 5% false-positive rate. If the three tests were **independent**, the chance of at least one false positive would be:\n\n$$1 - (1 - .05)^3 = .143$$\n\n. . .\n\nThey are *not* independent — the three tests reuse the same three groups — so that formula overstates it a bit. Let's just **check**, by simulating studies where we **know** there is nothing to find.\n\n------------------------------------------------------------------------\n\n## 1,000 studies where nothing was going on\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec-06_groups_JAMOVI_files/figure-revealjs/unnamed-chunk-1-1.png){width=960}\n:::\n:::\n\n\nThree groups drawn from the **same** population, every pairwise t-test run, repeated 1,000 times. About **12%** of these studies produced at least one \"significant\" difference. None were real.\n\n------------------------------------------------------------------------\n\n## It gets worse fast\n\n| Groups | Pairwise tests | False-positive rate |\n|------------------|------------------|------------------|\n| 2 | 1 | **4.9%** ← as advertised |\n| 3 | 3 | **12.3%** |\n| 4 | 6 | **20.2%** |\n| 5 | 10 | **29.2%** |\n\n[*20,000 simulated studies per row, n = 30 per group, all groups from the same population.*]{style=\"font-size:0.7em\"}\n\n::: incremental\n- The naive formula ($1-.95^{10}$ = 40% for five groups) **overstates** it, because the tests overlap\n- But the honest number is still **six times** the rate you think you are running\n:::\n\n::: callout-note\nJAMOVI has no built-in simulator, so this one is a demo rather than something to click along with. The code is on the R slides, and the activity has a version you can run if you are curious.\n:::\n\n. . .\n\nThis is why we start with **one** omnibus test, and why pairwise comparisons get **corrected**.\n\n------------------------------------------------------------------------\n\n## Two groups needed one dummy. Three need two.\n\n| Group | `Junior+` | `Sophomore` |\n|------------------|------------------|------------------|\n| **First year** (reference) | 0 | 0 |\n| Junior+ | 1 | 0 |\n| Sophomore | 0 | 1 |\n\n::: incremental\n- $k$ groups → $k - 1$ dummy variables\n- Every group gets a unique pattern of 0s and 1s\n- The reference group is the one that is **all zeros**\n:::\n\n. . .\n\nJAMOVI builds these the moment you drop a nominal variable into **Factors**.\n\n------------------------------------------------------------------------\n\n## The model\n\n> **Analyses → Regression → Linear Regression**\n>\n> Dependent: `hours_of_sleep` · **Factors:** `year_group`\n>\n> Model Fit: tick **R²** and **Overall Model Test (F test)**\n\n**Model Fit**\n\n| R² | F | df1 | df2 | p |\n|------------|------------|------------|------------|------------|\n| **0.111** | **6.02** | 2 | 96 | **0.003** |\n\n**Model Coefficients**\n\n| Predictor | Estimate | SE | t | p |\n|------------|------------|------------|------------|------------|\n| Intercept | **6.13** | 0.159 | 38.5 | \\< .001 |\n| Junior+ – First year | **0.79** | 0.228 | 3.47 | **\\< .001** |\n| Sophomore – First year | **0.35** | 0.261 | 1.34 | 0.184 |\n\n------------------------------------------------------------------------\n\n## Reading it\n\n$$\\widehat{sleep} = 6.13 + 0.79(junior^+) + 0.35(sophomore)$$\n\n::: incremental\n- **Intercept 6.13** = mean sleep of **first-years** (the reference)\n- **+0.79** = juniors+ sleep 0.79 hours more **than first-years**\n- **+0.35** = sophomores sleep 0.35 hours more **than first-years**, and that one is not significant\n- Every estimate is a comparison **to the reference group** — not to each other\n:::\n\n. . .\n\nSo where is sophomore vs junior+? **It isn't in this table.** JAMOVI even names the rows that way: `Junior+ – First year`.\n\n------------------------------------------------------------------------\n\n## The omnibus F test\n\n> F(2, 96) = 6.02, **p = .003**, R² = **.111**\n\n::: incremental\n- $H_0$: all three population means are equal\n- A small *p* says **at least one** group differs — it does not say which\n- This is the ANOVA you already know. Same model, different summary.\n:::\n\n. . .\n\nRun it the classic way and compare:\n\n> **Analyses → ANOVA → ANOVA** · Dependent `hours_of_sleep`, Fixed Factor `year_group`\n>\n> Tick **η²** under Effect Size\n\nSame F. Same p. η² = **.111** — the same number as R².\n\n------------------------------------------------------------------------\n\n## Getting the comparison the table hid\n\n> **ANOVA → Post Hoc Tests**\n>\n> Move `year_group` across · Correction: **Tukey**\n\n| Comparison | Mean difference | p~tukey~ |\n|--------------------------|--------------------------|-------------------|\n| First year − Junior+ | −0.79 | **0.002** |\n| First year − Sophomore | −0.35 | 0.377 |\n| Junior+ − Sophomore | 0.44 | 0.222 |\n\n::: incremental\n- The omnibus test was significant because of **one** of the three comparisons\n- Without the pairwise step you would not know which\n:::\n\n------------------------------------------------------------------------\n\n## Marginal means\n\n> **ANOVA → Estimated Marginal Means**\n\nAdd `year_group` to a term box and tick **Marginal means plots** and **Marginal means tables**.\n\n. . .\n\nWith one factor these are just the group means — but the plot (with error bars) is the figure you want in a talk, and in Week 9 these become the only sane way to read an interaction.\n\n------------------------------------------------------------------------\n\n## Writing it up\n\n> Average nightly sleep differed significantly across year in school, *F*(2, 96) = 6.02, *p* = .003, $\\eta^2$ = .11. First-year students reported the least sleep (*M* = 6.13, *SD* = 1.28), followed by sophomores (*M* = 6.48, *SD* = 0.90) and juniors or above (*M* = 6.92, *SD* = 0.64). Tukey-adjusted comparisons indicated that juniors and above slept significantly more than first-year students, *p* = .002; no other pairwise comparison was significant.\n\n. . .\n\n::: callout-tip\nNotice the shape: **omnibus test → group descriptives → which pairs differ**. In that order, every time.\n\nJAMOVI's tables are nearly APA already — right-click → **Export** to drop them into Word.\n:::\n\n------------------------------------------------------------------------\n\n## And the obvious caveat\n\nNobody was **randomly assigned** to be a first-year.\n\n::: incremental\n- Maybe upper-year students have more control over their schedules\n- Maybe the heavy-sleep-deprivation majors drop out before junior year\n- Maybe first-years live in noisier housing\n:::\n\n. . .\n\nThe model is fine. The **causal claim** is not available — same lesson as Lab 6. Next week's lab is the exception that proves the rule: a study where people *were* randomly assigned.\n\n------------------------------------------------------------------------\n\n## What the model assumes\n\n::: incremental\n1.  **Independence** — one row per student, no nesting (Week 13 relaxes this)\n2.  **Normality of the residuals** — not of the raw scores\n3.  **Equal variances** across groups (homogeneity) — remember SD = 1.28 vs 0.64\n:::\n\n. . .\n\n> **ANOVA → Assumption Checks**\n>\n> Homogeneity test (Levene's) · Normality test (Shapiro-Wilk) · Q-Q plot\n\nIf homogeneity fails, JAMOVI offers **Welch's** correction right in the One-Way ANOVA panel.\n\n------------------------------------------------------------------------\n\n## The big picture so far\n\n| What you want | Where it lives in JAMOVI | What people call it |\n|------------------|------------------------|------------------|\n| Continuous predictor | Regression → Linear Regression (**Covariates**) | Regression |\n| 2 groups | T-Tests, **or** Linear Regression (**Factors**) | t-test |\n| 3+ groups | ANOVA, **or** Linear Regression (**Factors**) | One-way ANOVA |\n| Several predictors | Covariates **and** Factors together | **Multiple regression (Week 8)** |\n\n. . .\n\nOne machine. You are just changing what goes in the boxes.\n\n------------------------------------------------------------------------\n\n## JAMOVI ↔ R cheat sheet\n\n| What you want | JAMOVI | R |\n|------------------------|------------------------|------------------------|\n| Group descriptives | Descriptives → Split by | `group_by() %>% summarize()` |\n| Two-group test | T-Tests → Independent Samples | `t.test(y ~ g, var.equal = TRUE)` |\n| Groups as a line | Linear Regression → **Factors** | `lm(y ~ g)` |\n| Omnibus F | Model Fit → Overall Model Test | `anova(mod)` / `summary(aov())` |\n| Change reference group | Reference Levels | `relevel()` / `fct_relevel()` |\n| Pairwise comparisons | ANOVA → Post Hoc (Tukey) | `emmeans(mod, pairwise ~ g)` |\n| Effect size | Cohen's d box · η² box | `effectsize::cohens_d()` · `glance()$r.squared` |\n| Group means plot | Estimated Marginal Means | `emmeans()` + `plot()` |\n| Make a grouping variable | Data → Compute → `IF(...)` | `mutate(case_when(...))` |\n\n------------------------------------------------------------------------\n\n## 🛠️ Activity Stop 2: Parts B & C\n\n::: callout-tip\n**Same Question, Three Ways** · \\~30 min · Pairs\n:::\n\n**Part B:** three Pokémon types, from descriptives to a written-up result\n\n**Part C:** choose a reference group on purpose, and see what changes (and what doesn't)\n\n[Open the activity](../class-activities/wk6_groups.html){.button target=\"_blank\"}\n\n------------------------------------------------------------------------\n\n## For next time\n\n📋 **Lab 7 — Does the Therapy Work?**, due **Tuesday 10/6 at 11:59pm**\n\n- A real three-arm randomized trial: Individual CBT, Group CBT, Waitlist\n- You fit the model, pick the reference group, and write the results\n- Five participants dropped out — you will have to decide what to say about that\n\n📖 Chapter 8 — ROS · Chapters 5 & 14.5 — ST · Chapter 15.4 — LSR\n\n::: callout-note\nHeads up: the **midterm project** is handed out in two weeks (10/15) and due 10/27. Lab 8 is due Tue 10/13, which is during Fall Break — submit it online as usual.\n:::\n",
    "supporting": [
      "lec-06_groups_JAMOVI_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}