---
title: "PSYC 640: Graduate Statistics"
tbl-colwidths: [5,5,15,20]
---

This page contains an outline of the topics, content, and preparation for the semester. This schedule will be updated as the semester progresses, with all changes documented here.

::: callout-important
Readings on the schedule will need to be completed prior to the course they are listed for. We will build on the concepts you read about in that specific class period, so it is important that you have read.
:::

<div>

+-------------------------+-------+------------------------------------------------+-----------------------------------+
| Week                    | Date  | Topic                                          | Prepare                           |
+:=======================:+:=====:+:==============================================:+:=================================:+
| [1](/weeks/week-1.html) | 08-25 | Getting set up + R foundations                 | Install R/RStudio; Bring a laptop |
+-------------------------+-------+------------------------------------------------+-----------------------------------+
| 2                       | 09-01 | LABOR DAY                                      | Chapter 1 & 2 - ST                |
|                         |       |                                                |                                   |
|                         |       |                                                | Chapter 2 - MSR                   |
+-------------------------+-------+------------------------------------------------+-----------------------------------+
| 3                       | 09-08 | Descriptives, Visualizations + Communication   | Chapter 5 - LSR                   |
|                         |       |                                                |                                   |
|                         |       |                                                | Chapter 1 & 3 - R4DS              |
+-------------------------+-------+------------------------------------------------+-----------------------------------+
| 4                       | 09-15 | Design, Sampling + Inference                   | Chapter 2 - IMS                   |
|                         |       |                                                |                                   |
|                         |       |                                                | Chapter 3 - MSR                   |
|                         |       |                                                |                                   |
|                         |       |                                                | Chapter 7 - ST                    |
+-------------------------+-------+------------------------------------------------+-----------------------------------+
| 5                       | 09-22 | Correlation + Effect Sizes                     | Chapter 5.1 & 13 - ST             |
|                         |       |                                                |                                   |
|                         |       |                                                | Chapter 11 - LSR                  |
+-------------------------+-------+------------------------------------------------+-----------------------------------+
| 6                       | 09-29 | Comparing Groups                               | Chapter 9 & 10 - ST               |
|                         |       |                                                |                                   |
|                         |       |                                                | Chapter 13 - LSR                  |
+-------------------------+-------+------------------------------------------------+-----------------------------------+
| 7                       | 10-06 | Simple Linear Regression                       | Chapter 14.1.1 - 14.1.4 - ST      |
|                         |       |                                                |                                   |
|                         |       |                                                | Chapter 7.1 - 7.2.4 - IMS         |
|                         |       |                                                |                                   |
|                         |       |                                                | Chapter 8.1.1 & 8.1.2 - MSR       |
+-------------------------+-------+------------------------------------------------+-----------------------------------+
| 8                       | 10-13 | FALL BREAK                                     | Work on your midterm project      |
+-------------------------+-------+------------------------------------------------+-----------------------------------+
| 9                       | 10-20 | Variability & Model Fit                        | Chapter 5 & 14- ST                |
|                         |       |                                                |                                   |
|                         |       |                                                | Chapter 7.2.5 - IMS               |
+-------------------------+-------+------------------------------------------------+-----------------------------------+
| 10                      | 10-27 | Multiple Regression I: Adding Predictors       | Chapter 15.3 - 15.5 - LSR         |
|                         |       |                                                |                                   |
|                         |       |                                                | Chapter 8 - IMS                   |
+-------------------------+-------+------------------------------------------------+-----------------------------------+
| 11                      | 11-03 | Multiple Regression II: Categorical Predictors | Chapter 9 - IMS                   |
|                         |       |                                                |                                   |
|                         |       |                                                | Chapter 8.3                       |
+-------------------------+-------+------------------------------------------------+-----------------------------------+
| 12                      | 11-10 | Assumptions + Model Diagnostics                | Chapter 7.3 - IMS                 |
|                         |       |                                                |                                   |
|                         |       |                                                | Chapter 14.5 - ST                 |
|                         |       |                                                |                                   |
|                         |       |                                                | Chapter 8.1.4 - MSR               |
|                         |       |                                                |                                   |
|                         |       |                                                | Chapter 15.8 - LSR                |
+-------------------------+-------+------------------------------------------------+-----------------------------------+
| 13                      | 11-17 | Expanding Regression                           | Chapter 14.2 & 14.3 - ST          |
+-------------------------+-------+------------------------------------------------+-----------------------------------+
| 14                      | 11-24 | Model Building + Comparison                    | Chapter 15.8 - 15.10 - LSR        |
+-------------------------+-------+------------------------------------------------+-----------------------------------+
| 15                      | 12-01 | Making R Work for You                          | Chapter 17 & 18 - ST              |
+-------------------------+-------+------------------------------------------------+-----------------------------------+
| 16                      | 12-08 | Wrapping Up + Workshop                         |                                   |
+-------------------------+-------+------------------------------------------------+-----------------------------------+

</div>

[*Introduction to Modern Statistics (2e)*](https://openintro-ims.netlify.app/){target="\"_blank"} –\> IMS

[*Learning Statistics with R*](https://learningstatisticswithr.com/book/){target="_blank"} –\> LSR

[*R for Data Science (2e)*](https://r4ds.hadley.nz/){target="\"_blank"} –\> R4DS

[*Modern Statistics with R (2e)*](https://www.modernstatisticswithr.com/){target="\"_blank"} –\> MSR

[*Statistical Thinking*](https://statsthinking21.github.io/statsthinking21-core-site/){target="\"_blank"} –\> ST

[*An Introduction to Statistical Learning (2e)*](https://www.statlearning.com/){target="_blank"} –\> ISL

[*Data Analysis: A Model Comparison Approach to Regression, ANOVA, and Beyond (3rd ed.)*](https://sadbhavnapublications.org/research-enrichment-material/2-Statistical-Books/Data-Analysis-A-Model-Comparison-Approach-To-Regression,-ANOVA,-and-Beyond.pdf){target="_blank"} –\> DA

```{r echo = FALSE}
knitr::knit_exit()
```

|      |      |       | Prepare | Slides | AE  |  Labs  | HW  | Exam | Project |
|------|------|-------|:-------:|:------:|:---:|:------:|:---:|:----:|:-------:|
| Week | Date | Topic |   📖    |   🖥️   | 📋  | [💻]() | ✍️  |  ✅  |   📂    |
