---
title: Syllabus
execute:
  freeze: true
---

You can also download a copy of the syllabus here: [Download Syllabus](docs/Haraden_Stats_PSYC640.pdf){target="_blank"}

# Weekly Schedule

Readings will be taken from the following texts:

-   [*Learning Statistics with R*](https://learningstatisticswithr.com/){target="\"_blank"} by Danielle Navarro

-   [*R for Data Science (2e)*](https://r4ds.hadley.nz/){target="\"_blank"} (Wickham, Çetinkaya-Rundel, & Grolemund, 2023)

-   [*OpenIntro Statistics 4^th^ ed.*](https://www.openintro.org/book/os/){target="\"_blank"} (Diez, Barr, & Cetinkaya-Rundel, 2022)

All books are available online for free, but can also be purchased if you prefer a physical copy of the materials. Some also allow for a PDF download if you prefer that formatting or to work offline.

**Note:** "R4DS" corresponds to the text *R for Data Science*; "LSR" corresponds to *Learning Stats with R*

+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| Week   | Date  | Topic                                   | Readings                                                                                                                                               | Presenter | Homework |
+========+=======+:========================================+:=======================================================================================================================================================+===========+==========+
| 1      | 08/27 | Course Orientation                      |                                                                                                                                                        |           |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| \-     | 08/29 | Getting Started with R                  | R4DS: Intro & 7                                                                                                                                        |           |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| 2      | 09/03 | Why Use Stats? & Research Designs       | LSR: 1 & 2                                                                                                                                             | DH        |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| \-     | 09/05 | R Workflow - structure of results       | RDS: 4 & 6 (or First Edition Chapter 8)                                                                                                                | SC        |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| 3      | 09/10 | Visualizing                             | RDS: 1                                                                                                                                                 | ThH       |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| \-     | 09/12 | Data Wrangling                          | RDS: 5                                                                                                                                                 | EM        |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| 4      | 09/17 | Data Wrangling                          |                                                                                                                                                        | AMG & HM  |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| \-     | 09/19 | Descriptives                            | LSR: 5                                                                                                                                                 | HS & NG   |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| 5      | 09/24 | Descriptives                            |                                                                                                                                                        | JLS & ES  |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| \-     | 09/26 | Statistical Thinking                    | [Lady Tasting Tea](http://users.stat.umn.edu/~rend0020/Teaching/STAT8801-resources/docs/Tea.pdf)                                                       | JB & CM   |          |
|        |       |                                         |                                                                                                                                                        |           |          |
|        |       |                                         | TBD                                                                                                                                                    |           |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| 6      | 10/01 | ANOVA                                   | [Intro](https://onlinestatbook.com/2/analysis_of_variance/intro.html) & [Design](https://onlinestatbook.com/2/analysis_of_variance/anova_designs.html) | MP & JR   |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| \-     | 10/03 | ANOVA                                   |                                                                                                                                                        | RH        |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| 7      | 10/08 | Regression                              | LSR: 15                                                                                                                                                | BP & ZK   |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| \-     | 10/10 | Regression                              |                                                                                                                                                        | TaH       |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| 8      | 10/15 | **NO CLASS**                            |                                                                                                                                                        |           |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| \-     | 10/17 | Probability, Distributions & Inferences | LSR: 9 & 10                                                                                                                                            |           |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| 9      | 10/22 | Probability, Distributions & Inferences |                                                                                                                                                        |           |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| \-     | 10/24 | Hypothesis Testing & Power              | LSR: 11 [Video – “What is a p-value?”](https://www.youtube.com/watch?v=RVxHlsIw_Do)                                                                    |           |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| 10     | 10/29 | Hypothesis Testing & Power              |                                                                                                                                                        |           |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| \-     | 10/31 | Categorical Data Analysis               | LSR: 12                                                                                                                                                |           |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| 11     | 11/05 | Categorical Data Analysis               |                                                                                                                                                        |           |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| \-     | 11/07 | Comparing Means                         | LSR: 13                                                                                                                                                |           |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| 12     | 11/12 | Comparing Means                         |                                                                                                                                                        |           |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| \-     | 11/14 | ANOVA                                   | LSR: 14                                                                                                                                                |           |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| 13     | 11/19 | ANOVA                                   |                                                                                                                                                        |           |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| \-     | 11/21 | Regression                              | LSR: 15                                                                                                                                                |           |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| 14     | 11/26 | Regression                              |                                                                                                                                                        |           |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| \-     | 11/28 | **NO CLASS**                            |                                                                                                                                                        |           |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| 15     | 12/03 | Overflow                                |                                                                                                                                                        |           |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| \-     | 12/05 | Overflow                                |                                                                                                                                                        |           |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+
| Finals |       |                                         |                                                                                                                                                        |           |          |
+--------+-------+-----------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------+----------+

**Final:** Oral exam will be held during the week of finals

# Graded materials

**Your final grade is comprised of these components:**

-   Lab Assignments: 35%
-   Journal Entries: 15%
-   Presentations: 25%
-   Oral exam: 25%

|       |        |        |       |        |        |       |        |       |       |
|:-----:|:------:|:------:|:-----:|:------:|:------:|:-----:|:------:|:-----:|:-----:|
| **A** | **A-** | **B+** | **B** | **B-** | **C+** | **C** | **C-** | **D** | **F** |
|  93+  | 90-92  | 87-89  | 83-86 | 80-82  | 77-79  | 73-76 | 70-72  | 60-69 | \< 60 |

## Lab Assignments

Lab assignments are intended to gauge your ability to apply the topics covered in class to the practice of data analysis. Lab assignments are to be done using R and RMarkdown; completed assignments should be submitted through myCourses, and students must attach both the .Rmd file and the compiled HTML file.

Lab assignments are due at the beginning of class on the day the assignment is listed. Lab assignments may be resubmitted with corrections and receive full credit. Please note, however, that corrections can only be made to problems that were answered at initial submission. To be considered for re-submission, assignments will have to be corrected and returned through myCourses within a week of receiving the initial grade. There is no limit to the number of times a homework assignment may be resubmitted as long as it is within the time frame.

Late assignments will be subject to the \[late policy\] with 25% being deducted for being late, and an additional 5% for each 24h period after the due date. For example, if you correctly answer questions totaling 28 points and turn it in 6 hours late, the assignment will receive 21 points. If you resubmit this assignment with corrected answers (a total of 30 points), the assignment will receive 22.5 points. [*Late assignments will be accepted only within 7 days of the original deadline.*]{.underline}

You may discuss assignments with your classmates; however, it is important that you complete each assignment on your own and do not simply copy someone else's code. If I believe one student has copied another's work, both students will receive a 0 on the homework assignment and will not be allowed to resubmit the assignment for points.

## Journal Entries

Each week you'll complete a short journal entry on myCourses. To earn full points, you'll have to write at least 200 words reflecting on just about anything at all. This can include content related to the course, such as how well you feel you understand the material or how you see the material come up in other work. This can also include anything related to your personal life or mental health that you would like for me to know, such as whether you are struggling to balance classes and research, having trouble creating a workspace at home, or whether you can balance time spent on campus and off. This can also be completely random things, like a news article you can't stop thinking about, or a favorite TV show, movie or book that you just love (especially if it is LOTR or Cosmere related). The content of what you write has *no impact* on your grade. In addition, what you write will be kept confidential.

**You may skip up to 5 journal entries with no penalty. This means that the total amount of journal entries you must submit is at least 10.**

The purpose of this assignment is to help facilitate communication between you and me. I have found other instructors using this and I would like to be able to develop supportive relationships with students, so I decided to implement this. Other instructors reported that they found that many students were more comfortable discussing questions and concerns in their journal assignments rather than through email.

## Presentations

Each student will be complete 2 brief presentations throughout the semester. These will need to be completed within the corresponding topic, but can be done at any point throughout that time (i.e., there won't be a single "presentation day" for everyone). The presentations will take place at the beginning of the class for the day.

The goal of the presentations is to have students get more practice with presenting to a group, as well as to provide more direct and useful information about the topics that we are discussing. Ultimately, a document will be compiled with all of the information that is presented in order for students to take with them moving forward.

The main focus of the presentations will be reflective of the structure of the course: (1) Practical and Using R; and (2) In-depth Stats. For topic 1, students will be asked to present on a package/library in R that they have found and walk through the usefulness of that tool. Then for topic 2, you will provide an overview of a specific statistical test/concept, this test being used in a paper and how it is written up. **More information will be available and Dustin will link it here, unless he has forgotten and then if you are reading this, that is kind of embarrassing.**

## Oral Exam

The oral exam will take place during finals week. About two weeks prior, you will be asked to schedule a time to complete the exam. The exam will take roughly 15 minutes. You will be asked to explain basic and elemental concepts, as if you were teaching an advanced undergraduate or new graduate student.

## **Late Policy**

*“A Wizard is never late, nor are they early. They arrive precisely when they mean to.”* 🧙‍♂️

Thanks Gandalf. Super helpful. Unfortunately, we are not wizards and late penalties will be applied to work that is not on time. There will be an initial 25% deduction for the first day and an additional 5% deduction for each day thereafter. For example, if you turn in an assignment 3 days late, there will be a 35% deduction from the grade for that assignment.

# Materials Needed

We will be using R for all data wrangling, visualization, and analysis. You may not use another statistical program in this course. Students must have the latest version of R and it is strongly recommended that students also download the RStudio GUI, both can be found [here](https://posit.co/download/rstudio-desktop/#download). Both types of software are free.

The text for this class will be pulled from multiple sources. They include:

-   [*Learning Statistics with R*](https://learningstatisticswithr.com/) by Danielle Navarro

-   [*R for Data Science (2e)*](https://r4ds.hadley.nz/) (Wickham, Çetinkaya-Rundel, & Grolemund, 2023)

-   [*OpenIntro Statistics 4^th^ ed.*](https://www.openintro.org/book/os/) (Diez, Barr, & Cetinkaya-Rundel, 2022)

All books are available online for free, but can also be purchased if you prefer a physical copy of the materials.

Additional reading assignments will be posted online.

# General Course Policies

## Statement on Reasonable Accommodations:

RIT is committed to providing academic adjustments to students with disabilities. If you would like to request academic adjustments such as testing modifications due to a disability, please contact the Disability Services Office. Contact information for the DSO and information about how to request adjustments can be found at [www.rit.edu/dso](http://www.rit.edu/dso). After you receive academic adjustment approval, it is imperative that you contact me as early as possible so that we can work out whatever arrangement is necessary.

## **Statement on Title IX:**

RIT is committed to providing a safe learning environment, free of harassment and discrimination as articulated in our university policies located on our governance website. RIT’s policies require faculty to share information about incidents of gender-based discrimination and harassment with RIT’s Title IX coordinator or deputy coordinators when incidents are stated to them directly. The information you provide to a non-confidential resource which includes faculty will be relayed only as necessary for the Title IX Coordinator to investigate and/or seek resolution. Even RIT Offices and employees who cannot guarantee confidentiality will maintain your privacy to the greatest extent possible.

If an individual discloses information during a public awareness event, a protest, during a class\
project, or advocacy event, RIT is not obligated to investigate based on this public disclosure. RIT may however use this information to further educate faculty, staff and students about prevention efforts and available resources.

If you would like to report an incident of gender based discrimination or harassment directly you may do so by using the online Sexual Harassment, Discrimination and Sexual Misconduct Reporting or anonymously by using the Compliance and Ethics Hotline. If you have a concern related to gender-based discrimination and/or harassment and prefer to have a confidential discussion, assistance is available from any of RIT’s confidential resources (listed below).\
\

+---------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------+
| RIT Counseling and Psychological Services\                                                  | NTID Counseling and Academic Advising\                                            |
| 585-475-2261 (V)\                                                                           | 585-475-6400\                                                                     |
| 585-475-6897 (TTY)\                                                                         | [www.ntid.rit.edu/counselingdept](http://www.ntid.rit.edu/counselingdept)         |
| [www.rit.edu/counseling](http://www.rit.edu/counseling)                                     |                                                                                   |
+---------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------+
| RIT Student Health Center\                                                                  | Center for Religious Life\                                                        |
| 585-475-2255 (V)\                                                                           | 585-475-2137\                                                                     |
| [www.rit.edu/studentaffairs/studenthealth](http://www.rit.edu/studentaffairs/studenthealth) | [www.rit.edu/studentaffairs/religion](http://www.rit.edu/studentaffairs/religion) |
+---------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------+
| RIT Ombuds Office\                                                                          |                                                                                   |
| 585-475-7357\                                                                               |                                                                                   |
| 585-475-6424\                                                                               |                                                                                   |
| 585-286-4677 (VP)\                                                                          |                                                                                   |
| [www.rit.edu/ombuds/contact-us](http://www.rit.edu/ombuds/contact-us)                       |                                                                                   |
+---------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------+

## Academic Integrity:

As an institution of higher learning, RIT expects students to behave honestly and ethically at all times, especially when submitting work for evaluation in conjunction with any course or degree requirement. The Department of Psychology encourages all students to become familiar with the [RIT Honor Code](https://www.rit.edu/academicaffairs/policiesmanual/p030) and with [RIT's Academic Integrity Policy](https://www.rit.edu/academicaffairs/policiesmanual/d080). RIT’s policy on academic integrity requires the instructor to investigate of any suspected breach of academic integrity. If the preponderance of evidence indicates a breach of academic integrity, the student who did so may incur a consequence up to and including failure for the entire course.

## RIT COVID-19 Safety Plans:

RIT is committed to the safety of the RIT community and beyond. Because the situation is still in a rapid state of change, checking the RIT Ready website, and specifically the RIT Safety Plan for the most up to date information is recommended: <https://www.rit.edu/ready/rit-safety-plan>.

## [**Course Specific Policies**]{.underline}

If you anticipate issues related to the format or requirements of this course, please meet with me. I would like us to discuss ways to make sure you can participate to your best ability in the course. This course abides by university policies at RIT. In particular, please note the following:

**PHONE/LAPTOP USE IN CLASS**: Please do not use cell phones during class. If you need to take an emergency phone call, please feel free to leave the class quietly.  Laptops may be used when necessary for course-related uses.

**CLASS CANCELLATION:** In the event of a University-wide emergency course requirements, classes, deadlines and grading schemes are subject to changes that may include alternative delivery methods, alternative methods of interaction with the instructor, class materials, and/or classmates, a revised attendance policy, and a revised semester calendar and/or grading scheme.

**CHANGES TO THE SYLLABUS:** I have provided this syllabus as a guide to our course and have made every attempt to provide an accurate overview of the course. However, as instructor, I reserve the right to modify this document during the semester, if necessary, to ensure that we achieve course learning objectives. You will receive advance notice of any changes to the syllabus through myCourses/email.
