---
title: "Week 1"
editor: visual
---

# Getting Started!!

Welcome to the course! I am very excited to get to work with you this semester on our journey into statistics. During our first class, we will review the syllabus and the plan for the course, followed by walking through the structure of each of the classes.

We’ll then dive right into our primary set of tools, R and JAMOVI. This session will go over installing R and RStudio, navigating the interface, and learning the foundational syntax of the R language and the `tidyverse`, including data types and basic functions.

::: {.callout-note icon="false"}
This first class will be Asynchronous due to me being away this week. Please use the class time to review the materials instead of doing it "some other time"
:::

## Prepare

Please have these downloaded. I will walk through the process as well if you are unclear.

- Install R and R-Studio (<https://posit.co/download/rstudio-desktop/>)

- Install JAMOVI (<https://www.jamovi.org/download.html>)

## Slides & Recordings

[💻 Getting Started - Syllabus](../slides/lec-01_syl.html){target="_blank"}

[📹Syllabus Recording](https://rit.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=43baad4b-51ec-4d65-b231-b4b3002b4a29){target="_blank"}

[💻Getting Started - Data](../slides/lec-02_background.html){target="_blank"}

[📹Reproduction/Reproducibility Recording](https://rit.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=f3cf9b4c-4730-4dbf-8db4-b4b3002ce161){target="_blank"}

[📹Getting Started with R Recording](https://rit.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=e31e8ad2-2e73-46e8-bfb4-b4b3002d959b){target="_blank"}

## For Next Time

📋[Lab 1 - Getting Started](../labs/lab-01_introduction)

📋[Lab 2 - Data Workflow](../labs/lab-02_data-workflow)

❓[Introduction Check-in](https://rit.az1.qualtrics.com/jfe/form/SV_7VV0edmGEBKisey){target="_blank"}

📖Chapter 1 & 2 - LSR

📖Chapter 1 - ROS

<br><br>

::: {style="font-size: 0.875em;"}
Back to [course schedule](/ "Course schedule") ⏎
:::
