---
title: "Week 11"
editor: visual
---

::: callout-important
Review Final Project Expectations and dates [here](https://dharaden.github.io/psyc641-s25/project/final-proj-desc.html).
:::

## Prepare

📖 Brough - Sec. 2.8 & 2.9

## Slides

🖥️ [Qualitative Data](/slides/lec-12.html)

🖥️ [Survey Methods](/slides/lec-12-2.html)

## In-Class

**Group 1 Observation**

-   Focus on the amount of times students initiates conversation with:

    -   The teacher

    -   Another student

**Group 2 Observation**

-   Focus on the amount of times the conversations are positive, negative, neutral with:

    -   The teacher

    -   Another student

## Examples of Qualitative Investigation

-   [Levitt, H. M., Motulsky, S. L., Wertz, F. J., Morrow, S. L., & Ponterotto, J. G. (2017). Recommendations for designing and reviewing qualitative research in psychology: Promoting methodological integrity. Qualitative psychology, 4(1), 2.](https://www.apa.org/pubs/journals/features/qua-qup0000082.pdf)

-   [Holder, A., Jackson, M. A., & Ponterotto, J. G. (2015). Racial microaggression experiences and coping strategies of Black women in corporate leadership. Qualitative psychology, 2(2), 164.](https://www.apa.org/pubs/journals/features/qua-0000024.pdf)

-   [Dutt, A., & Grabe, S. (2014). Lifetime activism, marginality, and psychology: Narratives of lifelong feminist activists committed to social change. Qualitative Psychology, 1(2), 107.](https://www.apa.org/pubs/journals/features/qua-0000010.pdf)

<br><br>

::: {style="font-size: 0.875em;"}
Back to [course schedule](/ "Course schedule") ⏎
:::
