<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <title>PSYC 640 - Graduate Statistics – Week 11: Categorical Predictors &amp; Logistic Regression</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-5ae9c59b2727fcd5357d4f034d95f9e0.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="Week 11: Categorical Predictors &amp; Logistic Regression – PSYC 640 - Graduate Statistics">
<meta property="og:description" content="Date: November 3, 2025">
<meta property="og:site_name" content="PSYC 640 - Graduate Statistics">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Week 11: Categorical Predictors &amp; Logistic Regression</h1>
  <p class="subtitle">Date: November 3, 2025</p>

<div class="quarto-title-authors">
</div>

</section>
<section id="today" class="slide level2">
<h2>Today…</h2>
</section>
<section class="slide level2">

<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a></a><span class="fu">library</span>(rio)</span>
<span id="cb1-3"><a></a><span class="fu">library</span>(here)</span>
<span id="cb1-4"><a></a><span class="fu">library</span>(lm.beta)</span>
<span id="cb1-5"><a></a><span class="fu">library</span>(easystats)</span>
<span id="cb1-6"><a></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb1-7"><a></a></span>
<span id="cb1-8"><a></a></span>
<span id="cb1-9"><a></a><span class="co">#Remove Scientific Notation </span></span>
<span id="cb1-10"><a></a><span class="fu">options</span>(<span class="at">scipen=</span><span class="dv">999</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="regression" class="slide level2 scrollable">
<h2>Regression</h2>
<p><strong>3 main reasons for using regression:</strong></p>
<ol type="1">
<li>As a description (what is the average salary for men and women?)</li>
<li>As part of causal inference (Does being a woman result in a lower salary?)</li>
<li>For prediction (“What happens if…” questions)</li>
</ol>
</section>
<section class="slide level2">

<h3 id="explaining-variance">Explaining Variance</h3>

<img data-src="images/clipboard-3448148790.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section class="slide level2">

<h3 id="model-interpretation">Model Interpretation</h3>
<p>Once we have a model, we will be able to interpret the coefficients. For a bivariate regression, this was fairly straightforward</p>
<p>We would look to the beta (effect size) and interpret it as: <strong><em>for every 1 unit increase in our X variable, there will be beta units increase in our Y variable.</em></strong></p>
</section>
<section id="multiple-regression" class="slide level2">
<h2>Multiple Regression</h2>
<p>We may want to include additional predictors into our model to best explain the variance in an outcome:</p>
<p><span class="math display">\[ Y_i = b_0 + b_1X_{1i} + b_2X_{2i} + ... + b_nX_{ni}+ e_i \]</span></p>
</section>
<section class="slide level2">

<h3 id="explaining-variance-1">Explaining Variance</h3>

<img data-src="images/clipboard-4102854469.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section class="slide level2">

<h3 id="model-interpretation-1">Model Interpretation</h3>
<p>Since we have multiple predictors in the model, we have to interpret each predictor estimate while considering the other variables.</p>
<p>We would look to the beta (effect size) and interpret it as: <strong><em>for every 1 unit increase in our</em></strong> <span class="math inline">\(X_1\)</span> <strong><em>variable, there will be beta units increase in our Y (outcome) variable, <u>holding all other variables constant</u>.</em></strong></p>
</section>
<section id="reporting-standardized-or-unstandardized" class="slide level2">
<h2>Reporting Standardized or Unstandardized?</h2>
<p><strong>INTERPRET <em>b</em></strong>:</p>
<ul>
<li><p>When the variables are measured in a meaningful metric</p></li>
<li><p>To compare the relative effects of different predictors in the same sample</p></li>
</ul>
<p><strong>INTERPRET <em>β</em></strong>:</p>
<ul>
<li><p>When the variables are not measured in a meaningful metric</p></li>
<li><p>To compare effects across samples or studies</p></li>
</ul>
</section>
<section id="multiple-regression-example" class="slide level2">
<h2>Multiple Regression: Example</h2>
<p>Previously, we predicted the # of Transformers movies someone watched by their age, income and # of books read</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a>cah_data <span class="ot">&lt;-</span> <span class="fu">import</span>(<span class="fu">here</span>(<span class="st">"files"</span>, <span class="st">"data"</span>, </span>
<span id="cb2-2"><a></a>                        <span class="st">"CAH.csv"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb2-3"><a></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.character), <span class="sc">~</span><span class="fu">na_if</span>(., <span class="st">""</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The regression equation would look something like this:</p>
<p><span class="math display">\[
Y = b_0 + b_1X_1 + b_2X_2 + b_3X_3 + e
\]</span></p>
</section>
<section class="slide level2">

<h3 id="transformers-regression-b">Transformers Regression: <span class="math inline">\(b\)</span></h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a>reg1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(transformers <span class="sc">~</span> age <span class="sc">+</span> income <span class="sc">+</span> books,</span>
<span id="cb3-2"><a></a>           <span class="at">data =</span> cah_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Interpret</strong>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a><span class="fu">summary</span>(reg1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = transformers ~ age + income + books, data = cah_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.0283 -1.0658 -0.6646  0.8359  4.2314 

Coefficients:
                 Estimate    Std. Error t value             Pr(&gt;|t|)    
(Intercept)  2.6872892571  0.3197311424   8.405 0.000000000000000644 ***
age         -0.0256880349  0.0054919383  -4.677 0.000003904370103857 ***
income      -0.0000021955  0.0000009953  -2.206               0.0279 *  
books        0.0018608303  0.0009792731   1.900               0.0581 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.504 on 427 degrees of freedom
  (569 observations deleted due to missingness)
Multiple R-squared:  0.06449,   Adjusted R-squared:  0.05791 
F-statistic: 9.811 on 3 and 427 DF,  p-value: 0.000002857</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<h3 id="transformers-regression-beta">Transformers Regression: <span class="math inline">\(\beta\)</span></h3>
<p><code>scale()</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a>reg1.std <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">scale</span>(transformers) <span class="sc">~</span> <span class="fu">scale</span>(age) <span class="sc">+</span> <span class="fu">scale</span>(income) <span class="sc">+</span> <span class="fu">scale</span>(books),</span>
<span id="cb6-2"><a></a>           <span class="at">data =</span> cah_data)</span>
<span id="cb6-3"><a></a></span>
<span id="cb6-4"><a></a><span class="fu">summary</span>(reg1.std)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = scale(transformers) ~ scale(age) + scale(income) + 
    scale(books), data = cah_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.3007 -0.6834 -0.4262  0.5361  2.7135 

Coefficients:
              Estimate Std. Error t value  Pr(&gt;|t|)    
(Intercept)   -0.04536    0.04817  -0.942    0.3469    
scale(age)    -0.27392    0.05856  -4.677 0.0000039 ***
scale(income) -0.10176    0.04613  -2.206    0.0279 *  
scale(books)   0.09053    0.04764   1.900    0.0581 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9642 on 427 degrees of freedom
  (569 observations deleted due to missingness)
Multiple R-squared:  0.06449,   Adjusted R-squared:  0.05791 
F-statistic: 9.811 on 3 and 427 DF,  p-value: 0.000002857</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<h3 id="transformers-regression-beta-1">Transformers Regression: <span class="math inline">\(\beta\)</span></h3>
<p><code>lm.beta()</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a><span class="do">## Same as before</span></span>
<span id="cb8-2"><a></a>reg1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(transformers <span class="sc">~</span> age <span class="sc">+</span> income <span class="sc">+</span> books,</span>
<span id="cb8-3"><a></a>           <span class="at">data =</span> cah_data)</span>
<span id="cb8-4"><a></a></span>
<span id="cb8-5"><a></a>beta1.std <span class="ot">&lt;-</span> <span class="fu">lm.beta</span>(reg1)</span>
<span id="cb8-6"><a></a><span class="fu">summary</span>(beta1.std)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = transformers ~ age + income + books, data = cah_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.0283 -1.0658 -0.6646  0.8359  4.2314 

Coefficients:
                 Estimate  Standardized    Std. Error t value
(Intercept)  2.6872892571            NA  0.3197311424   8.405
age         -0.0256880349 -0.2194418839  0.0054919383  -4.677
income      -0.0000021955 -0.1036558341  0.0000009953  -2.206
books        0.0018608303  0.0890938373  0.0009792731   1.900
                        Pr(&gt;|t|)    
(Intercept) 0.000000000000000644 ***
age         0.000003904370103857 ***
income                    0.0279 *  
books                     0.0581 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.504 on 427 degrees of freedom
  (569 observations deleted due to missingness)
Multiple R-squared:  0.06449,   Adjusted R-squared:  0.05791 
F-statistic: 9.811 on 3 and 427 DF,  p-value: 0.000002857</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<h3 id="how-would-we-write-up-the-results">How would we write up the results?</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = transformers ~ age + income + books, data = cah_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.0283 -1.0658 -0.6646  0.8359  4.2314 

Coefficients:
                 Estimate  Standardized    Std. Error t value
(Intercept)  2.6872892571            NA  0.3197311424   8.405
age         -0.0256880349 -0.2194418839  0.0054919383  -4.677
income      -0.0000021955 -0.1036558341  0.0000009953  -2.206
books        0.0018608303  0.0890938373  0.0009792731   1.900
                        Pr(&gt;|t|)    
(Intercept) 0.000000000000000644 ***
age         0.000003904370103857 ***
income                    0.0279 *  
books                     0.0581 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.504 on 427 degrees of freedom
  (569 observations deleted due to missingness)
Multiple R-squared:  0.06449,   Adjusted R-squared:  0.05791 
F-statistic: 9.811 on 3 and 427 DF,  p-value: 0.000002857</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<h3 id="how-would-we-write-up-the-results-1">How would we write up the results?</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a><span class="fu">tab_model</span>(reg1, <span class="at">show.std =</span> <span class="cn">TRUE</span>,</span>
<span id="cb11-2"><a></a>          <span class="at">pred.labels =</span> <span class="fu">c</span>(<span class="st">"Intercept"</span>, <span class="st">"Age"</span>, </span>
<span id="cb11-3"><a></a>                          <span class="st">"Income"</span>, <span class="st">"# of Books"</span>), </span>
<span id="cb11-4"><a></a>          <span class="at">dv.labels =</span> <span class="st">"# of Transformers Movies"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top" style="border-collapse:collapse; border:none;">
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">&nbsp;</th>
<th colspan="5" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;"># of Transformers Movies</th>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Predictors</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Estimates</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">std. Beta</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">CI</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">standardized CI</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">p</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Intercept</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">2.69</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">2.06&nbsp;–&nbsp;3.32</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.09&nbsp;–&nbsp;0.09</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Age</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.03</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.22</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.04&nbsp;–&nbsp;-0.01</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.31&nbsp;–&nbsp;-0.13</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Income</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.10</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.00&nbsp;–&nbsp;-0.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.20&nbsp;–&nbsp;-0.01</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>0.028</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"># of Books</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.09</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.00&nbsp;–&nbsp;0.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.00&nbsp;–&nbsp;0.18</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.058</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">Observations</td>
<td colspan="5" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">431</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">R<sup>2</sup> / R<sup>2</sup> adjusted</td>
<td colspan="5" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">0.064 / 0.058</td>
</tr>
</tbody>
</table>
</div>
</div>
<blockquote>
<p>A linear regression model was fit to the data to predict # of Transformers movies watched with participant age, income and reported # of books read. The model explains a significant, but small portion of variance in the outcome (<em>F(3, 427)</em> = 9.81, <em>p</em> &lt; .001, adj. <span class="math inline">\(R^2\)</span> = .06). Participant age ( <span class="math inline">\(\beta\)</span> = -0.22, <em>p</em> &lt; .001) and income ( <span class="math inline">\(\beta\)</span> = -0.10, <em>p</em> = .028) were significantly related to the number of transformers movies, while the number of books was not (<em>p</em> = .508). These findings suggest that as individuals age, they tend to watch fewer transformers movies, controlling for income and # of books. Additionally, as income increases, we see a decrease in # of transformer movies while taking into account participant age and # of books.</p>
</blockquote>
</section>
<section>
<section id="but-what-about-categorical-variables-as-predictors" class="title-slide slide level1 center">
<h1>But what about categorical variables as predictors?</h1>

<img data-src="images/clipboard-1169136778.jpeg" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="categorical-predictors" class="slide level2">
<h2>Categorical Predictors</h2>
<p>Typically identified by a grouping variable that may be a <code>character</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a><span class="fu">glimpse</span>(cah_data<span class="sc">$</span>political_affiliation)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> chr [1:1000] "Democrat" "Democrat" "Independent" "Republican" "Democrat" ...</code></pre>
</div>
</div>
<p>Need to change the variable from <code>character</code> to <code>factor</code> which will assign a number to each group</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a></a>cah_data <span class="ot">&lt;-</span> cah_data <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a></a>  <span class="fu">mutate</span>(</span>
<span id="cb14-3"><a></a>    <span class="at">pol =</span> <span class="fu">as.factor</span>(political_affiliation),</span>
<span id="cb14-4"><a></a>    <span class="at">ghosts =</span> <span class="fu">as.factor</span>(ghosts)</span>
<span id="cb14-5"><a></a>    )</span>
<span id="cb14-6"><a></a></span>
<span id="cb14-7"><a></a><span class="fu">glimpse</span>(cah_data<span class="sc">$</span>pol)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 3 levels "Democrat","Independent",..: 1 1 2 3 1 1 2 3 3 1 ...</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<h3 id="categorical-data">Categorical Data</h3>
<p><strong>Nominal</strong> - the numbers have no relation to the category it represents (Biological Sex)</p>
<ul>
<li><em>Biological Sex</em> - Male (1), Female (2), Intersex (3)</li>
</ul>
<p><strong>Ordinal</strong> - the order of the numbers matters</p>
<ul>
<li><em>Education Levels</em> - High school (1), Bachelor’s (2), Master’s (3), Doctorate (4)</li>
</ul>
</section>
<section class="slide level2">

<h3 id="categorical-data---regression">Categorical Data - Regression</h3>
<p><strong><em>Can we use the numeric values that each category represents in a regression?</em></strong> I mean we can do just about anything. But, we should <u><strong>not</strong></u> use the numeric values as they are</p>
<p><strong>Why can’t we do this?</strong></p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Consider how we interpret the beta coefficients for slope</p>
</div>
</div>
</div>
</section>
<section class="slide level2">

<h3 id="categorical-data---regression-1">Categorical Data - Regression</h3>
<p>Regressions assume that there are equal spacing between each of the values and that the spacing is meaningful</p>
<ul>
<li><p>Going from High School to Bachelor’s is considered equal to Master’s to Doctorate?</p></li>
<li><p>What does it mean to interpret Male to Female to Intersex?</p></li>
</ul>
<p>To properly investigate the differences between the groups, we have to “trick” our regression equation - <em>Enter Dummy Variables/Coding</em></p>
</section>
<section id="dummy-coding" class="slide level2">
<h2>Dummy Coding</h2>
<p>Numerical placeholders used to represent categorical variables</p>
<p>Taking a categorical variable with <span class="math inline">\(k\)</span> levels (e.g., <code>Democratic</code>, <code>Independent</code>, <code>Republican</code>) into <span class="math inline">\(k-1\)</span> binary variables.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>political_affiliation</th>
<th><em>becomes</em></th>
<th>Ind (binary1)</th>
<th>Rep (binary2)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Democrat</td>
<td>–&gt;</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>Independent</td>
<td>–&gt;</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Republican</td>
<td>–&gt;</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td>…</td>
<td></td>
<td>…</td>
<td>…</td>
</tr>
</tbody>
</table>
</section>
<section class="slide level2">

<h3 id="dummy-coding-1">Dummy Coding</h3>
<p>For the variable with <span class="math inline">\(k\)</span> levels, we use <span class="math inline">\(k-1\)</span> binary variables…why not use all of them?</p>
<ul>
<li class="fragment"><p>Including all three variables would result in perfect multicollinearity. All Democrats would be related to other Democrats and unrelated to everything else</p></li>
<li class="fragment"><p>By including 2 binary variables, we are able to obtain all information about group membership</p></li>
</ul>
</section>
<section class="slide level2">

<h3 id="dummy-coding-2">Dummy Coding</h3>
<p>The group that has 0’s for all the binary variables is the <strong>reference group</strong></p>
<p>For interpretation, we will make our statements in reference to this group</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>political_affiliation</th>
<th><em>becomes</em></th>
<th>Ind (binary1)</th>
<th>Rep (binary2)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Democrat</td>
<td>–&gt;</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>Independent</td>
<td>–&gt;</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Republican</td>
<td>–&gt;</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td>…</td>
<td></td>
<td>…</td>
<td>…</td>
</tr>
</tbody>
</table>
</section>
<section id="categorical-regression" class="slide level2">
<h2>Categorical Regression</h2>
<p>Going back to our Transformers dataset, let’s see how our political affiliation variable can predict # of transformers movies</p>
<p>Usually you have to create the separate dummy variables, but not in R</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a></a>cat1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(transformers <span class="sc">~</span> pol,</span>
<span id="cb16-2"><a></a>           <span class="at">data =</span> cah_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>You can also double check the dummy/contrast coding</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a><span class="fu">contrasts</span>(cah_data<span class="sc">$</span>pol)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Independent Republican
Democrat              0          0
Independent           1          0
Republican            0          1</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<h3 id="interpretation">Interpretation</h3>
<p>We are shown the different levels of our predictor variable, but you will not see a predictor for the reference group</p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Think about how we interpret the intercept of a regression model. What are all values of our predictors set to be when looking at the intercept estimate?</p>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a></a><span class="fu">summary</span>(cat1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = transformers ~ pol, data = cah_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.3447 -1.1804 -0.3447  0.8196  3.8367 

Coefficients:
               Estimate Std. Error t value            Pr(&gt;|t|)    
(Intercept)     1.18039    0.09399  12.559 &lt;0.0000000000000002 ***
polIndependent  0.16434    0.12349   1.331               0.184    
polRepublican  -0.01713    0.14257  -0.120               0.904    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.501 on 799 degrees of freedom
  (198 observations deleted due to missingness)
Multiple R-squared:  0.003244,  Adjusted R-squared:  0.0007487 
F-statistic:   1.3 on 2 and 799 DF,  p-value: 0.2731</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<h3 id="refactor-reference-group">Refactor Reference Group</h3>
<p>Maybe we want to compare to a specific group</p>
<p>We need to then update the reference group</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a></a>cah_data<span class="sc">$</span>pol2 <span class="ot">&lt;-</span> <span class="fu">relevel</span>(cah_data<span class="sc">$</span>pol, <span class="at">ref =</span> <span class="st">"Independent"</span>)</span>
<span id="cb21-2"><a></a>cat2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(transformers <span class="sc">~</span> pol2,</span>
<span id="cb21-3"><a></a>           <span class="at">data =</span> cah_data)</span>
<span id="cb21-4"><a></a><span class="fu">summary</span>(cat2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = transformers ~ pol2, data = cah_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.3447 -1.1804 -0.3447  0.8196  3.8367 

Coefficients:
               Estimate Std. Error t value            Pr(&gt;|t|)    
(Intercept)     1.34473    0.08011  16.786 &lt;0.0000000000000002 ***
pol2Democrat   -0.16434    0.12349  -1.331               0.184    
pol2Republican -0.18146    0.13383  -1.356               0.175    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.501 on 799 degrees of freedom
  (198 observations deleted due to missingness)
Multiple R-squared:  0.003244,  Adjusted R-squared:  0.0007487 
F-statistic:   1.3 on 2 and 799 DF,  p-value: 0.2731</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<h3 id="lm-or-aov"><code>lm()</code> or <code>aov()</code></h3>
<p>Didn’t this look similar to something we’ve done before?</p>
<p>We are examining group differences in Transformer Movies (continuous) by Political Affiliation (group/categorical)</p>
<p>IT IS JUST AN ANOVA</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a></a>aov1 <span class="ot">&lt;-</span> <span class="fu">aov</span>(transformers <span class="sc">~</span> pol2,</span>
<span id="cb23-2"><a></a>           <span class="at">data =</span> cah_data)</span>
<span id="cb23-3"><a></a><span class="fu">summary</span>(aov1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)
pol2          2    5.9   2.929     1.3  0.273
Residuals   799 1799.8   2.252               
198 observations deleted due to missingness</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<h3 id="everything-is-a-linear-model">Everything is a linear model</h3>
<p>We are able to come to the same conclusions that there are no significant differences between groups</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a></a><span class="co"># Regression F-value</span></span>
<span id="cb25-2"><a></a><span class="fu">summary</span>(cat2)<span class="sc">$</span>fstatistic[[<span class="dv">1</span>]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.300092</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a></a><span class="co"># ANOVA F-value</span></span>
<span id="cb27-2"><a></a><span class="fu">summary</span>(aov1)[[<span class="dv">1</span>]][<span class="dv">1</span>, <span class="dv">4</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.300092</code></pre>
</div>
</div>
</section></section>
<section id="section" class="title-slide slide level1 center">
<h1><img data-src="images/clipboard-1177388101.webp"></h1>

</section>

<section id="break" class="title-slide slide level1 center">
<h1>Break ☕🍵🥐</h1>

</section>

<section>
<section id="activity-time" class="title-slide slide level1 center">
<h1>Activity Time 🎨</h1>

</section>
<section id="categories-in-action" class="slide level2">
<h2>Categories in Action</h2>
<p><strong>Goal:</strong> Gain greater familiarity with dummy coding and categorical predictors</p>
<p><strong>Scenario:</strong> We are researchers examining the impact of a new intervention on reducing the vocalization “6️⃣7️⃣” in the youths. We have done classroom observations to collect data on how many times students say “6️⃣7️⃣” after receiving the intervention. This is the data you have in front of you. Youths have been randomly assigned to one of 3 groups, and we need to determine which had the biggest impact.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>You will submit <strong>one</strong> Rmd file for the whole group. Be sure to include all group member’s names.</p>
</div>
</div>
</div>
</section>
<section class="slide level2 scrollable">

<h3 id="part-1">Part 1</h3>
<ol type="1">
<li>Get into groups of 4</li>
<li>Download the data <a href="../files/data/cat_reg.csv" download="categorical_reg.csv">[Download Categorical data (.csv)]</a></li>
<li>Enter the data into the spreadsheet with the chips that you have
<ol type="1">
<li>Each chip has an ID number (three digits) and a score (between 5 - 20)</li>
<li>These are the scores for the “post”</li>
<li>Be sure to identify their Group (the color of the chip)</li>
</ol></li>
</ol>
</section>
<section class="slide level2 scrollable">

<h3 id="part-2">Part 2</h3>
<ol type="1">
<li><p>Import the data into R</p>
<ol type="1">
<li>You will only have data for one school (be sure to <code>filter()</code> to include your data)</li>
</ol></li>
<li><p>On the board, put a portion of your data in a table along with your Dummy Code Scheme</p>
<ol type="1">
<li>Dr.&nbsp;Haraden should have different sections designated, if not, please remind him nicely (he’s doing his best)</li>
</ol></li>
</ol>
</section>
<section class="slide level2 scrollable">

<h3 id="part-3">Part 3</h3>
<ol type="1">
<li><p>Calculate the average 6️⃣7️⃣ Score for your reference group:<br>
Average Score for Group 1 (Reference) = ______________ = <span class="math inline">\(\beta_0\)</span></p></li>
<li><p>Calculate the average 6️⃣7️⃣ Score for your other two groups:<br>
Average Score for Group 2 = ______________<br>
Average Score for Group 3 = ______________</p></li>
<li><p>Calculate the “Coefficients” by finding the mean difference from the reference group:<br>
<span class="math inline">\(\beta_1\)</span> = (Avg. Group 2 Score) - (Avg. Group 1 Score) = __________<br>
<span class="math inline">\(\beta_2\)</span> = (Avg. Group 3 Score) - (Avg. Group 1 Score) = __________</p></li>
</ol>
</section>
<section class="slide level2">

<h3 id="part-4">Part 4</h3>
<p>Write out the regression equation for the model in which we are predicting 6️⃣7️⃣ Scores with our Dummy Variables. It should follow a format that we’ve used before ( <span class="math inline">\(Y = b_0 + b_1X_1 + b_2X_2 + e\)</span> ), but replacing your estimates in the correct places with the appropriate variables.</p>
<p>Once your group agrees on the equation, write it on the board for your group</p>
</section>
<section id="categories-in-action-using-r" class="slide level2">
<h2>Categories in Action: Using R</h2>
<p>Now that we have the data entered appropriately, let’s double check, and include some additional variables!</p>
<p>Import dataset, confirm predictions, include pre-scores to see how that changes interpretation</p>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>Dr.&nbsp;Haraden is going to start opening up R and doing a follow-along thing. You have been warned</p>
</div>
</div>
</div>
</section></section>
<section id="everything-is-a-linear-model-1" class="title-slide slide level1 center">
<h1>Everything is a linear model</h1>

<img data-src="../images/reg_precious.gif" class="r-stretch"></section>

<section id="maybe-another-break" class="title-slide slide level1 center">
<h1>Maybe another break?</h1>

</section>

<section>
<section id="introducing-generalized-linear-model" class="title-slide slide level1 center">
<h1>Introducing Generalized Linear Model</h1>

</section>
<section id="status" class="slide level2">
<h2>6️⃣7️⃣ Status</h2>
<p>In our last example, we were able to see how these categorical variables could predict a continuous variable. This is perfect for linear regression.</p>
<p><em>What if we want to see if students have “recovered” from</em> 6️⃣7️⃣?</p>
<p>We would then ask: ““Which participants dropped below the clinical threshold for 6️⃣7️⃣ at follow-up? Now, our outcome is either recovered or not recovered.”</p>
</section>
<section id="recovery-status" class="slide level2">
<h2>Recovery Status</h2>
<p>Now we have a binary outcome; Yes/No recovery</p>
<p>What happens when we fit a linear regression? What are the chances of someone with a pre-score of 12 recovering by the follow-up?</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a></a>cat_reg <span class="ot">&lt;-</span> <span class="fu">import</span>(<span class="fu">here</span>(<span class="st">"files"</span>, <span class="st">"data"</span>, </span>
<span id="cb29-2"><a></a>                       <span class="st">"cat_reg_complete.xlsx"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb29-3"><a></a>  janitor<span class="sc">::</span><span class="fu">clean_names</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb29-4"><a></a>  <span class="co"># 1 = recovered; 0 = not recovered</span></span>
<span id="cb29-5"><a></a>  <span class="fu">mutate</span>(<span class="at">recover =</span> <span class="fu">if_else</span>(post_score <span class="sc">&gt;</span> <span class="dv">12</span>, <span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb29-6"><a></a></span>
<span id="cb29-7"><a></a>cat_reg <span class="sc">%&gt;%</span> </span>
<span id="cb29-8"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(pre_score, recover)) <span class="sc">+</span></span>
<span id="cb29-9"><a></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="dv">0</span>, <span class="at">height =</span> <span class="fl">0.05</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb29-10"><a></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb29-11"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb29-12"><a></a>    <span class="at">title =</span> <span class="st">"Pre-Score predicting Recovery"</span></span>
<span id="cb29-13"><a></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="lec-11_categor_files/figure-revealjs/unnamed-chunk-17-1.png" width="960" class="r-stretch"></section>
<section id="probability-to-odds-to-log-odds" class="slide level2">
<h2>Probability to Odds to Log-Odds</h2>
<p><strong>Probability (<em>p</em>)</strong>: The chance of an event happening. Ranges from 0 to 1</p>
<p><strong>Odds</strong>: The ratio of the probability of an event happening to it <em>not</em> happening.</p>
<ul>
<li><p><span class="math inline">\(Odds = \frac{p}{1-p}\)</span></p></li>
<li><p>Ranges from 0 to ∞. An odds of 4 means the event is 4 times more likely to happen than not.</p></li>
</ul>
<p><strong>Log-Odds (logit)</strong>: The natural log of the odds</p>
<ul>
<li><p><span class="math inline">\(Logit(p) = ln(\frac{p}{1-p})\)</span></p></li>
<li><p>Ranges from -∞ to +∞</p></li>
</ul>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>This step transforms our bounded outcome variable (0/1) to an unbound one!</p>
</div>
</div>
</div>
</section>
<section id="generalized-linear-model-glm" class="slide level2">
<h2>Generalized Linear Model (GLM)</h2>
<p>A generalization of a linear model (duh) that is used when the response variable has a non-normal error distribution</p>
<p>Most commonly used when there is a binary (0-1) or count variable as the outcome (we will focus on the binary)</p>
<p>Ultimately, we are trying to identify the <strong><em>probability</em></strong> of the outcome taking the value 1 (“success”) that is being modeled in relation to the predictor variables</p>
</section>
<section class="slide level2">

<h3 id="glm-logistic-regression">GLM: Logistic Regression</h3>
<p><span class="math display">\[
transformation(p_i)=\beta_0+\beta_1x_{1,i} + \beta_2x_{2,i} + \cdots+\beta_lx_{k,i}
\]</span></p>
<p>We have to apply a transformation to the left side so that it can take variables beyond just 0 &amp; 1</p>
<p>A common transformation is the <span class="math inline">\(logit\ transformation\)</span></p>
<p><span class="math display">\[
\log_{e}\left( \frac{p_i}{1-p_i} \right) = \beta_0 + \beta_1 x_{1,i} + \beta_2 x_{2,i} + \cdots + \beta_k x_{k,i}
\]</span></p>
</section>
<section class="slide level2">

<h3 id="glm---cah-data">GLM - CAH data 👻</h3>
<p>Research Question: <em>Does age, the number of books and the number of transformer movies predict the belief in ghosts?</em></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a></a><span class="do">## Using glm() instead of lm()</span></span>
<span id="cb30-2"><a></a>ln1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(ghosts <span class="sc">~</span> age <span class="sc">+</span> books <span class="sc">+</span> transformers, </span>
<span id="cb30-3"><a></a>           <span class="at">data =</span> cah_data, </span>
<span id="cb30-4"><a></a>           <span class="do">## This is new</span></span>
<span id="cb30-5"><a></a>           <span class="do">##Tells the model we are doing logistic regression with a binary outcome</span></span>
<span id="cb30-6"><a></a>           <span class="at">family =</span> <span class="st">"binomial"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section class="slide level2">

<h3 id="glm---cah-data-interpretation">GLM - CAH data Interpretation</h3>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Interpretation is still the same as linear regression, <strong><em>except</em></strong> we are dealing with <u><strong>log-odds</strong> of the outcome.</u> What does that mean??</p>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a></a><span class="fu">summary</span>(ln1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = ghosts ~ age + books + transformers, family = "binomial", 
    data = cah_data)

Coefficients:
               Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -0.5175834  0.2466775  -2.098 0.035886 *  
age          -0.0046259  0.0044171  -1.047 0.294975    
books         0.0008966  0.0009700   0.924 0.355311    
transformers  0.1643321  0.0453671   3.622 0.000292 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1195.3  on 900  degrees of freedom
Residual deviance: 1177.0  on 897  degrees of freedom
  (99 observations deleted due to missingness)
AIC: 1185

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<h3 id="glm---cah-data-interpretation-tables">GLM - CAH data Interpretation (tables)</h3>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>We want to be able to interpret these coefficients more easily so we put them into <strong>Odds Ratios</strong></p>
</div>
</div>
</div>
<p><code>sjPlot</code> is always coming in with the good tables</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a></a><span class="fu">tab_model</span>(ln1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top" style="border-collapse:collapse; border:none;">
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">&nbsp;</th>
<th colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">ghosts</th>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Predictors</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Odds Ratios</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">CI</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">p</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">(Intercept)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.60</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.37&nbsp;–&nbsp;0.96</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>0.036</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">age</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.99&nbsp;–&nbsp;1.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.295</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">books</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.00&nbsp;–&nbsp;1.00</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.355</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">transformers</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.18</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.08&nbsp;–&nbsp;1.29</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">Observations</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">901</td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">R<sup>2</sup> Tjur</td>
<td colspan="3" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">0.020</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="odds-ratios-or" class="slide level2">
<h2>Odds Ratios (OR)</h2>
<p><strong>OR &gt; 1:</strong> The predictor increases the odds of the outcome. (e.g., OR of 2.5 means the odds of believing in ghosts are 2.5 times higher).</p>
<p><strong>OR &lt; 1:</strong> The predictor decreases the odds of the outcome. (e.g., OR of 0.4 means the odds of believing in ghosts are 60% lower).</p>
<p><strong>OR = 1:</strong> The predictor has no effect on the odds of the outcome.</p>
</section>
<section id="visualization" class="slide level2">
<h2>Visualization</h2>
<p>Extract the model implied probabilities for each individual</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a></a>probs <span class="ot">&lt;-</span> broom<span class="sc">::</span><span class="fu">augment</span>(ln1, <span class="at">type.predict =</span> <span class="st">"response"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Plotting the predicted probabilities</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a></a>probs <span class="sc">%&gt;%</span> </span>
<span id="cb35-2"><a></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(age, .fitted)) <span class="sc">+</span></span>
<span id="cb35-3"><a></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">linewidth =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb35-4"><a></a>  <span class="fu">labs</span>(</span>
<span id="cb35-5"><a></a>    <span class="at">title =</span> <span class="st">"Predicted Probability of Believing in Ghosts by Age"</span>,</span>
<span id="cb35-6"><a></a>    <span class="at">subtitle =</span> <span class="st">"Holding # of Books and Transformers Movies at their mean"</span>,</span>
<span id="cb35-7"><a></a>    <span class="at">x =</span> <span class="st">"Age (years)"</span>,</span>
<span id="cb35-8"><a></a>    <span class="at">y =</span> <span class="st">"Predicted Probability of Believing in Ghosts"</span></span>
<span id="cb35-9"><a></a>  ) <span class="sc">+</span></span>
<span id="cb35-10"><a></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">1</span>) <span class="sc">+</span> <span class="co"># Keep the y-axis bounded at 0 and 1</span></span>
<span id="cb35-11"><a></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="lec-11_categor_files/figure-revealjs/unnamed-chunk-22-1.png" width="960" class="r-stretch"></section>
<section id="logistic-regression-summary" class="slide level2">
<h2>Logistic Regression: Summary</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Feature</strong></th>
<th style="text-align: left;"><strong>Linear Regression</strong></th>
<th style="text-align: left;"><strong>Logistic Regression</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Outcome Variable</td>
<td style="text-align: left;">Continuous</td>
<td style="text-align: left;">Categorical (Binary)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Equation</td>
<td style="text-align: left;"><span class="math inline">\(Y=β_0+β_1X\)</span></td>
<td style="text-align: left;"><span class="math inline">\(ln⁡(\frac{p}{1-p})=β_0+β_1X\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Key Interpretation</td>
<td style="text-align: left;"><span class="math inline">\(\beta_1\)</span> is the change in the mean of Y</td>
<td style="text-align: left;"><span class="math inline">\(\exp(\beta_1)\)</span> is theodds ratio</td>
</tr>
<tr class="even">
<td style="text-align: left;">R Function</td>
<td style="text-align: left;"><code>lm()</code></td>
<td style="text-align: left;"><code>glm(..., family="binomial")</code></td>
</tr>
</tbody>
</table>
</section>
<section class="slide level2">



</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="images/640_hex.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="https://dharaden.github.io/psyc640/">course-website</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: false,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/dharaden\.github\.io\/psyc640");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>