<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.26">

  <title>PSYC 640 - Graduate Statistics – Week 06: Comparing Means</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-5ae9c59b2727fcd5357d4f034d95f9e0.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="Week 06: Comparing Means – PSYC 640 - Graduate Statistics">
<meta property="og:description" content="Date: September 29, 2025">
<meta property="og:site_name" content="PSYC 640 - Graduate Statistics">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Week 06: Comparing Means</h1>
  <p class="subtitle">Date: September 29, 2025</p>

<div class="quarto-title-authors">
</div>

</section>
<section id="today" class="slide level2">
<h2>Today…</h2>
<p>HIGHLIGHT THE USE OF THE <code>rm()</code> FUNCTION TO GET RID OF THINGS IN YOUR ENVIRONMENT</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="co"># File management</span></span>
<span id="cb1-2"><a></a><span class="fu">library</span>(here)</span>
<span id="cb1-3"><a></a><span class="co"># for dplyr, ggplot2</span></span>
<span id="cb1-4"><a></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-5"><a></a><span class="co"># Pretty tables</span></span>
<span id="cb1-6"><a></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb1-7"><a></a><span class="fu">library</span>(ggstatsplot)</span>
<span id="cb1-8"><a></a><span class="co"># making tests easier</span></span>
<span id="cb1-9"><a></a><span class="fu">library</span>(lsr) <span class="do">## NEW</span></span>
<span id="cb1-10"><a></a><span class="co"># Getting marginal means</span></span>
<span id="cb1-11"><a></a><span class="fu">library</span>(emmeans)</span>
<span id="cb1-12"><a></a></span>
<span id="cb1-13"><a></a><span class="co">#Remove Scientific Notation </span></span>
<span id="cb1-14"><a></a><span class="fu">options</span>(<span class="at">scipen=</span><span class="dv">999</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section>
<section id="comparing-means" class="title-slide slide level1 center">
<h1>Comparing Means</h1>
<p>Converting to a t-score and checking against the t-distribution</p>
<ul>
<li><p>One-Sample</p></li>
<li><p>Independent Sample</p></li>
<li><p>Paired Sample</p></li>
</ul>
</section>
<section id="but-firstdegrees-of-freedom" class="slide level2">
<h2>but first…Degrees of Freedom</h2>
<p><strong>Degrees of Freedom:</strong> <em>the number of values in the final calculation of a statistic that are free to vary</em></p>
<p><strong>Example</strong>: Drawing a triangle</p>
<p><strong>❓Question:</strong> If you have a sample of 5 scores and you know the mean is 3, how many of those scores can you <em>freely</em> change?</p>
</section>
<section id="one-sample-t-test" class="slide level2">
<h2>One Sample t-test</h2>
<p><em>t</em>-tests were developed by William Sealy Gosset, who was a chemist studying the grains used in making beer. (He worked for Guinness.)</p>
<ul>
<li><p>Specifically, he wanted to know whether particular strains of grain made better or worse beer than the standard.</p></li>
<li><p>He developed the <em>t</em>-test, to test small samples of beer against a population with an unknown standard deviation.</p>
<ul>
<li>Probably had input from Karl Pearson and Ronald Fisher</li>
</ul></li>
<li><p>Published this as “Student” because Guinness didn’t want these tests tied to the production of beer.</p></li>
</ul>
</section>
<section class="slide level2">

<p><strong><em>One-sample tests compare your given sample with a “known” population</em></strong></p>
<p>Research question: does this sample come from this population?</p>
<p><strong>Hypotheses</strong></p>
<ul>
<li><p><span class="math inline">\(H_0\)</span>: Yes, this sample comes from this population.</p></li>
<li><p><span class="math inline">\(H_1\)</span>: No, this sample comes from a different population.</p></li>
</ul>
</section>
<section class="slide level2">

<p>To calculate the t-statistic, we generally use this formula:</p>
<p><span class="math display">\[t_{df=N-1} = \frac{\bar{X}-\mu}{\frac{\hat{\sigma}}{\sqrt{N}}}\]</span></p>
<p>The heavier tails of the t-distribution, especially for small N, are the penalty we pay for having to estimate the population standard deviation from the sample.</p>
</section>
<section class="slide level2">


<img data-src="../images/t-to-z.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="example" class="slide level2">
<h2>Example</h2>
<p>For examples today, we will use a dataset from Cards Against Humanity’s Pulse of the Nation survey (<a href="https://thepulseofthenation.com/" class="uri">https://thepulseofthenation.com/</a>)</p>
<ul>
<li><a href="../files/data/CAH.csv" download="CAH.csv">Cards Against Humanity Data (.csv)</a></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a><span class="do">## We are using read_csv() this time</span></span>
<span id="cb2-2"><a></a><span class="do">## import() was doing something strange with missing values</span></span>
<span id="cb2-3"><a></a>cah <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"files"</span>, <span class="st">"data"</span>, <span class="st">"CAH.csv"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb2-4"><a></a>  janitor<span class="sc">::</span><span class="fu">clean_names</span>() </span>
<span id="cb2-5"><a></a></span>
<span id="cb2-6"><a></a><span class="fu">head</span>(cah)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 16
     id income gender   age age_range political_affiliation education  ethnicity
  &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;                 &lt;chr&gt;      &lt;chr&gt;    
1     1   8000 Female    64 55-64     Democrat              College d… White    
2     2  68000 Female    56 55-64     Democrat              High scho… Black    
3     3  46000 Male      63 55-64     Independent           Some coll… White    
4     4  51000 Male      48 45-54     Republican            High scho… White    
5     5 100000 Female    32 25-34     Democrat              Some coll… White    
6     6  54000 Female    64 55-64     Democrat              Some coll… White    
# ℹ 8 more variables: marital_status &lt;chr&gt;, climate_change &lt;chr&gt;,
#   transformers &lt;dbl&gt;, books &lt;dbl&gt;, ghosts &lt;chr&gt;, spending &lt;chr&gt;,
#   choice &lt;chr&gt;, shower_pee &lt;chr&gt;</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<h3 id="assumptions-of-the-one-sample-t-test"><strong>Assumptions of the one-sample <em>t</em>-test</strong></h3>
<p><strong>Normality.</strong> We assume the sampling distribution of the mean is normally distributed. Under what two conditions can we be assured that this is true?</p>
<p><strong>Independence.</strong> Observations in the dataset are not associated with one another. Put another way, collecting a score from Participant A doesn’t tell me anything about what Participant B will say. How can we be safe in this assumption?</p>
</section>
<section class="slide level2">

<h3 id="a-brief-example">A brief example</h3>
<p>Using the Cards Against Humanity data, we find that participants identified having approximately 22.33 ( <span class="math inline">\(sd = 75.87\)</span> ) books in their home. We know that the average household has approximately 50 books. How does this sample represent the larger united states?</p>
<p><strong>Hypotheses</strong></p>
<p><span class="math inline">\(H_0: \mu = 50\)</span></p>
<p><span class="math inline">\(H_1: \mu \neq 50\)</span></p>
</section>
<section class="slide level2">

<div class="columns">
<div class="column" style="width:50%;">
<p><span class="math display">\[\mu = 50\]</span></p>
<p><span class="math display">\[N = 1000\]</span></p>
<p><span class="math display">\[ \bar{X} = 22.33 \]</span></p>
<p><span class="math display">\[ s = 75.87 \]</span></p>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a><span class="fu">t.test</span>(<span class="at">x =</span> cah<span class="sc">$</span>books, <span class="at">mu =</span> <span class="dv">50</span>,        </span>
<span id="cb4-2"><a></a>       <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  cah$books
t = -11.399, df = 976, p-value &lt; 0.00000000000000022
alternative hypothesis: true mean is not equal to 50
95 percent confidence interval:
 17.56785 27.09438
sample estimates:
mean of x 
 22.33112 </code></pre>
</div>
</div>
</div></div>
</section>
<section class="slide level2">

<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a></a>lsr<span class="sc">::</span><span class="fu">oneSampleTTest</span>(<span class="at">x =</span> cah<span class="sc">$</span>books, <span class="at">mu =</span> <span class="dv">50</span>, </span>
<span id="cb6-2"><a></a>                    <span class="at">one.sided =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   One sample t-test 

Data variable:   cah$books 

Descriptive statistics: 
             books
   mean     22.331
   std dev. 75.869

Hypotheses: 
   null:        population mean equals 50 
   alternative: population mean not equal to 50 

Test results: 
   t-statistic:  -11.399 
   degrees of freedom:  976 
   p-value:  &lt;.001 

Other information: 
   two-sided 95% confidence interval:  [17.568, 27.094] 
   estimated effect size (Cohen's d):  0.365 </code></pre>
</div>
</div>
</section>
<section id="cohens-d" class="slide level2">
<h2>Cohen’s D</h2>
<p>Cohen suggested one of the most common effect size estimates—the standardized mean difference—useful when comparing a group mean to a population mean or two group means to each other.</p>
<p><span class="math display">\[\delta = \frac{\mu_1 - \mu_0}{\sigma} \approx d = \frac{\bar{X}-\mu}{\hat{\sigma}}\]</span></p>
<p>Cohen’s d is in the standard deviation (Z) metric.</p>
</section>
<section class="slide level2">

<p>Cohens’s d for these data is <span class="math inline">\(0.365\)</span>. In other words, the sample mean differs from the population mean by <span class="math inline">\(0.365\)</span> standard deviation units.</p>
<p>Cohen (1988) suggests the following guidelines for interpreting the size of d:</p>
<ul>
<li><p>.2 = Small</p></li>
<li><p>.5 = Medium</p></li>
<li><p>.8 = Large</p></li>
</ul>
<p><span style="font-size:30px;">Cohen, J. (1988), Statistical power analysis for the behavioral sciences (2nd Ed.). Hillsdale: Lawrence Erlbaum.</span></p>
</section>
<section class="slide level2">

<h3 id="the-usefulness-of-the-one-sample-t-test">The usefulness of the one-sample <em>t</em>-test</h3>
<p>How often will you conducted a one-sample <em>t</em>-test on raw data?</p>
<ul>
<li>(Probably) never</li>
</ul>
<p>How often will you come across one-sample <em>t</em>-tests?</p>
<ul>
<li>(Probably) a lot!</li>
</ul>
<p>The one-sample <em>t</em>-test is used to test coefficients in a model.</p>
</section></section>
<section id="your-turn" class="title-slide slide level1 center">
<h1>YOUR TURN 💻</h1>

</section>

<section>
<section id="independent-samples-t-test" class="title-slide slide level1 center">
<h1>Independent Samples t-test</h1>
<p>Two different types: Student’s &amp; Welch’s</p>
<ul>
<li>Start with Student’s t-test which assumes equal variances between the groups</li>
</ul>
<p><span class="math display">\[ t = \frac{\bar{X_1} - \bar{X_2}}{SE(\bar{X_1} - \bar{X_2})} \]</span></p>
</section>
<section id="students-t-test" class="slide level2">
<h2>Student’s t-test</h2>
<p><span class="math display">\[ H_0 : \mu_1 = \mu_2  \ \  H_1 : \mu_1 \neq \mu_2 \]</span></p>

<img data-src="../images/student_H.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section class="slide level2">

<h3 id="students-t-test-calculate-se">Student’s t-test: Calculate SE</h3>
<p>Are able to use a pooled variance estimate</p>
<p>Both variances/standard deviations are assumed to be equal</p>
<p>Therefore:</p>
<p><span class="math display">\[ SE(\bar{X_1} - \bar{X_2}) = \hat{\sigma} \sqrt{\frac{1}{N_1} + \frac{1}{N_2}} \]</span></p>
<p>We are calculating the <strong>Standard Error of the Difference between means</strong></p>
<p>Degrees of Freedom: Total N - 2</p>
</section>
<section class="slide level2">

<h3 id="students-t-test-1">Student’s t-test</h3>
<p>Let’s try it out using the traditional <code>t.test()</code> function</p>
<p>Difference in Books by Belief in Ghosts</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a><span class="fu">t.test</span>(<span class="at">formula =</span> books <span class="sc">~</span> ghosts,</span>
<span id="cb8-2"><a></a>       <span class="at">data =</span> cah, <span class="at">var.equal =</span> <span class="cn">TRUE</span> )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  books by ghosts
t = -1.3642, df = 951, p-value = 0.1728
alternative hypothesis: true difference in means between group No and group Yes is not equal to 0
95 percent confidence interval:
 -16.98193   3.05404
sample estimates:
 mean in group No mean in group Yes 
         19.86525          26.82920 </code></pre>
</div>
</div>
</section>
<section id="welchs-t-test" class="slide level2">
<h2>Welch’s t-test</h2>
<p><span class="math display">\[ H_0 : \mu_1 = \mu_2  \ \  H_1 : \mu_1 \neq \mu_2 \]</span></p>

<img data-src="../images/welch_H.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section class="slide level2">

<h3 id="welchs-t-test-calculate-se">Welch’s t-test: Calculate SE</h3>
<p>Since the variances are not equal, we have to estimate the SE differently</p>
<p><span class="math display">\[ SE(\bar{X_1} - \bar{X_2}) = \sqrt{\frac{\hat{\sigma_1^2}}{N_1} + \frac{\hat{\sigma_2^2}}{N_2}} \]</span></p>
<p>Degrees of Freedom is also very different:</p>

<img data-src="../images/welch_df.png" class="quarto-figure quarto-figure-center r-stretch" width="380"></section>
<section class="slide level2">

<h3 id="welchs-t-test-in-r-classic">Welch’s t-test: In R (classic)</h3>
<p>Let’s try it out using the traditional <code>t.test()</code> function…turns out it is pretty straightforward</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a></a><span class="fu">t.test</span>(<span class="at">formula =</span> books <span class="sc">~</span> ghosts,</span>
<span id="cb10-2"><a></a>       <span class="at">data =</span> cah, <span class="at">var.equal =</span> <span class="cn">FALSE</span> )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  books by ghosts
t = -1.2319, df = 542.85, p-value = 0.2185
alternative hypothesis: true difference in means between group No and group Yes is not equal to 0
95 percent confidence interval:
 -18.068820   4.140927
sample estimates:
 mean in group No mean in group Yes 
         19.86525          26.82920 </code></pre>
</div>
</div>
</section>
<section id="cool-visualizations" class="slide level2">
<h2>Cool Visualizations</h2>
<p>The library <a href="https://indrajeetpatil.github.io/ggstatsplot/">ggstatsplot</a> has some wonderful visualizations of various tests</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a>ggstatsplot<span class="sc">::</span><span class="fu">ggbetweenstats</span>(   </span>
<span id="cb12-2"><a></a>  <span class="at">data  =</span> cah,   </span>
<span id="cb12-3"><a></a>  <span class="at">x     =</span> ghosts,   </span>
<span id="cb12-4"><a></a>  <span class="at">y     =</span> books,   </span>
<span id="cb12-5"><a></a>  <span class="at">title =</span> <span class="st">"Distribution of books by belief in ghosts"</span> )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="lec-6_mean_files/figure-revealjs/unnamed-chunk-7-1.png" width="960" class="r-stretch"></section>
<section class="slide level2">

<h3 id="interpreting-and-writing-up-an-independent-samples-t-test">Interpreting and writing up an independent samples t-test</h3>
<div style="font-size: 30px">
<p>The first sentence usually conveys some descriptive information about the two groups you were comparing. Then you identify the type of test you conducted and what was determined (be sure to include the “stat block” here as well with the t-statistic, df, p-value, CI and Effect size). Finish it up by putting that into person words and saying what that means.</p>
</div>
<blockquote>
<div style="font-size: 30px">
<p>The mean amount of books in the household for the group who did not believe in ghosts was 19.9 (SD = 61.2), while the mean for those who believed in ghosts was 26.8 (SD = 96.4). A Student’s independent samples t-test showed that there was not a significant mean difference (<em>t</em>(951)=-1.364, <em>p</em>=.17, <span class="math inline">\(CI_{95}\)</span>=[-16.98, 3.05]). This suggests that there is no difference in amount of books in their household as a function of belief in ghosts.</p>
</div>
</blockquote>
</section></section>
<section>
<section id="your-turn-1" class="title-slide slide level1 center">
<h1>YOUR TURN 💻</h1>

</section>
<section id="paired-samples-t-test" class="slide level2">
<h2>Paired Samples <span class="math inline">\(t\)</span>-Test</h2>
<p><a href="https://learningstatisticswithr.com/book/ttest.html#pairedsamplesttest">Chapter 13.5 - Learning Stats with R</a></p>
<p>Also called “Dependent Samples t-test”</p>
<ul>
<li><p>We have been testing means between two <em>independent</em> samples. Participants may be randomly assigned to the separate groups</p>
<ul>
<li>This is limited to those types of study designs, but what if we have repeated measures?</li>
</ul></li>
<li><p>We will then need to compare scores across people…the samples we are comparing now <em>depend</em> on one another and are <em>paired</em></p></li>
</ul>
</section>
<section class="slide level2">

<h3 id="paired-samples-t-test-1">Paired Samples <span class="math inline">\(t\)</span>-test</h3>
<p>Each of the repeated measures (or pairs) can be viewed as a <em>difference score</em></p>
<p>This reduces the analysis to a one-sample t-test of the <em>difference score</em></p>
<ul>
<li>We are comparing the sample (i.e., difference scores) to a population <span class="math inline">\(\mu\)</span> = 0</li>
</ul>
</section>
<section class="slide level2">

<h3 id="assumptions-paired-samples">Assumptions: Paired Samples</h3>
<p>The variable of interest (<em>difference scores</em>):</p>
<ul>
<li><p>Continuous (Interval/Ratio)</p></li>
<li><p>Have 2 groups (and only two groups) that are matched</p></li>
<li><p>Normally Distributed</p></li>
</ul>
</section>
<section class="slide level2">

<h3 id="why-paired-samples">Why paired samples??</h3>
<p>Previously, we looked at independent samples <span class="math inline">\(t\)</span>-tests, which we <em>could</em> do here as well (nobody will yell at you)</p>
<ul>
<li><p>However, this would violate the assumption that the data points are independent of one another!</p></li>
<li><p>Within vs.&nbsp;Between-subjects</p></li>
</ul>
</section>
<section class="slide level2">

<h3 id="within-vs.-between-subjects">Within vs.&nbsp;Between Subjects</h3>

<img data-src="../images/between-subjects-design.avif" class="quarto-figure quarto-figure-center r-stretch"></section>
<section class="slide level2">

<h3 id="paired-samples-single-sample">Paired Samples: Single Sample</h3>
<p>Instead of focusing on these variables as being separate/independent, we need to be able to account for their dependency on one another</p>
<p>This is done by calculating a <em>difference</em> or <em>change</em> score for each participant</p>
<p><span class="math display">\[ D_i = X_{i1} - X_{i2} \]</span></p>
<p>Notice: The equation is set up as <code>variable1</code> minus <code>variable2</code>. This will be important when we interpret the results</p>
</section>
<section class="slide level2">

<h3 id="paired-samples-hypotheses-t-statistic">Paired Samples: Hypotheses &amp; <span class="math inline">\(t\)</span>-statistic</h3>
<p>The hypotheses would then be:</p>
<p><span class="math display">\[ H_0:  \mu_D = 0; H_1: \mu_D \neq 0 \]</span></p>
<p>And to calculate our t-statistic: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="math inline">\(t_{df=n-1} = \frac{\bar{D}}{SE(D)}\)</span></p>
<p>where the Standard Error of the difference score is: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span class="math inline">\(\frac{\hat{\sigma_D}}{\sqrt{N}}\)</span></p>
</section>
<section id="review-of-the-t-test-process" class="slide level2 scrollable">
<h2>Review of the t-test process</h2>
<ol type="1">
<li><p>Collect Sample and define hypotheses</p></li>
<li><p>Set alpha level</p></li>
<li><p>Determine the sampling distribution (<span class="math inline">\(t\)</span> distribution for now)</p></li>
<li><p>Identify the critical value that corresponds to alpha and <em>df</em></p></li>
<li><p>Calculate test statistic for sample collected</p></li>
<li><p>Inspect &amp; compare statistic to critical value; Calculate probability</p></li>
</ol>
</section></section>
<section>
<section id="example-1-simple-by-hand" class="title-slide slide level1 center">
<h1>Example 1: Simple (by hand)</h1>
<p>Participants are placed in two differently colored rooms (counterbalanced) and are asked to rate overall happiness levels after spending 5 minutes inside the rooms. There are no windows, but there is a nice lamp and chair.</p>
<p>Hypotheses:</p>
<ul>
<li><p><span class="math inline">\(H_0:\)</span> There is no difference in ratings of happiness between the rooms ( <span class="math inline">\(\mu = 0\)</span> )</p></li>
<li><p><span class="math inline">\(H_1:\)</span> There is a difference in ratings of happiness between the rooms ( <span class="math inline">\(\mu \neq 0\)</span> )</p></li>
</ul>
</section>
<section class="slide level2">

<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Participant</th>
<th style="text-align: center;">Blue Room Score</th>
<th style="text-align: center;">Orange Room Score</th>
<th style="text-align: center;">Difference (<span class="math inline">\(X_{iB} - X_{iO}\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">-3</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">-8</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">-2</td>
</tr>
</tbody>
</table>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a>ex1 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">id =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>),</span>
<span id="cb13-2"><a></a>                  <span class="at">blue =</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">9</span>,<span class="dv">2</span>,<span class="dv">9</span>,<span class="dv">5</span>,<span class="dv">5</span>),    </span>
<span id="cb13-3"><a></a>                  <span class="at">orange =</span> <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">9</span>,<span class="dv">10</span>,<span class="dv">6</span>,<span class="dv">2</span>,<span class="dv">7</span>),   </span>
<span id="cb13-4"><a></a>                  <span class="at">diff_score =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">0</span>, <span class="sc">-</span><span class="dv">8</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="sc">-</span><span class="dv">2</span>))</span>
<span id="cb13-5"><a></a>  <span class="fu">head</span>(ex1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  id blue orange diff_score
1  1    3      6         -3
2  2    9      9          0
3  3    2     10         -8
4  4    9      6          3
5  5    5      2          3
6  6    5      7         -2</code></pre>
</div>
</div>
</section>
<section id="determining-t-crit" class="slide level2">
<h2>Determining <span class="math inline">\(t\)</span>-crit</h2>
<p>Can look things up using a <a href="https://www.tdistributiontable.com/">t-table</a> where you need the degrees of freedom and the alpha</p>
<p>But we have R to do those things for us:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a><span class="co">#the qt() function is for a 1 tailed test, so we are having to divide it in half to get both tails </span></span>
<span id="cb15-2"><a></a></span>
<span id="cb15-3"><a></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span> </span>
<span id="cb15-4"><a></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(ex1) </span>
<span id="cb15-5"><a></a>t_crit <span class="ot">&lt;-</span> <span class="fu">qt</span>(alpha<span class="sc">/</span><span class="dv">2</span>, n<span class="dv">-1</span>) </span>
<span id="cb15-6"><a></a>t_crit</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.570582</code></pre>
</div>
</div>
</section>
<section id="calculating-t" class="slide level2">
<h2>Calculating t</h2>
<p>Let’s get all of the information for the sample we are focusing on (difference scores):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a>d <span class="ot">&lt;-</span> <span class="fu">mean</span>(ex1<span class="sc">$</span>diff_score) </span>
<span id="cb17-2"><a></a>d </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.166667</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a></a>sd_diff <span class="ot">&lt;-</span> <span class="fu">sd</span>(ex1<span class="sc">$</span>diff_score) </span>
<span id="cb19-2"><a></a>sd_diff</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.167333</code></pre>
</div>
</div>
</section>
<section id="calculating-t-1" class="slide level2">
<h2>Calculating t</h2>
<p>Now we can calculate our <span class="math inline">\(t\)</span>-statistic: <span class="math display">\[t_{df=n-1} = \frac{\bar{D}}{\frac{sd_{diff}}{\sqrt{n}}}\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a></a>t_stat <span class="ot">&lt;-</span> d<span class="sc">/</span>(sd_diff<span class="sc">/</span>(<span class="fu">sqrt</span>(n))) </span>
<span id="cb21-2"><a></a>t_stat  </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.6857474</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a></a><span class="co">#Probability of this t-statistic  </span></span>
<span id="cb23-2"><a></a>p_val <span class="ot">&lt;-</span> <span class="fu">pt</span>(t_stat, n<span class="dv">-1</span>)<span class="sc">*</span><span class="dv">2</span> </span>
<span id="cb23-3"><a></a>p_val</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5233677</code></pre>
</div>
</div>
</section>
<section id="make-a-decision" class="slide level2">
<h2>Make a decision</h2>
<p>Hypotheses:</p>
<ul>
<li><p><span class="math inline">\(H_0:\)</span> There is no difference in ratings of happiness between the rooms ( <span class="math inline">\(\mu = 0\)</span> )</p></li>
<li><p><span class="math inline">\(H_1:\)</span> There is a difference in ratings of happiness between the rooms ( <span class="math inline">\(\mu \neq 0\)</span> )</p></li>
</ul>
<table class="caption-top">
<colgroup>
<col style="width: 11%">
<col style="width: 35%">
<col style="width: 27%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(alpha\)</span></th>
<th style="text-align: center;"><span class="math inline">\(t-crit\)</span></th>
<th style="text-align: center;"><span class="math inline">\(t-statistic\)</span></th>
<th style="text-align: center;"><span class="math inline">\(p-value\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.05</td>
<td style="text-align: center;"><span class="math inline">\(\pm\)</span> -2.57</td>
<td style="text-align: center;">-0.69</td>
<td style="text-align: center;">0.52</td>
</tr>
</tbody>
</table>
<p><strong>What can we conclude??</strong></p>
</section></section>
<section>
<section id="example-2-data-in-r" class="title-slide slide level1 center">
<h1>Example 2: Data in R</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a></a>state_school <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://raw.githubusercontent.com/dharaden/dharaden.github.io/main/data/NM-NY_CAS.csv"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb25-2"><a></a>  <span class="co">#create an ID variable</span></span>
<span id="cb25-3"><a></a>  <span class="fu">rowid_to_column</span>(<span class="st">"id"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="lets-look-at-the-data" class="slide level2">
<h2>Let’s Look at the data</h2>
<p>Research Question: Is there a difference between school nights and weekend nights for amount of time slept?</p>
<p>Only looking at the variables that we are potentially interested in:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a></a>state_school <span class="sc">%&gt;%</span>    </span>
<span id="cb26-2"><a></a>  <span class="fu">select</span>(id, Gender, Ageyears, Sleep_Hours_Schoolnight, Sleep_Hours_Non_Schoolnight) <span class="sc">%&gt;%</span>    </span>
<span id="cb26-3"><a></a>  <span class="fu">head</span>() <span class="co">#look at first few observations</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
     id Gender Ageyears Sleep_Hours_Schoolnight Sleep_Hours_Non_Schoolnight
  &lt;int&gt; &lt;chr&gt;     &lt;dbl&gt;                   &lt;dbl&gt;                       &lt;dbl&gt;
1     1 Female       16                     8                            13
2     2 Male         17                     8                             9
3     3 Female       19                     8                             7
4     4 Male         17                     8                             9
5     5 Male         16                     8.5                           5
6     6 Female       11                    11                            12</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<h3 id="difference-score">Difference Score</h3>
<div style="font-size: 30px">
<p>This can be done in a couple different ways and sometimes you will see things computed this way:</p>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a></a>state_school<span class="sc">$</span>sleep_diff <span class="ot">&lt;-</span> state_school<span class="sc">$</span>Sleep_Hours_Schoolnight <span class="sc">-</span> state_school<span class="sc">$</span>Sleep_Hours_Non_Schoolnight</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div style="font-size: 30px">
<p>However, we like the <code>tidyverse</code> so why don’t we use the <code>mutate()</code> function</p>
<p>And I always overdo things, so I am going to make a new dataset that only has the variables that I’m interested in (<code>sleep_state_school</code>)</p>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a></a>sleep_state_school <span class="ot">&lt;-</span> state_school <span class="sc">%&gt;%</span>    </span>
<span id="cb29-2"><a></a>  <span class="fu">mutate</span>(<span class="at">sleep_diff =</span> Sleep_Hours_Schoolnight <span class="sc">-</span> Sleep_Hours_Non_Schoolnight) <span class="sc">%&gt;%</span>   </span>
<span id="cb29-3"><a></a>  <span class="fu">select</span>(id, Gender, Ageyears, Sleep_Hours_Schoolnight,          Sleep_Hours_Non_Schoolnight, sleep_diff)  </span>
<span id="cb29-4"><a></a></span>
<span id="cb29-5"><a></a><span class="fu">head</span>(sleep_state_school)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
     id Gender Ageyears Sleep_Hours_Schoolni…¹ Sleep_Hours_Non_Scho…² sleep_diff
  &lt;int&gt; &lt;chr&gt;     &lt;dbl&gt;                  &lt;dbl&gt;                  &lt;dbl&gt;      &lt;dbl&gt;
1     1 Female       16                    8                       13       -5  
2     2 Male         17                    8                        9       -1  
3     3 Female       19                    8                        7        1  
4     4 Male         17                    8                        9       -1  
5     5 Male         16                    8.5                      5        3.5
6     6 Female       11                   11                       12       -1  
# ℹ abbreviated names: ¹​Sleep_Hours_Schoolnight, ²​Sleep_Hours_Non_Schoolnight</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<h3 id="visualizing">Visualizing</h3>
<p>Now that we have our variable of interest, let’s take a look at it!</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a></a>sleep_state_school <span class="sc">%&gt;%</span>   </span>
<span id="cb31-2"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(sleep_diff)) <span class="sc">+</span>    </span>
<span id="cb31-3"><a></a>  <span class="fu">geom_histogram</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="lec-6_mean_files/figure-revealjs/unnamed-chunk-16-1.png" width="960" class="r-stretch"></section>
<section id="doing-the-test-in-r-one-sample" class="slide level2">
<h2>Doing the test in R: One Sample</h2>
<p>Since we have calculated the difference scores, we can basically just do a one-sample t-test with the <code>lsr</code> library</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a></a><span class="fu">oneSampleTTest</span>(sleep_state_school<span class="sc">$</span>sleep_diff, <span class="at">mu =</span> <span class="dv">0</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   One sample t-test 

Data variable:   sleep_state_school$sleep_diff 

Descriptive statistics: 
            sleep_diff
   mean         -1.866
   std dev.      2.741

Hypotheses: 
   null:        population mean equals 0 
   alternative: population mean not equal to 0 

Test results: 
   t-statistic:  -9.106 
   degrees of freedom:  178 
   p-value:  &lt;.001 

Other information: 
   two-sided 95% confidence interval:  [-2.27, -1.462] 
   estimated effect size (Cohen's d):  0.681 </code></pre>
</div>
</div>
</section>
<section id="doing-the-test-in-r-paired-sample" class="slide level2">
<h2>Doing the test in R: Paired Sample</h2>
<p>Maybe we want to keep things separate and don’t want to calculate separate values. We can use <code>pairedSamplesTTest()</code> instead!</p>
<p>But this isn’t working and is making me mad…</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a></a>lsr<span class="sc">::</span><span class="fu">pairedSamplesTTest</span>(</span>
<span id="cb34-2"><a></a>  <span class="at">formula =</span> <span class="sc">~</span> Sleep_Hours_Schoolnight <span class="sc">+</span> Sleep_Hours_Non_Schoolnight,</span>
<span id="cb34-3"><a></a>  <span class="at">data =</span> sleep_state_school</span>
<span id="cb34-4"><a></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="doing-the-test-in-r-classic-edition" class="slide level2">
<h2>Doing the test in R: Classic Edition</h2>
<p>As you Google around to figure things out, you will likely see folks using <code>t.test()</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a></a><span class="fu">t.test</span>(<span class="at">x =</span> sleep_state_school<span class="sc">$</span>Sleep_Hours_Schoolnight,    </span>
<span id="cb35-2"><a></a>       <span class="at">y =</span> sleep_state_school<span class="sc">$</span>Sleep_Hours_Non_Schoolnight,</span>
<span id="cb35-3"><a></a>       <span class="at">paired =</span> <span class="cn">TRUE</span> )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  sleep_state_school$Sleep_Hours_Schoolnight and sleep_state_school$Sleep_Hours_Non_Schoolnight
t = -9.1062, df = 178, p-value &lt; 0.00000000000000022
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -2.270281 -1.461563
sample estimates:
mean difference 
      -1.865922 </code></pre>
</div>
</div>
</section>
<section id="reporting-t-test" class="slide level2">
<h2>Reporting <span class="math inline">\(t\)</span>-test</h2>
<p>The first sentence usually conveys some descriptive information about the sample you were comparing (e.g., pre &amp; post test).</p>
<p>Then you identify the type of test you conducted and what was determined (be sure to include the “stat block” here as well with the t-statistic, df, p-value, CI and Effect size).</p>
<p>Finish it up by putting that into person words and saying what that means.</p>
</section></section>
<section id="your-turn-2" class="title-slide slide level1 center">
<h1>YOUR TURN 💻</h1>

</section>

<section>
<section id="anova-analysis-of-variance" class="title-slide slide level1 center">
<h1>ANOVA (Analysis of Variance)</h1>

</section>
<section id="what-is-anova-lsr-ch.-14" class="slide level2">
<h2>What is ANOVA? (<a href="https://learningstatisticswithr.com/book/anova.html">LSR Ch. 14</a>)</h2>
<ul>
<li class="fragment">ANOVA stands for <u><strong><em>An</em></strong></u>alysis <u><strong><em>o</em></strong></u>f <u><strong><em>Va</em></strong></u>riance</li>
<li class="fragment">Comparing means between two or more groups (usually 3 or more)
<ul>
<li class="fragment">Continuous outcome and grouping variable with 2 or more levels</li>
</ul></li>
<li class="fragment">Under the larger umbrella of general linear models
<ul>
<li class="fragment">ANOVA is basically a regression with only categorical predictors</li>
</ul></li>
<li class="fragment">Likely the most widely used tool in Psychology</li>
</ul>
</section>
<section id="different-types-of-anova" class="slide level2">
<h2>Different Types of ANOVA</h2>
<ul>
<li><div class="fragment highlight-green">
<p>One-Way ANOVA</p>
</div></li>
<li><p>Two-Way ANOVA</p></li>
<li><p>Repeated Measures ANOVA</p></li>
<li><p>ANCOVA</p></li>
<li><p>MANOVA</p></li>
</ul>
</section>
<section id="one-way-anova" class="slide level2">
<h2>One-Way ANOVA</h2>
<p>Goal: Inform of differences among the levels of our variable of interest (Omnibus Test)</p>
<ul>
<li>But cannot tell us more than that…</li>
</ul>
<p>Hypotheses:</p>
<p><span class="math display">\[ H_0: it\: is\: true\: that\: \mu_1 = \mu_2 = \mu_3 =\: ...\mu_k  \\  H_1: it\: is\: \boldsymbol{not}\: true\: that\: \mu_1 = \mu_2 = \mu_3 =\: ...\mu_k \]</span></p>
</section>
<section id="waitmeans-or-variance" class="slide level2">
<h2>Wait…Means or Variance?</h2>
<p>We are using the variance to create a ratio (within group versus between group variance) to determine differences in means</p>
<ul>
<li>We are not directly investigating variance, but operationalize variance to create the ratio:</li>
</ul>
<p><span class="math display">\[ F_{df_b, \: df_w} = \frac{MS_{between}}{MS_{within}} \]</span></p>
</section>
<section class="slide level2">


<img data-src="../images/ANOVA.png" width="729" class="r-stretch"></section>
<section class="slide level2">


<img data-src="../images/ANOVA.png" width="729" class="r-stretch"><div class="columns">
<div class="column" style="width:50%;">
<p><span class="math inline">\(F = \frac{MS_{between}}{MS_{within}} = \frac{small}{large} &lt; 1\)</span></p>
</div><div class="column" style="width:50%;">
<p><span class="math inline">\(F = \frac{MS_{between}}{MS_{within}} = \frac{large}{small} &gt; 1\)</span></p>
</div></div>
</section>
<section id="anova-assumptions" class="slide level2">
<h2>ANOVA: Assumptions</h2>
<div style="font-size: 30px">
<p><strong>Independence</strong></p>
<ul>
<li>Observations between and within groups should be independent. No autocorrelation</li>
</ul>
<p><strong>Homogeneity of Variance</strong></p>
<ul>
<li>The variances within each group should be roughly equal
<ul>
<li>Levene’s test –&gt; Welch’s ANOVA for unequal variances</li>
</ul></li>
</ul>
<p><strong>Normality</strong></p>
<ul>
<li>The data within each group should follow a normal distribution
<ul>
<li>Shapiro-Wilk test –&gt; can transform the data or use non-parametric tests</li>
</ul></li>
</ul>
</div>
</section></section>
<section>
<section id="nhst-with-anova" class="title-slide slide level1 center">
<h1>NHST with ANOVA</h1>

</section>
<section id="review-of-the-nhst-process" class="slide level2 scrollable">
<h2>Review of the NHST process</h2>
<ol type="1">
<li class="fragment"><p>Collect Sample and define hypotheses</p></li>
<li class="fragment"><p>Set alpha level</p></li>
<li class="fragment"><p>Determine the sampling distribution (will be using <span class="math inline">\(F\)</span>-distribution now)</p></li>
<li class="fragment"><p>Identify the critical value</p></li>
<li class="fragment"><p>Calculate test statistic for sample collected</p></li>
<li class="fragment"><p>Inspect &amp; compare statistic to critical value; Calculate probability</p></li>
</ol>
</section>
<section id="steps-to-calculating-f-ratio" class="slide level2 scrollable">
<h2>Steps to calculating F-ratio</h2>
<ol type="1">
<li>Capture variance both between and within groups</li>
<li>Variance to Sum of Squares</li>
<li>Degrees of Freedom</li>
<li>Mean squares values</li>
<li>F-Statistic</li>
</ol>
</section>
<section id="capturing-variance" class="slide level2">
<h2>Capturing Variance</h2>
<p>We have calculated variance before!</p>
<p><span class="math display">\[ Var = \frac{1}{N}\sum(x_i - \bar{x})^2 \]</span></p>
<p>Now we have to take into account the variance between and within the groups:</p>
<p><span class="math display">\[ Var(Y) = \frac{1}{N} \sum^G_{k=1}\sum^{N_k}_{i=i}(Y_{ik} - \bar{Y})^2 \]</span></p>
<div style="font-size: 20px; text-align: center">
<p>Notice that we have the summation across each group ( <span class="math inline">\(G\)</span> ) and the person in the group ( <span class="math inline">\(N_k\)</span> )</p>
</div>
</section>
<section id="variance-to-sum-of-squares" class="slide level2">
<h2>Variance to Sum of Squares</h2>
<p><strong>Total Sum of Squares -</strong> Adding up the sum of squares instead of getting the average (notice the removal of <span class="math inline">\(\frac{1}{N}\)</span>)</p>
<p><span class="math display">\[ SS_{total} = \sum^G_{k=1}\sum^{N_k}_{i=i}(Y_{ik} - \bar{Y})^2 \]</span></p>
<p>Can be broken up to see what is the variation <strong><em>between</em></strong> the groups AND the variation <strong><em>within</em></strong> the groups</p>
<p><span class="math display">\[ SS_{total}=SS_{between}+SS_{within} \]</span></p>
<div style="font-size: 20px; text-align: center">
<p>This gets us closer to understanding the difference between means</p>
</div>
</section></section>
<section>
<section id="sum-of-squares" class="title-slide slide level1 center">
<h1>Sum of Squares</h1>

</section>
<section class="slide level2">

<h3 id="sum-of-squares-1">Sum of Squares</h3>
<p><span class="math display">\[ SS_{total}=SS_{between}+SS_{within} \]</span></p>

<img data-src="../images/var_ss.PNG" class="quarto-figure quarto-figure-center r-stretch"></section>
<section class="slide level2">

<h3 id="example-data">Example Data</h3>

<img data-src="../images/table1.PNG" class="quarto-figure quarto-figure-center r-stretch"></section>
<section class="slide level2">

<h3 id="example-data-1">Example Data</h3>

<img data-src="../images/table2.PNG" class="quarto-figure quarto-figure-center r-stretch"></section>
<section class="slide level2">

<h3 id="example-data-2">Example Data</h3>

<img data-src="../images/table3.PNG" class="quarto-figure quarto-figure-center r-stretch"></section>
<section class="slide level2">

<h3 id="example-data-3">Example Data</h3>

<img data-src="../images/table4.PNG" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="sum-of-squares---between" class="slide level2">
<h2>Sum of Squares - Between</h2>
<p>The difference between the <em>group mean</em> and <em>grand mean</em></p>
<p><span class="math display">\[ SS_{between} = \sum^G_{k=1}N_k(\bar{Y_k} - \bar{Y})^2 \]</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Group</th>
<th style="text-align: center;">Group Mean <span class="math inline">\(\bar{Y_k}\)</span></th>
<th style="text-align: center;">Grand Mean <span class="math inline">\(\bar{Y}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Cool</td>
<td style="text-align: center;">32</td>
<td style="text-align: center;">41.8</td>
</tr>
<tr class="even">
<td style="text-align: center;">Uncool</td>
<td style="text-align: center;">56.5</td>
<td style="text-align: center;">41.8</td>
</tr>
</tbody>
</table>
</section>
<section id="sum-of-squares---between-1" class="slide level2">
<h2>Sum of Squares - Between</h2>
<p>The difference between the <em>group mean</em> and <em>grand mean</em></p>
<p><span class="math display">\[ SS_{between} = \sum^G_{k=1}N_k(\bar{Y_k} - \bar{Y})^2 \]</span></p>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Group</th>
<th style="text-align: center;">Group Mean <span class="math inline">\(\bar{Y_k}\)</span></th>
<th style="text-align: center;">Grand Mean <span class="math inline">\(\bar{Y}\)</span></th>
<th style="text-align: center;">Sq. Dev.</th>
<th style="text-align: center;">N</th>
<th style="text-align: center;">Weighted Sq. Dev.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Cool</td>
<td style="text-align: center;">32</td>
<td style="text-align: center;">41.8</td>
<td style="text-align: center;">96.04</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">288.12</td>
</tr>
<tr class="even">
<td style="text-align: center;">Uncool</td>
<td style="text-align: center;">56.5</td>
<td style="text-align: center;">41.8</td>
<td style="text-align: center;">216.09</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">432.18</td>
</tr>
</tbody>
</table>
</section>
<section id="sum-of-squares---between-2" class="slide level2">
<h2>Sum of Squares - Between</h2>
<p>The difference between the <em>group mean</em> and <em>grand mean</em></p>
<p><span class="math display">\[ SS_{between} = \sum^G_{k=1}N_k(\bar{Y_k} - \bar{Y})^2 \]</span></p>
<p>Now we can sum the Weighted Squared Deviations together to get our Sum of Squares Between:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a></a>ssb <span class="ot">&lt;-</span> <span class="fl">288.12</span> <span class="sc">+</span> <span class="fl">432.18</span> </span>
<span id="cb37-2"><a></a>ssb</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 720.3</code></pre>
</div>
</div>
</section>
<section id="sum-of-squares---within" class="slide level2">
<h2>Sum of Squares - Within</h2>
<p>The difference between the <u><em>individual</em></u> and their <u><em>group mean</em></u></p>
<p><span class="math display">\[ SS_{within} = \sum^G_{k=1}\sum^{N_k}_{i=i}(Y_{ik} - \bar{Y_k})^2 \]</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Name</th>
<th style="text-align: center;">Grumpiness <span class="math inline">\(Y_{ik}\)</span></th>
<th style="text-align: center;">Group Mean <span class="math inline">\(\bar{Y_K}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Frodo</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">32</td>
</tr>
<tr class="even">
<td style="text-align: center;">Sam</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">32</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Bandit</td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">32</td>
</tr>
<tr class="even">
<td style="text-align: center;">Dolores U.</td>
<td style="text-align: center;">91</td>
<td style="text-align: center;">56.5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Dustin</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">56.5</td>
</tr>
</tbody>
</table>
</section>
<section id="sum-of-squares---within-1" class="slide level2">
<h2>Sum of Squares - Within</h2>
<p>The difference between the <u><em>individual</em></u> and their <u><em>group mean</em></u></p>
<p><span class="math display">\[ SS_{within} = \sum^G_{k=1}\sum^{N_k}_{i=i}(Y_{ik} - \bar{Y_k})^2 \]</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Name</th>
<th style="text-align: center;">Grumpiness <span class="math inline">\(Y_{ik}\)</span></th>
<th style="text-align: center;">Group Mean <span class="math inline">\(\bar{Y_K}\)</span></th>
<th>Sq. Dev</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Frodo</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">32</td>
<td>144</td>
</tr>
<tr class="even">
<td style="text-align: center;">Sam</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">32</td>
<td>529</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Bandit</td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">32</td>
<td>121</td>
</tr>
<tr class="even">
<td style="text-align: center;">Dolores U.</td>
<td style="text-align: center;">91</td>
<td style="text-align: center;">56.5</td>
<td>1190.25</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Dustin</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">56.5</td>
<td>1190.25</td>
</tr>
</tbody>
</table>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a></a>score <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">55</span>, <span class="dv">21</span>, <span class="dv">91</span>, <span class="dv">22</span>) </span>
<span id="cb39-2"><a></a>group_m <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">32</span>, <span class="dv">32</span>, <span class="dv">32</span>, <span class="fl">56.5</span>, <span class="fl">56.5</span>) </span>
<span id="cb39-3"><a></a>sq_dev <span class="ot">&lt;-</span> (score <span class="sc">-</span> group_m)<span class="sc">^</span><span class="dv">2</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="sum-of-squares---within-2" class="slide level2">
<h2>Sum of Squares - Within</h2>
<p>The difference between the <u><em>individual</em></u> and their <u><em>group mean</em></u></p>
<p><span class="math display">\[ SS_{within} = \sum^G_{k=1}\sum^{N_k}_{i=i}(Y_{ik} - \bar{Y_k})^2 \]</span> Now we can sum the Squared Deviations together to get our Sum of Squares Within:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a></a><span class="fu">sum</span>(sq_dev)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3174.5</code></pre>
</div>
</div>
</section>
<section id="sum-of-squares-2" class="slide level2">
<h2>Sum of Squares</h2>
<p>Can start to have an idea of what this looks like</p>
<p><span class="math display">\[ SS_{between} = \sum^G_{k=1}N_k(\bar{Y_k} - \bar{Y})^2 = 720.3 \]</span></p>
<p><span class="math display">\[ SS_{within} = \sum^G_{k=1}\sum^{N_k}_{i=i}(Y_{ik} - \bar{Y_k})^2 = 3174.5 \]</span></p>
<p>Next we have to take into account the degrees of freedom</p>
</section></section>
<section>
<section id="degrees-of-freedom---anova" class="title-slide slide level1 center">
<h1>Degrees of Freedom - ANOVA</h1>

</section>
<section id="degrees-of-freedom" class="slide level2 scrollable">
<h2>Degrees of Freedom</h2>
<p>Since we have 2 types of variations that we are examining, this needs to be reflected in the degrees of freedom</p>
<ol type="1">
<li><p>Take the number of groups and subtract 1<br>
<span class="math inline">\(df_{between} = G - 1\)</span></p></li>
<li><p>Take the total number of observations and subtract the number of groups</p>
<p><span class="math inline">\(df_{within} = N - G\)</span></p></li>
</ol>
</section></section>
<section>
<section id="mean-squares" class="title-slide slide level1 center">
<h1>Mean Squares</h1>

</section>
<section id="calculating-mean-squares" class="slide level2">
<h2>Calculating Mean Squares</h2>
<p>Next we convert our summed squares value into a “mean squares”</p>
<p>This is done by dividing by the respective degrees of freedom</p>
<p><span class="math display">\[ MS_b = \frac{SS_b}{df_b} \]</span></p>
<p><span class="math display">\[ MS_W = \frac{SS_w}{df_w} \]</span></p>
</section>
<section id="calculating-mean-squares---example" class="slide level2">
<h2>Calculating Mean Squares - Example</h2>
<p>Let’s take a look at how this applies to our example: <span class="math display">\[ MS_b = \frac{SS_b}{G-1} = \frac{720.3}{2-1} = 720.3 \]</span></p>
<p><span class="math display">\[ MS_W = \frac{SS_w}{N-G} = \frac{3174.5}{5-2} = 1058.167  \]</span></p>
</section></section>
<section>
<section id="f-statistic" class="title-slide slide level1 center">
<h1><span class="math inline">\(F\)</span>-Statistic</h1>

</section>
<section id="calculating-the-f-statistic" class="slide level2">
<h2>Calculating the F-Statistic</h2>
<p><span class="math display">\[F = \frac{MS_b}{MS_w}\]</span></p>
<p>If the null hypothesis is true, <span class="math inline">\(F\)</span> has an expected value close to 1 (numerator and denominator are estimates of the same variability)</p>
<p>If it is false, the numerator will likely be larger, because systematic, between-group differences contribute to the variance of the means, but not to variance within group.</p>
</section>
<section class="slide level2">

<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a></a><span class="fu">data.frame</span>(<span class="at">F =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">8</span>)) <span class="sc">%&gt;%</span>   </span>
<span id="cb42-2"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> F)) <span class="sc">+</span>   </span>
<span id="cb42-3"><a></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> <span class="cf">function</span>(x) <span class="fu">df</span>(x, <span class="at">df1 =</span> <span class="dv">3</span>, <span class="at">df2 =</span> <span class="dv">196</span>),                  <span class="at">geom =</span> <span class="st">"line"</span>) <span class="sc">+</span>   </span>
<span id="cb42-4"><a></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> <span class="cf">function</span>(x) <span class="fu">df</span>(x, <span class="at">df1 =</span> <span class="dv">3</span>, <span class="at">df2 =</span> <span class="dv">196</span>),                  <span class="at">geom =</span> <span class="st">"area"</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="fl">2.65</span>, <span class="dv">8</span>), <span class="at">fill =</span> <span class="st">"purple"</span>) <span class="sc">+</span>   <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="fl">2.65</span>), <span class="at">color =</span> <span class="st">"purple"</span>) <span class="sc">+</span>   <span class="fu">scale_y_continuous</span>(<span class="st">"Density"</span>) <span class="sc">+</span> <span class="fu">scale_x_continuous</span>(<span class="st">"F statistic"</span>, <span class="at">breaks =</span> <span class="cn">NULL</span>) <span class="sc">+</span>   <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="lec-6_mean_files/figure-revealjs/unnamed-chunk-23-1.png" width="960" class="r-stretch"><p>If data are normally distributed, then the variance is <span class="math inline">\(\chi^2\)</span> distributed</p>
<p><span class="math inline">\(F\)</span>-distributions are one-tailed tests. Recall that we’re interested in how far away our test statistic from the null <span class="math inline">\((F = 1).\)</span></p>
</section>
<section id="calculating-f-statistic-example" class="slide level2">
<h2>Calculating F-statistic: Example</h2>
<p><span class="math display">\[F = \frac{MS_b}{MS_w} = \frac{720.3}{1058.167} = 0.68\]</span></p>
<p><a href="http://courses.atlas.illinois.edu/spring2016/STAT/STAT200/pf.html">Link</a> to probability calculator</p>
</section>
<section class="slide level2">

<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a></a><span class="fu">data.frame</span>(<span class="at">F =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">8</span>)) <span class="sc">%&gt;%</span>   </span>
<span id="cb43-2"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> F)) <span class="sc">+</span>   </span>
<span id="cb43-3"><a></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> <span class="cf">function</span>(x) <span class="fu">df</span>(x, <span class="at">df1 =</span> <span class="dv">3</span>, <span class="at">df2 =</span> <span class="dv">196</span>),                  <span class="at">geom =</span> <span class="st">"line"</span>) <span class="sc">+</span>   </span>
<span id="cb43-4"><a></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> <span class="cf">function</span>(x) <span class="fu">df</span>(x, <span class="at">df1 =</span> <span class="dv">3</span>, <span class="at">df2 =</span> <span class="dv">196</span>),                  <span class="at">geom =</span> <span class="st">"area"</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="fl">2.65</span>, <span class="dv">8</span>), <span class="at">fill =</span> <span class="st">"purple"</span>) <span class="sc">+</span>   <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="fl">2.65</span>), <span class="at">color =</span> <span class="st">"purple"</span>) <span class="sc">+</span></span>
<span id="cb43-5"><a></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="fl">0.68</span>), <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span>    </span>
<span id="cb43-6"><a></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>,            </span>
<span id="cb43-7"><a></a>           <span class="at">label =</span> <span class="st">"F=0.68"</span>,             </span>
<span id="cb43-8"><a></a>           <span class="at">x =</span> <span class="fl">1.1</span>, <span class="at">y =</span> <span class="fl">0.65</span>, <span class="at">size =</span> <span class="dv">8</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb43-9"><a></a>  <span class="fu">scale_y_continuous</span>(<span class="st">"Density"</span>) <span class="sc">+</span> </span>
<span id="cb43-10"><a></a>  <span class="fu">scale_x_continuous</span>(<span class="st">"F statistic"</span>, <span class="at">breaks =</span> <span class="cn">NULL</span>) <span class="sc">+</span>   </span>
<span id="cb43-11"><a></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="lec-6_mean_files/figure-revealjs/unnamed-chunk-24-1.png" width="960" class="r-stretch"><p>What can we conclude?</p>
</section>
<section id="contrastspost-hoc-tests" class="slide level2 scrollable">
<h2>Contrasts/Post-Hoc Tests</h2>
<p>Performed when there is a significant difference among the groups to examine which groups are different</p>
<ol type="1">
<li><strong>Contrasts</strong>: When we have <em>a priori</em> hypotheses</li>
<li><strong>Post-hoc Tests</strong>: When we want to test everything</li>
</ol>
</section></section>
<section>
<section id="reporting-results" class="title-slide slide level1 center">
<h1>Reporting Results</h1>

</section>
<section id="tables" class="slide level2">
<h2>Tables</h2>
<p>Often times the output will be in the form of a table and then it is often reported this way in the manuscript</p>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Source of Variation</th>
<th style="text-align: center;">df</th>
<th style="text-align: center;">Sum of Squares</th>
<th style="text-align: center;">Mean Squares</th>
<th style="text-align: center;">F-statistic</th>
<th style="text-align: center;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Group</td>
<td style="text-align: center;"><span class="math inline">\(G-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_b\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MS_b = \frac{SS_b}{df_b}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(F = \frac{MS_b}{MS_w}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(p\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">Residual</td>
<td style="text-align: center;"><span class="math inline">\(N-G\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_w\)</span></td>
<td style="text-align: center;"><span class="math inline">\(MS_w = \frac{SS_w}{df_w}\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Total</td>
<td style="text-align: center;"><span class="math inline">\(N-1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(SS_{total}\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</section>
<section id="in-text" class="slide level2">
<h2>In-Text</h2>
<blockquote>
<p>A one-way analysis of variance was used to test for differences in the [variable of interest/outcome variable] as a function of [whatever the factor is]. Specifically, differences in [variable of interest] were assessed for the [list different levels and be sure to include (M= , SD= )] . The one-way ANOVA revealed a significant/nonsignificant effect of [factor] on scores on the [variable of interest] (F(dfb, dfw) = f-ratio, p = p-value, η2 = effect size).</p>
<p>Planned comparisons were conducted to compare expected differences among the [however many groups] means. Planned contrasts revealed that participants in the [one of the conditions] had a greater/fewer [variable of interest] and then include the p-value. This same type of sentence is repeated for whichever contrasts you completed. Descriptive statistics were reported in Table 1.</p>
</blockquote>
</section></section>
<section>
<section id="one-way-anova-in-r" class="title-slide slide level1 center">
<h1>One-Way ANOVA in R</h1>
<p><code>Continuous_Variable ~ Group_Variable</code></p>
</section>
<section id="books-by-marital-status" class="slide level2">
<h2>Books by Marital Status</h2>
<p>We can examine how many books (continuous) by marital status (7 categories: Married, Divorced, In a relationship, Other, Separated, Widowed, Single)</p>
<p>VISUALIZE!</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a></a><span class="fu">ggbetweenstats</span>(</span>
<span id="cb44-2"><a></a>  <span class="at">data  =</span> cah,</span>
<span id="cb44-3"><a></a>  <span class="at">x     =</span> marital_status,</span>
<span id="cb44-4"><a></a>  <span class="at">y     =</span> books,</span>
<span id="cb44-5"><a></a>  <span class="at">title =</span> <span class="st">"Distribution of books across marital status"</span></span>
<span id="cb44-6"><a></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="lec-6_mean_files/figure-revealjs/unnamed-chunk-25-1.png" width="960" class="r-stretch"></section>
<section class="slide level2">

<h3 id="running-the-anova">Running the ANOVA</h3>
<p>Use the same way we build a model and then get the summary of that model</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a></a>aov_mar <span class="ot">&lt;-</span> <span class="fu">aov</span>(books <span class="sc">~</span> marital_status, </span>
<span id="cb45-2"><a></a>               <span class="at">data =</span> cah)</span>
<span id="cb45-3"><a></a></span>
<span id="cb45-4"><a></a><span class="fu">summary</span>(aov_mar)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Df  Sum Sq Mean Sq F value  Pr(&gt;F)   
marital_status   6  124027   20671   3.624 0.00146 **
Residuals      963 5492561    5704                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
30 observations deleted due to missingness</code></pre>
</div>
</div>
</section>
<section class="slide level2 scrollable">

<h3 id="post-hoc-tests">Post-hoc Tests</h3>
<ol type="1">
<li>Examine the basic summary statistics</li>
<li>Do pairwise comparisons between each of the groups, based on the model we created</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a></a><span class="co">#get basic summary stats</span></span>
<span id="cb47-2"><a></a>cah <span class="sc">%&gt;%</span> </span>
<span id="cb47-3"><a></a>  <span class="fu">group_by</span>(marital_status) <span class="sc">%&gt;%</span> </span>
<span id="cb47-4"><a></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(books, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb47-5"><a></a>            <span class="at">sd =</span> <span class="fu">sd</span>(books, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 3
  marital_status     mean    sd
  &lt;chr&gt;             &lt;dbl&gt; &lt;dbl&gt;
1 Divorced          56.9  165. 
2 In a relationship 13.6   25.8
3 Married           18.3   59.5
4 Other             50     NA  
5 Separated          7.75  14.3
6 Single            20.4   76.1
7 Widowed           30.7   59.0
8 &lt;NA&gt;              14     12.3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a></a><span class="co"># conduct the comparisons</span></span>
<span id="cb49-2"><a></a><span class="fu">emmeans</span>(aov_mar, pairwise <span class="sc">~</span> marital_status, </span>
<span id="cb49-3"><a></a>        <span class="at">adjust =</span> <span class="st">"none"</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$emmeans
 marital_status    emmean    SE  df lower.CL upper.CL
 Divorced           56.87  8.29 963    40.61     73.1
 In a relationship  13.61  8.05 963    -2.19     29.4
 Married            18.28  3.36 963    11.68     24.9
 Other              50.00 75.50 963   -98.21    198.2
 Separated           7.75 18.90 963   -29.30     44.8
 Single             20.37  5.27 963    10.01     30.7
 Widowed            30.67  8.84 963    13.32     48.0

Confidence level used: 0.95 

$contrasts
 contrast                      estimate    SE  df t.ratio p.value
 Divorced - In a relationship     43.26 11.60 963   3.744  0.0002
 Divorced - Married               38.59  8.95 963   4.314  &lt;.0001
 Divorced - Other                  6.87 76.00 963   0.090  0.9279
 Divorced - Separated             49.12 20.60 963   2.382  0.0174
 Divorced - Single                36.51  9.83 963   3.716  0.0002
 Divorced - Widowed               26.20 12.10 963   2.162  0.0308
 In a relationship - Married      -4.67  8.73 963  -0.535  0.5929
 In a relationship - Other       -36.39 76.00 963  -0.479  0.6320
 In a relationship - Separated     5.86 20.50 963   0.286  0.7752
 In a relationship - Single       -6.75  9.62 963  -0.702  0.4831
 In a relationship - Widowed     -17.06 12.00 963  -1.427  0.1540
 Married - Other                 -31.72 75.60 963  -0.420  0.6749
 Married - Separated              10.53 19.20 963   0.549  0.5831
 Married - Single                 -2.09  6.26 963  -0.333  0.7389
 Married - Widowed               -12.39  9.46 963  -1.310  0.1904
 Other - Separated                42.25 77.80 963   0.543  0.5874
 Other - Single                   29.63 75.70 963   0.391  0.6956
 Other - Widowed                  19.33 76.00 963   0.254  0.7994
 Separated - Single              -12.62 19.60 963  -0.644  0.5200
 Separated - Widowed             -22.92 20.80 963  -1.099  0.2718
 Single - Widowed                -10.31 10.30 963  -1.001  0.3170</code></pre>
</div>
</div>
</section>
<section id="family-wise-error" class="slide level2">
<h2>Family-wise error</h2>
<p>These pairwise comparisons can quickly grow in number as the number of Groups increases. With 3 (k) Groups, we have k(k-1)/2 = 3 possible pairwise comparisons.</p>
<p>As the number of groups in the ANOVA grows, the number of possible pairwise comparisons increases dramatically.</p>

<img data-src="lec-6_mean_files/figure-revealjs/unnamed-chunk-28-1.png" width="960" class="r-stretch"></section>
<section class="slide level2">

<p>As the number of tests grows, and assuming the null hypothesis is true, the probability that we will make one or more Type I errors increases. To approximate the magnitude of the problem, we can assume that the multiple pairwise comparisons are independent. The probability that we <strong>don’t</strong> make a Type I error for <u><strong>one</strong></u> test is:</p>
<p><span class="math display">\[P(\text{No Type I}, 1 \text{ test}) = 1-\alpha\]</span></p>
</section>
<section class="slide level2">

<p>The probability that we don’t make a Type I error for <u><strong>two</strong></u> tests is:</p>
<p><span class="math display">\[P(\text{No Type I}, 2 \text{ test}) = (1-\alpha)(1-\alpha)\]</span></p>
<p>For C tests, the probability that we make <strong>no</strong> Type I errors is</p>
<p><span class="math display">\[P(\text{No Type I}, C \text{ tests}) = (1-\alpha)^C\]</span></p>
<p>We can then use the following to calculate the probability that we make one or more Type I errors in a collection of C independent tests.</p>
<p><span class="math display">\[P(\text{At least one Type I}, C \text{ tests}) = 1-(1-\alpha)^C\]</span></p>
</section>
<section class="slide level2">

<p>The Type I error inflation that accompanies multiple comparisons motivates the large number of “correction” procedures that have been developed.</p>

<img data-src="lec-6_mean_files/figure-revealjs/unnamed-chunk-29-1.png" width="960" class="r-stretch"></section>
<section class="slide level2">

<p>Multiple comparisons, each tested with <span class="math inline">\(\alpha_{per-test}\)</span>, increases the family-wise <span class="math inline">\(\alpha\)</span> level.</p>
<p><span class="math display">\[\large \alpha_{family-wise} = 1 - (1-\alpha_{per-test})^C\]</span> Šidák showed that the family-wise a could be controlled to a desired level (e.g., .05) by changing the <span class="math inline">\(\alpha_{per-test}\)</span> to:</p>
<p><span class="math display">\[\large \alpha_{per-wise} = 1 - (1-\alpha_{family-wise})^{\frac{1}{C}}\]</span></p>
</section>
<section class="slide level2">

<h3 id="bonferroni">Bonferroni</h3>
<p>Bonferroni (and Dunn, and others) suggested this simple approximation:</p>
<p><span class="math display">\[\large \alpha_{per-test} = \frac{\alpha_{family-wise}}{C}\]</span></p>
<p>This is typically called the Bonferroni correction and is very often used even though better alternatives are available.</p>
</section>
<section class="slide level2">

<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a></a><span class="fu">emmeans</span>(aov_mar, pairwise <span class="sc">~</span> marital_status,          <span class="at">adjust =</span> <span class="st">"bonferroni"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$emmeans
 marital_status    emmean    SE  df lower.CL upper.CL
 Divorced           56.87  8.29 963    40.61     73.1
 In a relationship  13.61  8.05 963    -2.19     29.4
 Married            18.28  3.36 963    11.68     24.9
 Other              50.00 75.50 963   -98.21    198.2
 Separated           7.75 18.90 963   -29.30     44.8
 Single             20.37  5.27 963    10.01     30.7
 Widowed            30.67  8.84 963    13.32     48.0

Confidence level used: 0.95 

$contrasts
 contrast                      estimate    SE  df t.ratio p.value
 Divorced - In a relationship     43.26 11.60 963   3.744  0.0040
 Divorced - Married               38.59  8.95 963   4.314  0.0004
 Divorced - Other                  6.87 76.00 963   0.090  1.0000
 Divorced - Separated             49.12 20.60 963   2.382  0.3654
 Divorced - Single                36.51  9.83 963   3.716  0.0045
 Divorced - Widowed               26.20 12.10 963   2.162  0.6478
 In a relationship - Married      -4.67  8.73 963  -0.535  1.0000
 In a relationship - Other       -36.39 76.00 963  -0.479  1.0000
 In a relationship - Separated     5.86 20.50 963   0.286  1.0000
 In a relationship - Single       -6.75  9.62 963  -0.702  1.0000
 In a relationship - Widowed     -17.06 12.00 963  -1.427  1.0000
 Married - Other                 -31.72 75.60 963  -0.420  1.0000
 Married - Separated              10.53 19.20 963   0.549  1.0000
 Married - Single                 -2.09  6.26 963  -0.333  1.0000
 Married - Widowed               -12.39  9.46 963  -1.310  1.0000
 Other - Separated                42.25 77.80 963   0.543  1.0000
 Other - Single                   29.63 75.70 963   0.391  1.0000
 Other - Widowed                  19.33 76.00 963   0.254  1.0000
 Separated - Single              -12.62 19.60 963  -0.644  1.0000
 Separated - Widowed             -22.92 20.80 963  -1.099  1.0000
 Single - Widowed                -10.31 10.30 963  -1.001  1.0000

P value adjustment: bonferroni method for 21 tests </code></pre>
</div>
</div>
</section>
<section class="slide level2">

<p>The Bonferroni procedure is conservative. Other correction procedures have been developed that control family-wise Type I error at .05 but that are more powerful than the Bonferroni procedure. The most common one is the Holm procedure.</p>
<p>The Holm procedure does not make a constant adjustment to each per-test <span class="math inline">\(\alpha\)</span>. Instead it makes adjustments in stages depending on the relative size of each pairwise p-value.</p>
</section>
<section class="slide level2 scrollable">

<h3 id="holm-correction">Holm correction</h3>
<ol type="1">
<li>Rank order the p-values from largest to smallest.</li>
<li>Start with the smallest p-value. Multiply it by its rank.</li>
<li>Go to the next smallest p-value. Multiply it by its rank. If the result is larger than the adjusted p-value of next smallest rank, keep it. Otherwise replace with the previous step adjusted p-value.</li>
<li>Repeat Step 3 for the remaining p-values.</li>
<li>Judge significance of each new p-value against <span class="math inline">\(\alpha = .05\)</span>.</li>
</ol>
</section>
<section class="slide level2">

<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">Original p value</th>
<th style="text-align: right;">Rank</th>
<th style="text-align: right;">Rank x p</th>
<th style="text-align: right;">Holm</th>
<th style="text-align: right;">Bonferroni</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.0012</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.0072</td>
<td style="text-align: right;">0.0072</td>
<td style="text-align: right;">0.0072</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.0023</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.0115</td>
<td style="text-align: right;">0.0115</td>
<td style="text-align: right;">0.0138</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.0450</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.1800</td>
<td style="text-align: right;">0.1800</td>
<td style="text-align: right;">0.2700</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.0470</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.1410</td>
<td style="text-align: right;">0.1800</td>
<td style="text-align: right;">0.2820</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.0530</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.1060</td>
<td style="text-align: right;">0.1800</td>
<td style="text-align: right;">0.3180</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.2100</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.2100</td>
<td style="text-align: right;">0.2100</td>
<td style="text-align: right;">1.0000</td>
</tr>
</tbody>
</table>
</section>
<section class="slide level2">

<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a></a><span class="fu">emmeans</span>(aov_mar, pairwise <span class="sc">~</span> marital_status,          <span class="at">adjust =</span> <span class="st">"holm"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$emmeans
 marital_status    emmean    SE  df lower.CL upper.CL
 Divorced           56.87  8.29 963    40.61     73.1
 In a relationship  13.61  8.05 963    -2.19     29.4
 Married            18.28  3.36 963    11.68     24.9
 Other              50.00 75.50 963   -98.21    198.2
 Separated           7.75 18.90 963   -29.30     44.8
 Single             20.37  5.27 963    10.01     30.7
 Widowed            30.67  8.84 963    13.32     48.0

Confidence level used: 0.95 

$contrasts
 contrast                      estimate    SE  df t.ratio p.value
 Divorced - In a relationship     43.26 11.60 963   3.744  0.0038
 Divorced - Married               38.59  8.95 963   4.314  0.0004
 Divorced - Other                  6.87 76.00 963   0.090  1.0000
 Divorced - Separated             49.12 20.60 963   2.382  0.3132
 Divorced - Single                36.51  9.83 963   3.716  0.0041
 Divorced - Widowed               26.20 12.10 963   2.162  0.5244
 In a relationship - Married      -4.67  8.73 963  -0.535  1.0000
 In a relationship - Other       -36.39 76.00 963  -0.479  1.0000
 In a relationship - Separated     5.86 20.50 963   0.286  1.0000
 In a relationship - Single       -6.75  9.62 963  -0.702  1.0000
 In a relationship - Widowed     -17.06 12.00 963  -1.427  1.0000
 Married - Other                 -31.72 75.60 963  -0.420  1.0000
 Married - Separated              10.53 19.20 963   0.549  1.0000
 Married - Single                 -2.09  6.26 963  -0.333  1.0000
 Married - Widowed               -12.39  9.46 963  -1.310  1.0000
 Other - Separated                42.25 77.80 963   0.543  1.0000
 Other - Single                   29.63 75.70 963   0.391  1.0000
 Other - Widowed                  19.33 76.00 963   0.254  1.0000
 Separated - Single              -12.62 19.60 963  -0.644  1.0000
 Separated - Widowed             -22.92 20.80 963  -1.099  1.0000
 Single - Widowed                -10.31 10.30 963  -1.001  1.0000

P value adjustment: holm method for 21 tests </code></pre>
</div>
</div>
</section>
<section class="slide level2">

<h3 id="tukey-hsd">Tukey HSD</h3>
<p>Used to compare <strong>all groups</strong> to each other (so all possible comparisons of 2 groups)</p>
<p>Typically the most common</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a></a><span class="fu">emmeans</span>(aov_mar, pairwise <span class="sc">~</span> marital_status,          <span class="at">adjust =</span> <span class="st">"tukey"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$emmeans
 marital_status    emmean    SE  df lower.CL upper.CL
 Divorced           56.87  8.29 963    40.61     73.1
 In a relationship  13.61  8.05 963    -2.19     29.4
 Married            18.28  3.36 963    11.68     24.9
 Other              50.00 75.50 963   -98.21    198.2
 Separated           7.75 18.90 963   -29.30     44.8
 Single             20.37  5.27 963    10.01     30.7
 Widowed            30.67  8.84 963    13.32     48.0

Confidence level used: 0.95 

$contrasts
 contrast                      estimate    SE  df t.ratio p.value
 Divorced - In a relationship     43.26 11.60 963   3.744  0.0036
 Divorced - Married               38.59  8.95 963   4.314  0.0004
 Divorced - Other                  6.87 76.00 963   0.090  1.0000
 Divorced - Separated             49.12 20.60 963   2.382  0.2071
 Divorced - Single                36.51  9.83 963   3.716  0.0040
 Divorced - Widowed               26.20 12.10 963   2.162  0.3173
 In a relationship - Married      -4.67  8.73 963  -0.535  0.9983
 In a relationship - Other       -36.39 76.00 963  -0.479  0.9991
 In a relationship - Separated     5.86 20.50 963   0.286  1.0000
 In a relationship - Single       -6.75  9.62 963  -0.702  0.9925
 In a relationship - Widowed     -17.06 12.00 963  -1.427  0.7874
 Married - Other                 -31.72 75.60 963  -0.420  0.9996
 Married - Separated              10.53 19.20 963   0.549  0.9981
 Married - Single                 -2.09  6.26 963  -0.333  0.9999
 Married - Widowed               -12.39  9.46 963  -1.310  0.8473
 Other - Separated                42.25 77.80 963   0.543  0.9982
 Other - Single                   29.63 75.70 963   0.391  0.9997
 Other - Widowed                  19.33 76.00 963   0.254  1.0000
 Separated - Single              -12.62 19.60 963  -0.644  0.9953
 Separated - Widowed             -22.92 20.80 963  -1.099  0.9283
 Single - Widowed                -10.31 10.30 963  -1.001  0.9538

P value adjustment: tukey method for comparing a family of 7 estimates </code></pre>
</div>
</div>
</section>
<section class="slide level2">

<h3 id="tukey-hsd-another-way">Tukey HSD another way</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a></a><span class="fu">TukeyHSD</span>(aov_mar)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = books ~ marital_status, data = cah)

$marital_status
                                  diff        lwr        upr     p adj
In a relationship-Divorced  -43.259858  -77.40177  -9.117947 0.0036187
Married-Divorced            -38.593732  -65.02603 -12.161436 0.0003541
Other-Divorced               -6.873494 -231.34992 217.602937 1.0000000
Separated-Divorced          -49.123494 -110.04754  11.800548 0.2071415
Single-Divorced             -36.507640  -65.53787  -7.477414 0.0040209
Widowed-Divorced            -26.202261  -62.00630   9.601774 0.3172699
Married-In a relationship     4.666126  -21.11337  30.445620 0.9983277
Other-In a relationship      36.386364 -188.01414 260.786863 0.9991040
Separated-In a relationship  -5.863636  -66.50731  54.780036 0.9999557
Single-In a relationship      6.752217  -21.68491  35.189343 0.9925145
Widowed-In a relationship    17.057597  -18.26725  52.382446 0.7873530
Other-Married                31.720238 -191.63728 255.077755 0.9995816
Separated-Married           -10.529762  -67.19237  46.132847 0.9980605
Single-Married                2.086092  -16.39813  20.570309 0.9998901
Widowed-Married              12.391471  -15.55206  40.335007 0.8472908
Separated-Other             -42.250000 -272.25359 187.753593 0.9981827
Single-Other                -29.634146 -253.31398 194.045687 0.9997201
Widowed-Other               -19.328767 -243.98816 205.330626 0.9999778
Single-Separated             12.615854  -45.30425  70.535962 0.9953161
Widowed-Separated            22.921233  -38.67352  84.515988 0.9283177
Widowed-Single               10.305379  -20.10727  40.718024 0.9537681</code></pre>
</div>
</div>
</section></section>
<section>
<section id="anova-is-regression" class="title-slide slide level1 center">
<h1>ANOVA is regression</h1>
<p>In regression, we can accommodate categorical predictors. How does this compare to ANOVA?</p>
<ul>
<li>Same omnibus test of the model!</li>
</ul>
<p>*(Really the same model, but packaged differently.)</p>
<ul>
<li>When would you use one versus the other?</li>
</ul>
</section>
<section class="slide level2">

<div class="columns">
<div class="column" style="width:50%;">
<p><strong>ANOVA</strong></p>
<ul>
<li><p>More traditional for 3+ groups</p></li>
<li><p>Comparing/controlling multiple categorical variables</p></li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Regression</strong></p>
<ul>
<li><p>Best for two groups</p></li>
<li><p>Incorporating continuous predictors too</p></li>
<li><p>Good for 3+ groups when you have more specific hypotheses (contrasts)</p></li>
</ul>
</div></div>
</section></section>
<section>
<section id="two-way-anova" class="title-slide slide level1 center">
<h1>Two-Way ANOVA</h1>

</section>
<section id="what-is-a-two-way-anova" class="slide level2">
<h2>What is a Two-Way ANOVA?</h2>
<p>Examines the impact of <strong><em>2</em></strong> nominal/categorical variables on a continuous outcome</p>
<p>We can now examine:</p>
<ul>
<li><p>The impact of variable 1 on the outcome (Main Effect)</p></li>
<li><p>The impact of variable 2 on the outcome (Main Effect)</p></li>
<li><p>The <em>interaction</em>&nbsp;of variable 1 &amp; 2 on the outcome (Interaction Effect)</p>
<ul>
<li class="fragment">The effect of variable 1 <strong><em>depends</em></strong> on the level of variable 2</li>
</ul></li>
</ul>
</section>
<section class="slide level2">

</section>
<section id="main-effect-interactions" class="slide level2">
<h2>Main Effect &amp; Interactions</h2>
<p>Main Effect: Basically a one-way ANOVA</p>
<ul>
<li>The effect of variable 1 is the same across all levels of variable 2</li>
</ul>
<p>Interaction:</p>
<ul>
<li><p>Able to examine the effect of variable 1 across different levels of variable 2</p></li>
<li><p>Basically speaking, <strong>the effect of variable 1 on our outcome <em>DEPENDS on the levels of variable 2</em></strong></p></li>
</ul>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="images/640_hex.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="https://dharaden.github.io/psyc640/">course-website</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: false,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/dharaden\.github\.io\/psyc640");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>