<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.26">

  <title>PSYC 640 - Graduate Statistics – Week 13: Intro to Moderation</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-5ae9c59b2727fcd5357d4f034d95f9e0.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
<meta property="og:title" content="Week 13: Intro to Moderation – PSYC 640 - Graduate Statistics">
<meta property="og:description" content="Date: November 17, 2025">
<meta property="og:site_name" content="PSYC 640 - Graduate Statistics">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Week 13: Intro to Moderation</h1>
  <p class="subtitle">Date: November 17, 2025</p>

<div class="quarto-title-authors">
</div>

</section>
<section id="today" class="slide level2">
<h2>Today…</h2>
<ul>
<li><p>Checking back in on Regression</p></li>
<li><p>Making things complicated with moderation</p></li>
<li><p>Final Project Check in</p></li>
</ul>
</section>
<section class="slide level2">

<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a></a><span class="fu">library</span>(rio)</span>
<span id="cb1-3"><a></a><span class="fu">library</span>(here)</span>
<span id="cb1-4"><a></a><span class="fu">library</span>(lm.beta)</span>
<span id="cb1-5"><a></a><span class="fu">library</span>(easystats) <span class="co">#https://easystats.github.io/modelbased/articles/introduction_comparisons_3.html?q=simple%20slo#contrasts-and-comparisons-for-slopes-of-numeric-predictors</span></span>
<span id="cb1-6"><a></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb1-7"><a></a></span>
<span id="cb1-8"><a></a></span>
<span id="cb1-9"><a></a><span class="co">#Remove Scientific Notation </span></span>
<span id="cb1-10"><a></a><span class="fu">options</span>(<span class="at">scipen=</span><span class="dv">999</span>)</span>
<span id="cb1-11"><a></a></span>
<span id="cb1-12"><a></a><span class="co">#Import Example Data</span></span>
<span id="cb1-13"><a></a>t_data <span class="ot">&lt;-</span> <span class="fu">import</span>(<span class="fu">here</span>(<span class="st">"files"</span>, <span class="st">"data"</span>, <span class="st">"tutor.csv"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="motivating-example" class="slide level2">
<h2>Motivating example</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a><span class="fu">glimpse</span>(t_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 20
Columns: 4
$ ID    &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 1…
$ study &lt;dbl&gt; 1.62, 0.54, 0.86, 0.80, 0.36, 2.14, 1.13, 1.66, 1.23, 1.92, 1.82…
$ grade &lt;dbl&gt; 9.0, 7.8, 8.5, 6.2, 6.9, 9.0, 6.6, 8.7, 6.6, 8.8, 9.7, 5.9, 9.5,…
$ tutor &lt;int&gt; 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a>t_data <span class="ot">=</span> t_data <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a></a>  <span class="fu">mutate</span>(<span class="at">tutor_lab =</span> <span class="fu">factor</span>(tutor, </span>
<span id="cb4-3"><a></a>                            <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),</span>
<span id="cb4-4"><a></a>                            <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No tutor"</span>, <span class="st">"Tutor"</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section class="slide level2">

<div class="cell" data-output.lines="[9,10,11,12]">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(grade <span class="sc">~</span> tutor, <span class="at">data =</span> t_data)</span>
<span id="cb5-2"><a></a><span class="fu">summary</span>(mod1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>...
Coefficients:
            Estimate Std. Error t value            Pr(&gt;|t|)    
(Intercept)   6.7600     0.2804  24.108 0.00000000000000375 ***
tutor         2.1300     0.3966   5.371 0.00004186706304119 ***
...</code></pre>
</div>
</div>
<p>Consider the regression model below. How do we interpret the coefficient, <span class="math inline">\(b_1\)</span> ?</p>
<p><span class="math display">\[\hat{\text{grade}} = b_{0} + b_{1}\text{Tutor}\]</span></p>
<div class="fragment">
<p><span class="math inline">\(b_0\)</span> is the mean of the reference group (no tutor), and <span class="math inline">\(b_1\)</span> represents the difference in means between the two groups.</p>
</div>
</section>
<section class="slide level2">

<h3 id="visualizing">Visualizing</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a>means <span class="ot">&lt;-</span> t_data <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a></a>  <span class="fu">group_by</span>(tutor_lab) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a></a>  <span class="fu">summarize</span>(<span class="at">M =</span> <span class="fu">mean</span>(grade))</span>
<span id="cb7-4"><a></a>no_tutor <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(means[<span class="dv">1</span>,<span class="dv">2</span>])</span>
<span id="cb7-5"><a></a>tutor <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(means[<span class="dv">2</span>,<span class="dv">2</span>])</span>
<span id="cb7-6"><a></a></span>
<span id="cb7-7"><a></a></span>
<span id="cb7-8"><a></a>t_data <span class="sc">%&gt;%</span> </span>
<span id="cb7-9"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(tutor, grade, <span class="at">color =</span> tutor_lab)) <span class="sc">+</span></span>
<span id="cb7-10"><a></a>    <span class="fu">geom_jitter</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">width =</span> .<span class="dv">05</span>) <span class="sc">+</span></span>
<span id="cb7-11"><a></a>    <span class="fu">geom_hline</span>(<span class="fu">aes</span>(<span class="at">yintercept =</span> M, <span class="at">color =</span> tutor_lab), </span>
<span id="cb7-12"><a></a>              <span class="at">data =</span> means, <span class="at">linewidth =</span> <span class="fl">1.5</span>) <span class="sc">+</span> </span>
<span id="cb7-13"><a></a>    <span class="fu">annotate</span>(<span class="st">"segment"</span>, <span class="at">x =</span> <span class="fl">0.5</span>, <span class="at">xend =</span> <span class="fl">0.5</span>, </span>
<span id="cb7-14"><a></a>             <span class="at">y =</span> no_tutor, <span class="at">yend =</span> tutor,</span>
<span id="cb7-15"><a></a>             <span class="at">colour =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb7-16"><a></a>    <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> .<span class="dv">75</span>, <span class="at">y =</span> <span class="dv">8</span>, <span class="at">label =</span> <span class="st">"Mean Difference"</span>, </span>
<span id="cb7-17"><a></a>             <span class="at">size =</span> <span class="fl">2.5</span>) <span class="sc">+</span></span>
<span id="cb7-18"><a></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No tutor"</span>, <span class="st">"tutor"</span>)) <span class="sc">+</span></span>
<span id="cb7-19"><a></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span><span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb7-20"><a></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Group"</span>, <span class="at">y =</span> <span class="st">"Grade (out of 10)"</span>, <span class="at">color =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb7-21"><a></a>  cowplot<span class="sc">::</span><span class="fu">theme_cowplot</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="lec-13_mod_files/figure-revealjs/unnamed-chunk-5-1.png" width="768" class="r-stretch"></section>
<section class="slide level2">

<h3 id="visualizing-1">Visualizing</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a>means <span class="ot">&lt;-</span> t_data <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a></a>  <span class="fu">group_by</span>(tutor_lab) <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a></a>  <span class="fu">summarize</span>(<span class="at">M =</span> <span class="fu">mean</span>(grade))</span>
<span id="cb8-4"><a></a>no_tutor <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(means[<span class="dv">1</span>,<span class="dv">2</span>])</span>
<span id="cb8-5"><a></a>tutor <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(means[<span class="dv">2</span>,<span class="dv">2</span>])</span>
<span id="cb8-6"><a></a></span>
<span id="cb8-7"><a></a></span>
<span id="cb8-8"><a></a>t_data <span class="sc">%&gt;%</span> </span>
<span id="cb8-9"><a></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(study, grade, <span class="at">color =</span> tutor_lab)) <span class="sc">+</span></span>
<span id="cb8-10"><a></a>    <span class="fu">geom_jitter</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">width =</span> .<span class="dv">05</span>) <span class="sc">+</span></span>
<span id="cb8-11"><a></a>    <span class="fu">geom_hline</span>(<span class="fu">aes</span>(<span class="at">yintercept =</span> M, <span class="at">color =</span> tutor_lab), </span>
<span id="cb8-12"><a></a>              <span class="at">data =</span> means, <span class="at">linewidth =</span> <span class="fl">1.5</span>) <span class="sc">+</span> </span>
<span id="cb8-13"><a></a>    <span class="fu">annotate</span>(<span class="st">"segment"</span>, <span class="at">x =</span> <span class="fl">0.5</span>, <span class="at">xend =</span> <span class="fl">0.5</span>, </span>
<span id="cb8-14"><a></a>             <span class="at">y =</span> no_tutor, <span class="at">yend =</span> tutor,</span>
<span id="cb8-15"><a></a>             <span class="at">colour =</span> <span class="st">"royalblue"</span>) <span class="sc">+</span></span>
<span id="cb8-16"><a></a>    <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">1</span>, <span class="at">y =</span> <span class="dv">8</span>, <span class="at">label =</span> <span class="st">"Mean Difference"</span>, </span>
<span id="cb8-17"><a></a>             <span class="at">size =</span> <span class="fl">2.5</span>) <span class="sc">+</span> </span>
<span id="cb8-18"><a></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Hours studying"</span>, <span class="at">y =</span> <span class="st">"Grade (out of 10)"</span>, <span class="at">color =</span> <span class="st">""</span>, </span>
<span id="cb8-19"><a></a>       <span class="at">title =</span> <span class="st">"Is this capturing the data??"</span>) <span class="sc">+</span></span>
<span id="cb8-20"><a></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span><span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb8-21"><a></a>  cowplot<span class="sc">::</span><span class="fu">theme_cowplot</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="lec-13_mod_files/figure-revealjs/unnamed-chunk-6-1.png" width="768" class="r-stretch"></section>
<section class="slide level2">

<h3 id="interpreting-slopes">Interpreting slopes</h3>
<p>Extending this to the multivariate case, let’s add hours spent studying (<code>study</code>) as another covariate.</p>
<div class="cell" data-output.lines="[9,10,11,12,13]">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a></a>mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(grade <span class="sc">~</span> tutor_lab <span class="sc">+</span> study, <span class="at">data =</span> t_data)</span>
<span id="cb9-2"><a></a><span class="fu">summary</span>(mod2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>...
Coefficients:
               Estimate Std. Error t value         Pr(&gt;|t|)    
(Intercept)      5.5882     0.3198  17.474 0.00000000000269 ***
tutor_labTutor   1.3751     0.3183   4.320         0.000465 ***
study            1.1777     0.2565   4.592         0.000259 ***
...</code></pre>
</div>
</div>
<p><span class="math display">\[\hat{Y} = b_{0} + b_{1}\text{Tutor} + b_2\text{Study}\]</span></p>
<p>How do we interpret <span class="math inline">\(b_1?\)</span></p>
</section>
<section class="slide level2">

<div class="cell" data-output.lines="[9,10,11,12,13]">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a>mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(grade <span class="sc">~</span> tutor_lab <span class="sc">+</span> study, <span class="at">data =</span> t_data)</span>
<span id="cb11-2"><a></a><span class="fu">summary</span>(mod2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>...
Coefficients:
               Estimate Std. Error t value         Pr(&gt;|t|)    
(Intercept)      5.5882     0.3198  17.474 0.00000000000269 ***
tutor_labTutor   1.3751     0.3183   4.320         0.000465 ***
study            1.1777     0.2565   4.592         0.000259 ***
...</code></pre>
</div>
</div>
<p><span class="math display">\[\hat{Y} = b_{0} + b_{1}\text{Tutor} + b_2\text{Study}\]</span></p>
<p><span class="math inline">\(b_1\)</span> is the difference in means between the two groups <em>if the two groups have the same average level of hours studying</em> or holding <code>study</code> constant.</p>
<p>BTW this is an ANCOVA.</p>
</section>
<section class="slide level2">

<h3 id="visualizing-2">Visualizing</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a>mod <span class="ot">=</span> <span class="fu">lm</span>(grade <span class="sc">~</span> study <span class="sc">+</span> tutor_lab, <span class="at">data =</span> t_data)</span>
<span id="cb13-2"><a></a>t_data<span class="sc">$</span>pmod <span class="ot">=</span> <span class="fu">predict</span>(mod)</span>
<span id="cb13-3"><a></a></span>
<span id="cb13-4"><a></a>predict<span class="fl">.2</span> <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">study =</span> <span class="fu">rep</span>(<span class="fu">mean</span>(t_data<span class="sc">$</span>study), <span class="dv">2</span>), <span class="at">tutor_lab =</span> <span class="fu">c</span>(<span class="st">"No tutor"</span>, <span class="st">"Tutor"</span>))</span>
<span id="cb13-5"><a></a>predict<span class="fl">.2</span><span class="sc">$</span>grade <span class="ot">=</span> <span class="fu">predict</span>(mod, <span class="at">newdata =</span> predict<span class="fl">.2</span>) </span>
<span id="cb13-6"><a></a>predict<span class="fl">.2</span> <span class="ot">=</span> <span class="fu">cbind</span>(predict<span class="fl">.2</span>[<span class="dv">1</span>,], predict<span class="fl">.2</span>[<span class="dv">2</span>,])</span>
<span id="cb13-7"><a></a><span class="fu">names</span>(predict<span class="fl">.2</span>) <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"x1"</span>, <span class="st">"d1"</span>, <span class="st">"y1"</span>, <span class="st">"x2"</span>, <span class="st">"d2"</span>, <span class="st">"y2"</span>)</span>
<span id="cb13-8"><a></a></span>
<span id="cb13-9"><a></a><span class="fu">ggplot</span>(t_data, <span class="fu">aes</span>(study,grade, <span class="at">color =</span> tutor_lab)) <span class="sc">+</span></span>
<span id="cb13-10"><a></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="fu">aes</span>(<span class="at">color =</span> tutor_lab)) <span class="sc">+</span></span>
<span id="cb13-11"><a></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">y =</span> pmod), <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> F)<span class="sc">+</span></span>
<span id="cb13-12"><a></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span> x1, <span class="at">y =</span> y1, <span class="at">xend =</span> x2, <span class="at">yend =</span> y2), <span class="at">data =</span> predict<span class="fl">.2</span>, </span>
<span id="cb13-13"><a></a>               <span class="at">inherit.aes =</span> F, <span class="at">size =</span> <span class="fl">1.5</span>)<span class="sc">+</span></span>
<span id="cb13-14"><a></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Hours studying"</span>, <span class="at">y =</span> <span class="st">"Grade (out of 10)"</span>, <span class="at">color =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb13-15"><a></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span><span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb13-16"><a></a>  cowplot<span class="sc">::</span><span class="fu">theme_cowplot</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="lec-13_mod_files/figure-revealjs/unnamed-chunk-9-1.png" width="768" class="r-stretch"></section>
<section class="slide level2">

<h3 id="visualizing-3">Visualizing</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a></a><span class="fu">ggplot</span>(t_data, <span class="fu">aes</span>(study, grade, <span class="at">group =</span> tutor_lab)) <span class="sc">+</span></span>
<span id="cb14-2"><a></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="fu">aes</span>(<span class="at">shape =</span> tutor_lab, <span class="at">color =</span> tutor_lab)) <span class="sc">+</span></span>
<span id="cb14-3"><a></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">y =</span> pmod), <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> F, <span class="at">color =</span> <span class="st">"black"</span>)<span class="sc">+</span></span>
<span id="cb14-4"><a></a>    <span class="fu">geom_hline</span>(<span class="fu">aes</span>(<span class="at">yintercept =</span> M), <span class="at">linetype =</span> <span class="st">"dashed"</span>,</span>
<span id="cb14-5"><a></a>             <span class="at">data =</span> means, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span> </span>
<span id="cb14-6"><a></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span> x1, <span class="at">y =</span> y1, <span class="at">xend =</span> x2, <span class="at">yend =</span> y2), <span class="at">data =</span> predict<span class="fl">.2</span>, </span>
<span id="cb14-7"><a></a>               <span class="at">inherit.aes =</span> F, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb14-8"><a></a>  <span class="fu">annotate</span>(<span class="st">"segment"</span>, <span class="at">x =</span> <span class="fl">0.5</span>, <span class="at">xend =</span> <span class="fl">0.5</span>, </span>
<span id="cb14-9"><a></a>             <span class="at">y =</span> no_tutor, <span class="at">yend =</span> tutor,</span>
<span id="cb14-10"><a></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>, </span>
<span id="cb14-11"><a></a>           <span class="at">linewidth =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb14-12"><a></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Hours studying"</span>, <span class="at">y =</span> <span class="st">"Grade (out of 10)"</span>, <span class="at">color =</span> <span class="st">""</span>, <span class="at">shape =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb14-13"><a></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span><span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb14-14"><a></a>  cowplot<span class="sc">::</span><span class="fu">theme_cowplot</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="lec-13_mod_files/figure-revealjs/unnamed-chunk-10-1.png" width="768" class="r-stretch"></section>
<section id="what-are-interactions" class="slide level2">
<h2>What are interactions?</h2>
<p>When we have two variables, A and B, in a regression model, we are testing whether these variables have <span style="color:purple">additive effects</span> on our outcome, Y. That is, the effect of A on Y is <strong>constant</strong> over all values of B.</p>
<ul>
<li>Example: Studying and working with a tutor have additive effects on grades; no matter how many hours I spend studying, working with a tutor will improve my grade by 2 points.</li>
</ul>
</section>
<section id="what-are-interactions-1" class="slide level2">
<h2>What are interactions?</h2>
<p>However, we may hypothesis that two variables have <span style="color:purple">joint effects</span>, or interact with each other. In this case, the effect of A on Y changes as a function of B.</p>
<ul>
<li><p>Example: Working with a tutor has a positive impact on grades but only for individuals who do not spend a lot of time studying; for individuals who study a lot, tutoring will have little or no impact.</p></li>
<li><p>This is also referred to as <span style="color:purple">moderation.</span></p></li>
</ul>
<p>Interactions (moderation) tell us whether the effect of one IV (on a DV) <strong><em>depends</em></strong> on another IV.</p>
</section>
<section id="interactions" class="slide level2">
<h2>Interactions</h2>
<p>Now extend this example to include joint effects, not just additive effects:</p>
<p><span class="math display">\[\hat{\text{grade}} = b_{0} + b_{1}\text{Tutor} + b_2\text{Study} + b_3(\text{Tutor}\times\text{Study})\]</span></p>
<div class="cell" data-output.lines="[9,10,11,12,13,14]">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a>mod3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(grade <span class="sc">~</span> tutor_lab <span class="sc">+</span> study <span class="sc">+</span> tutor_lab<span class="sc">*</span>study, <span class="at">data =</span> t_data) </span>
<span id="cb15-2"><a></a>mod3 <span class="ot">&lt;-</span>  <span class="fu">lm</span>(grade <span class="sc">~</span> tutor_lab<span class="sc">*</span>study, <span class="at">data =</span> t_data)</span>
<span id="cb15-3"><a></a><span class="fu">summary</span>(mod3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>...
Coefficients:
                     Estimate Std. Error t value      Pr(&gt;|t|)    
(Intercept)            5.0121     0.3496  14.337 0.00000000015 ***
tutor_labTutor         2.9203     0.6418   4.550      0.000328 ***
study                  1.7567     0.3095   5.676 0.00003443132 ***
tutor_labTutor:study  -1.1713     0.4402  -2.661      0.017093 *  
...</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<h3 id="visualizing-4">Visualizing</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a><span class="fu">ggplot</span>(t_data, <span class="fu">aes</span>(study, grade, <span class="at">color =</span> tutor_lab)) <span class="sc">+</span></span>
<span id="cb17-2"><a></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb17-3"><a></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> F)<span class="sc">+</span></span>
<span id="cb17-4"><a></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Hours studying"</span>, <span class="at">y =</span> <span class="st">"Grade (out of 10)"</span>, <span class="at">color =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb17-5"><a></a>  cowplot<span class="sc">::</span><span class="fu">theme_cowplot</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="lec-13_mod_files/figure-revealjs/unnamed-chunk-13-1.png" width="768" class="r-stretch"><p>Where should we draw the segment to compare means?</p>
</section>
<section id="interpreting-coefficients" class="slide level2">
<h2>Interpreting coefficients</h2>
<p><span class="math display">\[\hat{\text{grade}} = b_{0} + b_{1}\text{Tutor} + b_2\text{Study} + b_3(\text{Tutor}\times\text{Study})\]</span></p>
<div class="cell" data-output.lines="[9,10,11,12,13,14]">
<div class="cell-output cell-output-stdout">
<pre><code>...
Coefficients:
                     Estimate Std. Error t value      Pr(&gt;|t|)    
(Intercept)            5.0121     0.3496  14.337 0.00000000015 ***
tutor_labTutor         2.9203     0.6418   4.550      0.000328 ***
study                  1.7567     0.3095   5.676 0.00003443132 ***
tutor_labTutor:study  -1.1713     0.4402  -2.661      0.017093 *  
...</code></pre>
</div>
</div>
<p>Intercept: the expected value of Y when all predictors are 0</p>
<p><span class="math inline">\(b_1\)</span>: The difference in means (tutor vs no tutor) <em>when study = 0</em></p>
<p><span class="math inline">\(b_2\)</span>: The slope of study <em>when tutor = 0, or the reference group</em></p>
<p><span class="math inline">\(b_3\)</span>?</p>
</section>
<section id="interpreting-coefficients-1" class="slide level2">
<h2>Interpreting coefficients</h2>
<p><span class="math display">\[\hat{\text{grade}} = b_{0} + b_{1}\text{Tutor} + b_2\text{Study} + b_3(\text{Tutor}\times\text{Study})\]</span></p>
<p><span class="math inline">\(b_3\)</span></p>
<ul>
<li>the linear effect of the product of hours studying and tutoring</li>
<li>how much the slope of <code>study</code> differs for the two tutoring groups</li>
<li>how much the effect of tutoring changes for for every one 1 hour increase in studying.</li>
</ul>
</section>
<section id="terms" class="slide level2">
<h2>Terms</h2>
<p>Interactions tell us whether the effect of one IV (on a DV) <em>depends</em> on another IV. In this case, the effect of tutoring <em>depends on</em> a student’s time spent studying. Tutoring has a large effect when a student’s spends little time studying, but a small effect when the amount of time studying is high.</p>
<p><span class="math inline">\(b_3\)</span> is referred to as a “higher-order term.”</p>
<p><span style="color:purple">Higher-order terms</span> are those terms that represent interactions.</p>
</section>
<section id="terms-1" class="slide level2">
<h2>Terms</h2>
<p><span style="color:purple">Lower-order terms</span> change depending on the values of the higher-order terms. The value of <span class="math inline">\(b_1\)</span> and <span class="math inline">\(b_2\)</span> will change depending on the value of <span class="math inline">\(b_3\)</span>.</p>
<ul>
<li>These values represent “conditional effects” (because the value is conditional on the level of the other variable). In many cases, the value and significance test with these terms is either meaningless (if an IV is never equal to 0) or unhelpful, as these values and significance change across the data.</li>
</ul>
</section>
<section id="conditional-effects-and-simple-slopes" class="slide level2">
<h2>Conditional effects and simple slopes</h2>
<p>The regression line estimated in this model is quite difficult to interpret on its own. A good strategy is to decompose the regression equation into <span style="color:purple">simple slopes</span>, which are determined by calculating the conditional effects at a specific level of the moderating variable.</p>
<ul>
<li><p>Simple slope: the equation for Y on X at different levels of Z</p></li>
<li><p>Conditional effect: the slope coefficients in the full regression model that can change. These are the lower-order terms associated with a variable. E.g., studying has a conditional effect on grade.</p></li>
</ul>
</section>
<section class="slide level2">

<p>The conditional nature of these effects is easiest to see by “plugging in” different values for one of your variables. Return to the regression equation estimated in our tutoring data:</p>
</section>
<section class="slide level2">

<div class="cell" data-output.lines="[9,10,11,12,13,14]">
<div class="cell-output cell-output-stdout">
<pre><code>...
Coefficients:
                     Estimate Std. Error t value      Pr(&gt;|t|)    
(Intercept)            5.0121     0.3496  14.337 0.00000000015 ***
tutor_labTutor         2.9203     0.6418   4.550      0.000328 ***
study                  1.7567     0.3095   5.676 0.00003443132 ***
tutor_labTutor:study  -1.1713     0.4402  -2.661      0.017093 *  
...</code></pre>
</div>
</div>
<p><span class="math display">\[\hat{\text{grade}} = 5.01 + 2.92(\text{Tutor})+ 1.76(\text{Study})+ -1.17(\text{T} \times \text{S})\]</span></p>
<div class="fragment">
<p><span style="color:purple">Set Tutoring to 0</span></p>
<p><span class="math display">\[
\begin{aligned}
\hat{\text{grade}} &amp;= 5.01 + 2.92(0)+ 1.76(\text{Study})+ -1.17(0 \times \text{Study}) \\
&amp;= 5.01 + 0+ 1.76(\text{Study})+ 0(\text{Study}) \\
&amp;= 5.01 + 1.76(\text{Study})
\end{aligned}
\]</span></p>
</div>
</section>
<section class="slide level2">

<div class="cell" data-output.lines="[9,10,11,12,13,14]">
<div class="cell-output cell-output-stdout">
<pre><code>...
Coefficients:
                     Estimate Std. Error t value      Pr(&gt;|t|)    
(Intercept)            5.0121     0.3496  14.337 0.00000000015 ***
tutor_labTutor         2.9203     0.6418   4.550      0.000328 ***
study                  1.7567     0.3095   5.676 0.00003443132 ***
tutor_labTutor:study  -1.1713     0.4402  -2.661      0.017093 *  
...</code></pre>
</div>
</div>
<p><span class="math display">\[\hat{\text{grade}} = 5.01 + 2.92(\text{Tutor})+ 1.76(\text{Study})+ -1.17(\text{T} \times \text{S})\]</span></p>
<p><span style="color:purple">Set Tutoring to 1</span></p>
<p><span class="math display">\[
\begin{aligned}
\hat{\text{grade}} &amp;= 5.01 + 2.92(1)+ 1.76(\text{Study})+ -1.17(1 \times \text{Study}) \\
&amp;= 5.01 + 2.92+ 1.76(\text{Study})+ -1.17(\text{Study}) \\
&amp;= 7.93 + 0.59(\text{Study})
\end{aligned}
\]</span> ————————————————————————</p>
</section>
<section id="interaction-shapes" class="slide level2">
<h2>Interaction shapes</h2>
<p>Often we graph the simple slopes as a way to understand the interaction. The shape of the lines in the graph are informative and help us interpret conceptually what’s happening.</p>
</section>
<section class="slide level2">

<h3 id="cross-over-interactions">Cross-over interactions</h3>

<img data-src="lec-13_mod_files/figure-revealjs/unnamed-chunk-19-1.png" width="960" class="r-stretch"></section>
<section class="slide level2">

<h3 id="ordinal-interactions">Ordinal interactions</h3>

<img data-src="lec-13_mod_files/figure-revealjs/unnamed-chunk-20-1.png" width="960" class="r-stretch"></section>
<section class="slide level2">

<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb21-2"><a></a><span class="fu">plot_model</span>(mod3, <span class="at">type =</span> <span class="st">"int"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="lec-13_mod_files/figure-revealjs/unnamed-chunk-21-1.png" width="960" class="r-stretch"></section>
<section class="slide level2">

<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb22-2"><a></a><span class="fu">plot_model</span>(mod3, <span class="at">type =</span> <span class="st">"pred"</span>, <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">"study"</span>, <span class="st">"tutor_lab"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="lec-13_mod_files/figure-revealjs/unnamed-chunk-22-1.png" width="960" class="r-stretch"></section>
<section id="centering" class="slide level2">
<h2>Centering</h2>
<p>The regression equation built using the raw data is not only difficult to interpret, but often the terms displayed are not relevant to the hypotheses we’re interested.</p>
<ul>
<li><span class="math inline">\(b_0\)</span> is the expected value when all predictors are 0, but this may never happen in real life</li>
<li><span class="math inline">\(b_1\)</span> is the effect of tutoring when hours spent studying is equal to 0, but this may not ever happen either.</li>
</ul>
</section>
<section class="slide level2">

<p><span style="color:purple">Centering</span> your variables by subtracting the mean from all values can improve the interpretation of your results.</p>
<ul>
<li>Remember, a linear transformation does not change associations (correlations) between variables. In this case, it only changes the interpretation for some coefficients.</li>
</ul>
</section>
<section class="slide level2">

<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a></a>t_data <span class="ot">=</span> t_data <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a></a>  <span class="fu">mutate</span>(<span class="at">study_c =</span> study <span class="sc">-</span> <span class="fu">mean</span>(study))</span>
<span id="cb23-3"><a></a><span class="fu">head</span>(t_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  ID study grade tutor tutor_lab study_c
1  1  1.62   9.0     1     Tutor  0.3045
2  2  0.54   7.8     1     Tutor -0.7755
3  3  0.86   8.5     1     Tutor -0.4555
4  4  0.80   6.2     0  No tutor -0.5155
5  5  0.36   6.9     0  No tutor -0.9555
6  6  2.14   9.0     1     Tutor  0.8245</code></pre>
</div>
</div>
<p>Why did we not center Y (grades)?</p>
</section>
<section class="slide level2">

<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a></a><span class="fu">summary</span>(<span class="fu">lm</span>(grade <span class="sc">~</span> tutor_lab <span class="sc">+</span> study_c <span class="sc">+</span> tutor_lab<span class="sc">:</span>study_c, <span class="at">data =</span> t_data))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = grade ~ tutor_lab + study_c + tutor_lab:study_c, 
    data = t_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.5728 -0.3837 -0.1584  0.1838  1.2555 

Coefficients:
                       Estimate Std. Error t value             Pr(&gt;|t|)    
(Intercept)              7.3230     0.1929  37.963 &lt; 0.0000000000000002 ***
tutor_labTutor           1.3794     0.2732   5.049             0.000119 ***
study_c                  1.7567     0.3095   5.676            0.0000344 ***
tutor_labTutor:study_c  -1.1713     0.4402  -2.661             0.017093 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5232 on 16 degrees of freedom
Multiple R-squared:  0.8811,    Adjusted R-squared:  0.8588 
F-statistic: 39.53 on 3 and 16 DF,  p-value: 0.0000001259</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a></a><span class="fu">summary</span>(mod3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = grade ~ tutor_lab + study + tutor_lab:study, data = t_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.5728 -0.3837 -0.1584  0.1838  1.2555 

Coefficients:
                     Estimate Std. Error t value      Pr(&gt;|t|)    
(Intercept)            5.0121     0.3496  14.337 0.00000000015 ***
tutor_labTutor         2.9203     0.6418   4.550      0.000328 ***
study                  1.7567     0.3095   5.676 0.00003443132 ***
tutor_labTutor:study  -1.1713     0.4402  -2.661      0.017093 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5232 on 16 degrees of freedom
Multiple R-squared:  0.8811,    Adjusted R-squared:  0.8588 
F-statistic: 39.53 on 3 and 16 DF,  p-value: 0.0000001259</code></pre>
</div>
</div>
<p>What changed? What stayed the same?</p>
</section>
<section id="wrapping-up" class="slide level2">
<h2>Wrapping Up</h2>
<p>We just examined moderation as an interaction between a categorical variable and a continuous variable</p>
</section>
<section id="next-steps" class="slide level2">
<h2>Next Steps</h2>
<p>Moderations with two <em>continuous</em> predictors</p>
</section>
<section id="what-are-interactions-2" class="slide level2">
<h2>What are interactions?</h2>
<p>When we have two variables, A and B, in a regression model, we are testing whether these variables have <strong>additive effects</strong> on our outcome, Y. That is, the effect of A on Y is constant over all values of B.</p>
<ul>
<li>Example: Drinking coffee and hours of sleep have additive effects on alertness; no matter how any hours I slept the previous night, drinking one cup of coffee will make me .5 SD more awake than not drinking coffee.</li>
</ul>
</section>
<section id="what-are-interactions-3" class="slide level2">
<h2>What are interactions?</h2>
<p>However, we may hypothesis that two variables have <strong>joint effects</strong>, or interact with each other. In this case, the effect of A on Y changes as a function of B.</p>
<ul>
<li><p>Example: Chronic stress has a negative impact on health but only for individuals who receive little or no social support; for individuals with high social support, chronic stress has no impact on health.</p></li>
<li><p>This is also referred to as <strong>moderation.</strong></p></li>
<li><p>The <strong>“interaction term”</strong> is the regression coefficient that tests this hypothesis.</p></li>
</ul>
</section>
<section class="slide level2">

<div class="columns">
<div class="column" style="width:50%;">
<h3 id="univariate-regression">Univariate regression</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lec-13_mod_files/figure-revealjs/unnamed-chunk-26-1.png" width="432"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:50%;">
<h3 id="multivariate-regression">Multivariate regression</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lec-13_mod_files/figure-revealjs/unnamed-chunk-27-1.png" width="432"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section class="slide level2">

<h3 id="multivariate-regression-with-an-interaction">Multivariate regression with an interaction</h3>
<p><img data-src="images/clipboard-2770957871.png"></p>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/clipboard-2770957871.png" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
</section>
<section class="slide level2">

<h3 id="example">Example</h3>
<p>Here we have an outcome (<code>Stress</code>) that we are interested in predicting from trait <code>Anxiety</code> and levels of social <code>Support</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a></a>stress.data <span class="ot">&lt;-</span> <span class="fu">import</span>(<span class="fu">here</span>(<span class="st">"files"</span>, <span class="st">"data"</span>, <span class="st">"stress.csv"</span>))</span>
<span id="cb29-2"><a></a>psych<span class="sc">::</span><span class="fu">describe</span>(stress.data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           vars   n  mean    sd median trimmed   mad  min    max  range  skew
id            1 118 59.50 34.21  59.50   59.50 43.74 1.00 118.00 117.00  0.00
Anxiety       2 118  7.61  2.49   7.75    7.67  2.26 0.70  14.64  13.94 -0.18
Stress        3 118  5.18  1.88   5.27    5.17  1.65 0.62  10.32   9.71  0.08
Support       4 118  8.73  3.28   8.52    8.66  3.16 0.02  17.34  17.32  0.18
Condition*    5 118  1.53  0.50   2.00    1.53  0.00 1.00   2.00   1.00 -0.10
           kurtosis   se
id            -1.23 3.15
Anxiety        0.28 0.23
Stress         0.22 0.17
Support        0.19 0.30
Condition*    -2.01 0.05</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a></a>imodel <span class="ot">&lt;-</span> <span class="fu">lm</span>(Stress <span class="sc">~</span> Anxiety<span class="sc">*</span>Support, <span class="at">data =</span> stress.data)</span>
<span id="cb31-2"><a></a><span class="fu">summary</span>(imodel)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Stress ~ Anxiety * Support, data = stress.data)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.8163 -1.0783  0.0373  0.9200  3.6109 

Coefficients:
                Estimate Std. Error t value       Pr(&gt;|t|)    
(Intercept)     -2.73966    1.12101  -2.444        0.01606 *  
Anxiety          0.61561    0.13010   4.732 0.000006435373 ***
Support          0.66697    0.09547   6.986 0.000000000202 ***
Anxiety:Support -0.04174    0.01309  -3.188        0.00185 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.462 on 114 degrees of freedom
Multiple R-squared:  0.4084,    Adjusted R-squared:  0.3928 
F-statistic: 26.23 on 3 and 114 DF,  p-value: 0.0000000000005645</code></pre>
</div>
</div>
<p><span class="math display">\[\hat{Stress} = -2.74 + 0.62(Anx) + 0.67(Sup) + -0.04(Anx \times Sup)\]</span></p>
</section>
<section id="conditional-effects-and-simple-slopes-1" class="slide level2">
<h2>Conditional effects and simple slopes</h2>
<p>The regression line estimated in this model is quite difficult to interpret on its own. A good strategy is to decompose the regression equation into <strong>simple slopes</strong>, which are determined by calculating the conditional effects at a specific level of the moderating variable.</p>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li>Simple slope: the equation for Y on X at different levels of Z; but also refers to only the coefficient for X in this equation</li>
</ul>
</div><div class="column" style="width:50%;">
<ul>
<li>Conditional effect: the slope coefficients in the full regression model which can change. These are the lower-order terms associated with a variable.</li>
</ul>
</div></div>
</section>
<section class="slide level2">

<p>The conditional nature of these effects is easiest to see by “plugging in” different values for one of your variables. Return to the regression equation estimated in our stress data:</p>
<p><span class="math display">\[\hat{Stress} = -2.74 + 0.62(\text{Anx})+ 0.67(\text{Sup})+ -0.04(\text{Anx} \times \text{Sup})\]</span></p>
</section>
<section class="slide level2">

<p>The conditional nature of these effects is easiest to see by “plugging in” different values for one of your variables. Return to the regression equation estimated in our stress data:</p>
<p><span class="math display">\[\hat{Stress} = -2.74 + 0.62(\text{Anx})+ 0.67(\text{Sup})+ -0.04(\text{Anx} \times \text{Sup})\]</span></p>
<p><strong>Set Support to 5</strong></p>
<p><span class="math display">\[
\begin{aligned}
\hat{Stress} &amp;= -2.74 + 0.62(\text{Anx})+ 0.67(5)+ -0.04(\text{Anx} \times 5) \\
&amp;= -2.74 + 0.62(\text{Anx})+ 3.35+ -0.2(\text{Anx}) \\
&amp;= 0.61 + 0.42(\text{Anx})
\end{aligned}
\]</span></p>
</section>
<section class="slide level2">

<p>The conditional nature of these effects is easiest to see by “plugging in” different values for one of your variables. Return to the regression equation estimated in our stress data:</p>
<p><span class="math display">\[\hat{Stress} = -2.74 + 0.62(\text{Anx})+ 0.67(\text{Sup})+ -0.04(\text{Anx} \times \text{Sup})\]</span></p>
<p><strong>Set Support to 10</strong></p>
<p><span class="math display">\[
\begin{aligned}
\hat{Stress} &amp;= -2.74 + 0.62(\text{Anx})+ 0.67(10)+ -0.04(\text{Anx} \times 10) \\
&amp;= -2.74 + 0.62(\text{Anx})+ 6.7+ -0.4(\text{Anx}) \\
&amp;= 3.96 + 0.22(\text{Anx})
\end{aligned}
\]</span></p>
</section>
<section id="plotting-interactions" class="slide level2">
<h2>Plotting interactions</h2>
<p>What is this plotting?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a></a><span class="fu">plot_model</span>(imodel, <span class="at">type =</span> <span class="st">"pred"</span>, <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">"Support"</span>, <span class="st">"Anxiety[mean]"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="lec-13_mod_files/figure-revealjs/unnamed-chunk-35-1.png" width="960" class="r-stretch"></section>
<section class="slide level2">

<div class="columns">
<div class="column" style="width:50%;">
<p>Put values of the moderator in brackets!</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lec-13_mod_files/figure-revealjs/intplot1-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a></a><span class="fu">plot_model</span>(imodel, <span class="at">type =</span> <span class="st">"pred"</span>, </span>
<span id="cb34-2"><a></a>           <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">"Support"</span>, </span>
<span id="cb34-3"><a></a>                     <span class="st">"Anxiety[5,10]"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div><div class="column" style="width:50%;">
<p>Put values of the moderator in argument <code>mdrt.values</code>!</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lec-13_mod_files/figure-revealjs/intplot2-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a></a><span class="fu">plot_model</span>(imodel, <span class="at">type =</span> <span class="st">"pred"</span>, </span>
<span id="cb35-2"><a></a>           <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">"Support"</span>, </span>
<span id="cb35-3"><a></a>                     <span class="st">"Anxiety"</span>), </span>
<span id="cb35-4"><a></a>           <span class="at">mdrt.values =</span> <span class="st">"meansd"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div></div>
</section>
<section id="testing-simple-slopes" class="slide level2">
<h2>Testing simple slopes</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a></a><span class="co">#https://easystats.github.io/modelbased/articles/introduction_comparisons_3.html?q=simple%20slo#contrasts-and-comparisons-for-slopes-of-numeric-predictors</span></span>
<span id="cb36-2"><a></a></span>
<span id="cb36-3"><a></a>pred <span class="ot">&lt;-</span> <span class="fu">estimate_means</span>(imodel, <span class="fu">c</span>(<span class="st">"Support"</span>, <span class="st">"Anxiety = c(5,6,7)"</span>))</span>
<span id="cb36-4"><a></a><span class="fu">plot</span>(pred)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a></a><span class="fu">estimate_slopes</span>(imodel, <span class="st">"Support"</span>, <span class="at">by =</span> <span class="st">"Anxiety = c(5,6,7)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Estimated Marginal Effects

Anxiety | Slope |   SE |       95% CI | t(114) |      p
-------------------------------------------------------
5       |  0.46 | 0.05 | [0.36, 0.56] |   8.83 | &lt; .001
6       |  0.42 | 0.05 | [0.32, 0.51] |   8.44 | &lt; .001
7       |  0.37 | 0.05 | [0.28, 0.47] |   7.47 | &lt; .001

Marginal effects estimated for Support
Type of slope was dY/dX</code></pre>
</div>
</div>
<img data-src="lec-13_mod_files/figure-revealjs/unnamed-chunk-38-1.png" width="960" class="r-stretch"></section>
<section id="testing-simple-slopes-1" class="slide level2">
<h2>Testing simple slopes</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a></a><span class="fu">estimate_slopes</span>(imodel, <span class="st">"Support"</span>, <span class="at">by =</span> <span class="st">"Anxiety=[sd]"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Estimated Marginal Effects

Anxiety | Slope |   SE |       95% CI | t(114) |      p
-------------------------------------------------------
5.13    |  0.45 | 0.05 | [0.35, 0.55] |   8.82 | &lt; .001
7.61    |  0.35 | 0.05 | [0.25, 0.45] |   6.67 | &lt; .001
10.10   |  0.25 | 0.07 | [0.11, 0.38] |   3.48 | &lt; .001

Marginal effects estimated for Support
Type of slope was dY/dX</code></pre>
</div>
</div>
</section>
<section id="simple-slopes---significance-tests" class="slide level2">
<h2>Simple slopes - Significance tests</h2>
<p>What if you want to compare slopes to each other? How would we test this?</p>
<div class="fragment">
<p>The test of the interaction coefficient is equivalent to the test of the difference in slopes at levels of Z separated by 1 unit.</p>
<div class="cell" data-highlight.output="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a></a><span class="fu">coef</span>(<span class="fu">summary</span>(imodel))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   Estimate Std. Error   t value           Pr(&gt;|t|)
(Intercept)     -2.73966246 1.12100519 -2.443934 0.0160605206624654
Anxiety          0.61561220 0.13010161  4.731780 0.0000064353728132
Support          0.66696689 0.09547464  6.985802 0.0000000002017698
Anxiety:Support -0.04174076 0.01309328 -3.187954 0.0018497364252185</code></pre>
</div>
</div>
</div>
</section>
<section class="slide level2">

<p>Or you can use the <code>modelbased</code> package.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a></a><span class="fu">estimate_contrasts</span>(imodel, <span class="st">"Support"</span>, <span class="at">by =</span> <span class="st">"Anxiety=[sd]"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Marginal Contrasts Analysis

Level1 | Level2 | Difference |   SE |         95% CI | t(114) |     p
---------------------------------------------------------------------
7.614  | 5.127  |      -0.10 | 0.03 | [-0.17, -0.04] |  -3.19 | 0.002
10.102 | 5.127  |      -0.21 | 0.07 | [-0.34, -0.08] |  -3.19 | 0.002
10.102 | 7.614  |      -0.10 | 0.03 | [-0.17, -0.04] |  -3.19 | 0.002

Variable predicted: Stress
Predictors contrasted: Support
Predictors averaged: Support (8.7)
p-values are uncorrected.</code></pre>
</div>
</div>
</section>
<section class="slide level2">

<p>Perhaps you noted that the t-statistic and p-values are the same… The OLS model constrains the change in slope to be equal equivalent across values of the moderator.</p>
</section>
<section class="slide level2">

<p>Remember, regression and ANOVA are mathematically equivalent – both divide the total variability in <span class="math inline">\(Y\)</span> into variability overlapping with (“explained by”) the model and residual variability.</p>
<p>What differs is the way results are presented. The regression framework is excellent for continuous variables, but interpreting the interactions of categorical variables is more difficult.</p>
</section>
<section class="slide level2">



</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="images/640_hex.png" class="slide-logo"></p>
<div class="footer footer-default">
<p><a href="https://dharaden.github.io/psyc640/">course-website</a></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: false,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/dharaden\.github\.io\/psyc640");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>