{
  "hash": "dde1f5a131fe93f3ea38201649e6aea5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 05: Simple Regression\"\nsubtitle: \"Date: September 24, 2026\"\nfooter:  \"[course-website](https://dharaden.github.io/psyc640/)\"\nlogo: \"images/640_hex.png\"\nformat:\n  revealjs:\n    theme: [default, brand, clean.scss]\n    multiplex: false\n    transition: fade\n    transition-speed: fast\n    slide-number: true\n    incremental: false\n    chalkboard: true\n    overview: false\n    scrollable: true\n    code-line-numbers: true\neditor: visual\nexecute:\n  echo: true\n  freeze: auto\n---\n\n## Today...\n\n**The Linear Model** — one machine, most of the course\n\n- Why a line? (and why regression *first*)\n- Data = Model + Error\n- Where the intercept and slope come from\n- Reading a slope out loud\n- How well does the line fit? ($R^2$, effect size)\n- The punchline from Lab 5\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# File management\nlibrary(here)\n# for dplyr, ggplot2\nlibrary(tidyverse)\n# Loading data\nlibrary(rio)\n# tidy model output\nlibrary(broom)\n# descriptives\nlibrary(psych)\n# pretty tables\nlibrary(sjPlot)\n\n#Remove Scientific Notation\noptions(scipen = 999)\n\ncah <- import(here(\"files\", \"data\", \"CAH.csv\"))\n```\n:::\n\n\n------------------------------------------------------------------------\n\n## First, a confession about Lab 5\n\nIn Lab 5 you ran three things:\n\n1.  A **t-test** comparing two groups\n2.  A **correlation** between two continuous variables\n3.  An `lm()` — the \"sneak peek\" 👀\n\nAnd the numbers came back *the same*.\n\n. . .\n\nThat was not a bug, and it was not a coincidence.\n\n::: callout-important\nRegression is not a new test that sits next to t-tests and correlations. It is the **general machine** that both of them are special cases of.\n:::\n\n------------------------------------------------------------------------\n\n## Why I teach regression first\n\nRegression is a general data analytic system\n\n- Lots of things fall under the umbrella of regression\n\n- It handles many forms of relations and types of variables\n\n- The output gives you **effect sizes** *and* **statistical significance**\n\n- We can add multiple predictors and account for their intercorrelations\n\n. . .\n\nLearn one machine well, then add parts to it. That is the whole plan for the next eight weeks.\n\n------------------------------------------------------------------------\n\n### Uses for regression\n\n::: incremental\n- **Adjustment**: Take into account (*control*) known effects in a relationship\n\n- **Prediction**: Develop a model based on what has happened previously to predict what will happen in the future\n\n- **Explanation**: Examine the influence of one or more variables on some outcome\n:::\n\n# Part 1: Building the Line\n\n------------------------------------------------------------------------\n\n### The core idea\n\nWith regression, we are ***building a model*** that we think best represents the data, and the broader world\n\n$$\nData = Model + error\n$$\n\n. . .\n\nEvery model we build for the rest of the semester is a variation on this sentence.\n\n------------------------------------------------------------------------\n\n## A line you already know\n\nAt the simplest form we draw a line to characterize the linear relationship between two variables, so that for any value of `x` we have an estimate of `y`\n\n$$\nY = mX + b\n$$\n\n::::::: columns\n:::: {.column width=\"50%\"}\n::: incremental\n- Y = Outcome Variable (DV)\n\n- m = Slope Term\n:::\n::::\n\n:::: {.column width=\"50%\"}\n::: incremental\n- X = Predictor (IV)\n\n- b = Intercept\n:::\n::::\n:::::::\n\n------------------------------------------------------------------------\n\n### Let's \"science up\" the equation\n\n$$\nY_i = b_0 + b_1X_i + e_i\n$$\n\nThis captures how we calculate **each observation** ( $Y_i$ )\n\n$$\n\\hat{Y_i} = b_0 + b_1X_i\n$$\n\nThis gives the \"best guess\" or *expected* value of $Y$ given $X$\n\n------------------------------------------------------------------------\n\n### Expected vs. Actual\n\n$$Y_i = b_{0} + b_{1}X_i + e_i \\qquad \\hat{Y_i} = b_{0} + b_{1}X_i$$\n\n$\\hat{Y}$ signifies the **fitted** score — no error. We interpret it as \"on average.\"\n\nThe difference between the fitted and the observed score is the **residual**:\n\n$$Y_i - \\hat{Y_i} = e_i$$\n\n::: callout-note\nThere is a different $e$ value for **each observation** in the dataset. The residual is the part of a person your model gets wrong — hold onto that, it becomes the whole story in a few weeks.\n:::\n\n------------------------------------------------------------------------\n\n## OLS\n\n::: incremental\n- How do we find the regression estimates?\n\n- **O**rdinary **L**east **S**quares estimation\n\n- Minimizes deviations\n\n  - $$ min\\sum(Y_{i} - \\hat{Y} ) ^{2} $$\n\n- Other estimation procedures are possible (and necessary in some cases)\n:::\n\n------------------------------------------------------------------------\n\n## Some data\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(142)\nx.1 <- rnorm(10, 0, 1)\ne.1 <- rnorm(10, 0, 2)\ny.1 <- .5 + .55 * x.1 + e.1\nd.1 <- data.frame(x.1, y.1)\nm.1 <- lm(y.1 ~ x.1, data = d.1)\nd1.f <- augment(m.1)\n\nggplot(d1.f, aes(x = x.1, y = y.1)) +\n  geom_point(size = 2) +\n  geom_smooth(method = lm, se = FALSE) +\n  theme_bw(base_size = 20)\n```\n\n::: {.cell-output-display}\n![](lec-05_regression_files/figure-revealjs/plot1-1.png){width=960}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## The fitted values ( $\\hat{Y}$ )\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(d1.f, aes(x = x.1, y = y.1)) +\n  geom_point(size = 2) +\n  geom_point(aes(y = .fitted), shape = 1, size = 2) +\n  theme_bw(base_size = 20)\n```\n\n::: {.cell-output-display}\n![](lec-05_regression_files/figure-revealjs/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## The residuals ( $e_i$ )\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(d1.f, aes(x = x.1, y = y.1)) +\n  geom_point(size = 2) +\n  geom_point(aes(y = .fitted), shape = 1, size = 2) +\n  geom_segment(aes(xend = x.1, yend = .fitted), color = \"red\") +\n  theme_bw(base_size = 20)\n```\n\n::: {.cell-output-display}\n![](lec-05_regression_files/figure-revealjs/unnamed-chunk-3-1.png){width=960}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Put it together\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(d1.f, aes(x = x.1, y = y.1)) +\n  geom_point(size = 2) +\n  geom_smooth(method = lm, se = FALSE) +\n  geom_point(aes(y = .fitted), shape = 1, size = 2) +\n  geom_segment(aes(xend = x.1, yend = .fitted), color = \"red\") +\n  theme_bw(base_size = 20)\n```\n\n::: {.cell-output-display}\n![](lec-05_regression_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Compare to a bad fit\n\nWhich has more \\[**RED\\]**{style=\"color: red;\"}\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec-05_regression_files/figure-revealjs/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec-05_regression_files/figure-revealjs/unnamed-chunk-6-1.png){width=960}\n:::\n:::\n\n:::\n:::::\n\n------------------------------------------------------------------------\n\n## OLS\n\nThe line that yields the smallest sum of squared deviations\n\n$$\\Sigma(Y_i - \\hat{Y_i})^2$$ $$= \\Sigma(Y_i - (b_0+b_{1}X_i))^2$$ $$= \\Sigma(e_i)^2$$\n\n. . .\n\nYou *could* try many different coefficients until you find the pair with the smallest sum of squared deviations. Luckily, there are simple calculations that yield the OLS solution every time.\n\n------------------------------------------------------------------------\n\n## Where does the slope come from? 🤔\n\nStarting with the **covariance** between two variables:\n\n$$cov_{xy} = \\frac{\\sum(x-\\bar{x})(y-\\bar{y})}{N-1}$$\n\nand the correlation, which is just a standardized covariance:\n\n$$r_{xy} = \\frac{cov_{xy}}{s_x s_y}$$\n\n. . .\n\nThe regression coefficient is built from exactly the same pieces.\n\n------------------------------------------------------------------------\n\n## Regression coefficient, $b_{1}$\n\n$$b_{1} = \\frac{cov_{XY}}{s_{x}^{2}} = r_{xy} \\frac{s_{y}}{s_{x}}$$\n\nWhat units is the regression coefficient in?\n\n. . .\n\nThe slope equals the estimated change in **Y** for a **1-unit** change in **X**\n\n::: callout-tip\nA correlation is unitless. A slope is **in the units of your study**. That is why a slope is often the more useful number to report to a human being.\n:::\n\n------------------------------------------------------------------------\n\n## Slope *is* the correlation (rescaled)\n\n$$\\Large b_{1} = r_{xy} \\frac{s_{y}}{s_{x}}$$\n\nIf the standard deviation of both X and Y is equal to 1:\n\n$$\\Large b_1 = r_{xy} \\frac{s_{y}}{s_{x}} = r_{xy} \\frac{1}{1} = r_{xy} = \\beta_{yx}$$\n\n. . .\n\n**Standardize both variables and the slope becomes the correlation.** Same information, different clothes.\n\n------------------------------------------------------------------------\n\n## Estimating the intercept, $b_0$\n\n- The intercept adjusts for differences in the means of X and Y\n\n$$\\hat{Y_i} = \\bar{Y} + r_{xy} \\frac{s_{y}}{s_{x}}(X_i-\\bar{X})$$\n\n- It is where the regression line crosses the y-axis, at $X = 0$\n\n- It ensures the line runs through the point $(\\bar{X}, \\bar{Y})$\n\n$$\\Large b_0 = \\bar{Y} - b_1\\bar{X}$$\n\n------------------------------------------------------------------------\n\n## 🔍 Visualizing OLS\n\nPlay with these — they make the \"least squares\" part click:\n\n<https://setosa.io/ev/ordinary-least-squares-regression/>\n\n[https://observablehq.com/\\@yizhe-ang/interactive-visualization-of-linear-regression](https://observablehq.com/@yizhe-ang/interactive-visualization-of-linear-regression)\n\n# Part 2: Reading a Line Out Loud\n\n------------------------------------------------------------------------\n\n## Our data today 🃏\n\n**Cards Against Humanity: *Pulse of the Nation*** — a national poll that asked serious demographic questions *and* some very strange ones.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncah %>%\n  select(age, transformers, books) %>%\n  psych::describe()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             vars    n  mean    sd median trimmed   mad min  max range  skew\nage             1 1000 49.41 16.63     50   49.30 17.79  18   99    81  0.07\ntransformers    2  938  1.33  1.56      1    1.10  1.48   0    5     5  0.90\nbooks           3  977 22.33 75.87      5    9.47  7.41   0 1000  1000 10.00\n             kurtosis   se\nage             -0.49 0.53\ntransformers    -0.38 0.05\nbooks          118.09 2.43\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## 🛠️ Activity Stop 1: One Line, Two Stories\n\n::: callout-tip\n**Part A: Follow along** · \\~20 min · Pairs\n:::\n\nWe fit this model together, from the top:\n\n- Plot it, then guess *r* **before** you run it\n- `lm()`, find the intercept and slope\n- Say the slope in a unit that means something\n- Predict a person and compute their residual\n\n[Open the activity](../class-activities/wk5_linear-model.html){.button target=\"_blank\"}\n\n------------------------------------------------------------------------\n\n## Step 1: ALWAYS visualize first\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(cah, aes(x = age, y = transformers)) +\n  geom_point(alpha = .3) +\n  geom_smooth(method = \"lm\", se = FALSE) +\n  labs(x = \"Age (years)\",\n       y = \"Transformers movies seen\") +\n  theme_bw(base_size = 20)\n```\n\n::: {.cell-output-display}\n![](lec-05_regression_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## By hand, then by R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr        <- cor(cah$age, cah$transformers, use = \"pairwise\")\ns_age    <- sd(cah$age, na.rm = TRUE)\ns_tf     <- sd(cah$transformers, na.rm = TRUE)\nm_age    <- mean(cah$age, na.rm = TRUE)\nm_tf     <- mean(cah$transformers, na.rm = TRUE)\n\nb1 <- r * (s_tf / s_age)\nb0 <- m_tf - (b1 * m_age)\n\nc(r = r, b1 = b1, b0 = b0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          r          b1          b0 \n-0.26644722 -0.02498682  2.56823762 \n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## In `R`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit.1 <- lm(transformers ~ age, data = cah)\nsummary(fit.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = transformers ~ age, data = cah)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-2.1206 -1.1055 -0.5472  0.9784  4.8588 \n\nCoefficients:\n            Estimate Std. Error t value            Pr(>|t|)    \n(Intercept)  2.57733    0.15503  16.625 <0.0000000000000002 ***\nage         -0.02538    0.00300  -8.457 <0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.504 on 936 degrees of freedom\n  (62 observations deleted due to missingness)\nMultiple R-squared:  0.07099,\tAdjusted R-squared:   0.07 \nF-statistic: 71.53 on 1 and 936 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n:::\n\n\n::: notes\nPoint at the Estimate column first, then the t and p. Note the slope's t is identical to cor.test — we prove it on the next slides.\n:::\n\n------------------------------------------------------------------------\n\n## wait...they aren't the same? Rounding?\n\nThe results are close, but not identical. What's the deal??\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nc(r = r, b1 = b1, b0 = b0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          r          b1          b0 \n-0.26644722 -0.02498682  2.56823762 \n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(fit.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)   2.58     0.155       16.6  1.41e-54\n2 age          -0.0254   0.00300     -8.46 1.04e-16\n```\n\n\n:::\n:::\n\n:::\n:::::\n\n. . .\n\n**MISSING DATA**\n\nOur data has 62 participants with missing values\n\n`lm()` just kicks folks out with `NA` - listwise deletion\n\nHand calculation used all participants in the data\n\n------------------------------------------------------------------------\n\n## Comparing...again\n\nThis time we are going to listwise delete participants.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncah_tf <- cah %>% drop_na(age, transformers)\nr        <- cor(cah_tf$age, cah_tf$transformers, use = \"pairwise\")\ns_age    <- sd(cah_tf$age, na.rm = TRUE)\ns_tf     <- sd(cah_tf$transformers, na.rm = TRUE)\nm_age    <- mean(cah_tf$age, na.rm = TRUE)\nm_tf     <- mean(cah_tf$transformers, na.rm = TRUE)\n\nb1 <- r * (s_tf / s_age)\nb0 <- m_tf - (b1 * m_age)\n\nc(r = r, b1 = b1, b0 = b0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          r          b1          b0 \n-0.26644722 -0.02537607  2.57733245 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(fit.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)   2.58     0.155       16.6  1.41e-54\n2 age          -0.0254   0.00300     -8.46 1.04e-16\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Saying the slope out loud\n\n$$\\widehat{transformers} = 2.58 - 0.025(age)$$\n\n::: incremental\n- \"Each **additional year** of age is associated with **0.025 fewer** Transformers movies seen.\"\n\n- That sounds like nothing. So **rescale it to a unit people care about**:\n\n  - 10 years → about **0.25 fewer** movies\n  - 40 years → about **one whole movie** fewer\n\n- Note the word **associated**. Nobody was randomly assigned an age.\n:::\n\n------------------------------------------------------------------------\n\n## And the intercept?\n\n$b_0 = 2.58$ = the predicted number of Transformers movies for a person aged **zero**.\n\n. . .\n\n::: callout-warning\n## Careful\n\nNobody in this sample is under **18**. A prediction at age 0 is **extrapolation** — the model has never seen data anywhere near there.\n\nThe intercept is an **anchor for the line**, not a finding.\n:::\n\n. . .\n\nWhen zero is not meaningful, **centering** the predictor fixes the interpretation (we will do this for real in Week 9).\n\n------------------------------------------------------------------------\n\n## Predict a person\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# predicted movies for a 20-year-old\nb0 + b1 * 20\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.069811\n```\n\n\n:::\n:::\n\n\n. . .\n\nA 20-year-old in the data who has seen **4** movies:\n\n$$e_i = Y_i - \\hat{Y_i} = 4 - 2.07 = +1.93$$\n\n**Positive residual** → above the line → the model **under-predicted** this person.\n\n------------------------------------------------------------------------\n\n## ☕ Break {background-color=\"#C9ADE0\"}\n\n**10 minutes**\n\nWhen we come back: how do we know if this line is any *good*?\n\n# Part 3: How Well Does the Line Fit?\n\n------------------------------------------------------------------------\n\n## Statistical inference\n\n- The way the world is = our model + error\n\n- How good is our model? Does it \"fit\" the data well?\n\n. . .\n\nTo assess fit, we examine the proportion of variance in our outcome that is \"explained\" by our model.\n\nTo do that, we **partition the variance** into two categories: variability captured by the model, and variability that is not.\n\n------------------------------------------------------------------------\n\n## Partitioning variation\n\nStart with the relationship between observed $Y$ and fitted $\\hat{Y}$:\n\n$$Y_i = \\hat{Y}_i + e_i$$\n\n. . .\n\nVariances are **additive when two variables are independent**. If C = A + B, then the variance of C is the sum of the variances of A and B.\n\n. . .\n\nWhy can we use that rule here?\n\n::: notes\nStudents must recognize that Y-hat and e are uncorrelated — they must be, by the way OLS is built.\n:::\n\n------------------------------------------------------------------------\n\n## Partitioning variation\n\n::::: columns\n::: {.column width=\"50%\"}\n[$\\hat{Y}_i$ and $e_i$ are independent of each other. So the variance of $Y$ equals the variance of $\\hat{Y}$ plus the variance of $e$.]{style=\"font-size:80%\"}\n\n$$\\large s^2_Y = s^2_{\\hat{Y}} + s^2_{e}$$\n:::\n\n::: {.column width=\"50%\"}\n[Variances are sums of squares divided by N−1, and all have the same sample size here, so:]{style=\"font-size:80%\"}\n\n$$\\large SS_Y = SS_{\\hat{Y}} + SS_{\\text{e}}$$\n:::\n:::::\n\n. . .\n\n$$ SS_Y = SS_{\\text{Model}} + SS_{\\text{Residual}}$$\n\n------------------------------------------------------------------------\n\n## Coefficient of Determination\n\n$$\\Large \\frac{SS_{Model}}{SS_{Y}} = \\frac{s_{Model}^2}{s_{y}^2} = R^2$$\n\n$R^2$ is the **proportion of variance in Y explained by the model**\n\n. . .\n\n$$\\large \\sqrt{R^2} = r_{Y\\hat{Y}}$$\n\nWith one predictor, that is just our old friend $r$.\n\n------------------------------------------------------------------------\n\n## Ta da! 🎉\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# the correlation, squared\ncor(cah$age, cah$transformers, use = \"pairwise\")^2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.07099412\n```\n\n\n:::\n\n```{.r .cell-code}\n# R-squared straight from the model\nsummary(fit.1)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.07099412\n```\n\n\n:::\n:::\n\n\n. . .\n\nAnd the *t* for the slope?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(fit.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)   2.58     0.155       16.6  1.41e-54\n2 age          -0.0254   0.00300     -8.46 1.04e-16\n```\n\n\n:::\n\n```{.r .cell-code}\ncor.test(cah$age, cah$transformers)$statistic\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        t \n-8.457459 \n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Significance $\\neq$ importance\n\nThe $p$-value tells us the effect is **likely not zero**. It says *nothing* about whether the effect is large or meaningful.\n\n::: callout-important\nWith a large enough sample, a tiny, trivial effect becomes statistically significant. Our *n* here is **938**.\n:::\n\n**Statistical Significance** $\\neq$ **Practical Significance**\n\n------------------------------------------------------------------------\n\n## Effect size for a regression\n\n1.  **The slope itself** — in the units of your study. The most concrete thing you have.\n\n2.  **Standardized slope** — in SD units. Cohen's rough guide: small (\\|.10\\|), medium (\\|.30\\|), large (\\|.50\\|)\n\n3.  **Coefficient of determination** $R^2$ — proportion of variance accounted for\n\n. . .\n\nFor our model: $r = -.27$, so $R^2 = .071$\n\n> \"Approximately **7%** of the variability in Transformers movies seen is accounted for by age.\"\n\n------------------------------------------------------------------------\n\n## Writing it up\n\nTemplate: *b* = slope, *t*(df) = statistic, *p* = p-value, plus $R^2$\n\n> Age significantly predicted the number of Transformers movies a respondent had seen (*b* = −0.03, *p* \\< .001). Each additional decade of age was associated with about a quarter of a movie fewer, and age accounted for 7.1% of the variance in movies seen ($R^2$ = .07).\n\n. . .\n\n::: callout-tip\nNotice what the good version includes: the estimate **in real units**, the test, *and* a statement of how much it matters. All three.\n\nSome folks will include the t-values, but I find that overwhelming. Just have that in the tables.\n:::\n\n------------------------------------------------------------------------\n\n## Pretty tables with `sjPlot`\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_model(fit.1, show.std = TRUE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<tr>\n<th style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; \">&nbsp;</th>\n<th colspan=\"5\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">transformers</th>\n</tr>\n<tr>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; \">Predictors</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Estimates</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">std. Beta</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">standardized CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">p</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">2.58</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.00</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">2.27&nbsp;&ndash;&nbsp;2.88</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;0.06&nbsp;&ndash;&nbsp;0.06</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">age</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;0.03</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;0.27</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;0.03&nbsp;&ndash;&nbsp;-0.02</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;0.33&nbsp;&ndash;&nbsp;-0.20</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;\">Observations</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"5\">938</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">R<sup>2</sup> / R<sup>2</sup> adjusted</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"5\">0.071 / 0.070</td>\n</tr>\n\n</table>\n\n`````\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Data, fitted, and residuals\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_info <- augment(fit.1)\nhead(model_info)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 9\n  .rownames transformers   age .fitted  .resid    .hat .sigma .cooksd .std.resid\n  <chr>            <int> <int>   <dbl>   <dbl>   <dbl>  <dbl>   <dbl>      <dbl>\n1 1                    1    64   0.953  0.0467 0.00196   1.50 9.51e-7     0.0311\n2 2                    0    56   1.16  -1.16   0.00126   1.50 3.74e-4    -0.769 \n3 3                    0    63   0.979 -0.979  0.00185   1.50 3.92e-4    -0.651 \n4 4                    0    48   1.36  -1.36   0.00107   1.50 4.38e-4    -0.904 \n5 5                    1    32   1.77  -0.765  0.00222   1.50 2.88e-4    -0.509 \n6 6                    0    64   0.953 -0.953  0.00196   1.50 3.95e-4    -0.635 \n```\n\n\n:::\n:::\n\n\n::: notes\nPoint out that the average of the residuals is 0 — just like the average deviation from the mean is 0.\n:::\n\n------------------------------------------------------------------------\n\n### The relationship between $\\hat{Y_i}$ and $e_i$\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nmodel_info %>%\n  ggplot(aes(x = .fitted, y = .resid)) +\n  geom_point(alpha = .3) +\n  geom_smooth(se = F, method = \"lm\") +\n  scale_y_continuous(\"e\") +\n  scale_x_continuous(expression(hat(Y))) +\n  theme_bw(base_size = 25)\n```\n\n::: {.cell-output-display}\n![](lec-05_regression_files/figure-revealjs/unnamed-chunk-20-1.png){width=768}\n:::\n:::\n\n\n. . .\n\nFlat. Always. **By construction** — and in Week 10 we will use that fact to catch models that are lying to us.\n\n# Part 4: The Lab 5 Punchline\n\n------------------------------------------------------------------------\n\n## A t-test *is* a regression\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncah_mf <- cah %>% filter(gender == \"Male\" | \n                           gender == \"Female\") \n#OR\n\ncah_mf <- cah %>% filter(gender %in% c(\"Male\", \"Female\"))\n\n\nt.test(transformers ~ gender, data = cah_mf, var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  transformers by gender\nt = -2.2886, df = 911, p-value = 0.02233\nalternative hypothesis: true difference in means between group Female and group Male is not equal to 0\n95 percent confidence interval:\n -0.4348223 -0.0333445\nsample estimates:\nmean in group Female   mean in group Male \n            1.206897             1.440980 \n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## The same question as a line\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(transformers ~ gender, data = cah_mf) %>% tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)    1.21     0.0717     16.8  1.59e-55\n2 genderMale     0.234    0.102       2.29 2.23e- 2\n```\n\n\n:::\n:::\n\n\n::: incremental\n- The **intercept** (1.21) is the mean of the *first* group (Female)\n- The **slope** (0.23) is the *difference* between the means\n- Same *t*. Same *p*. One machine.\n:::\n\n------------------------------------------------------------------------\n\n## Why this matters\n\n::: callout-note\nYou do not have to memorize a separate procedure for every design.\n\n`outcome ~ predictor` handles the continuous case **and** the group case. Over the next few weeks we just add more predictors to the same machine.\n:::\n\n**Next week:** groups as regression, in full — t-tests and ANOVA as `lm()`.\n\n------------------------------------------------------------------------\n\n## One more thing: regression to the mean\n\nAn observation about heights motivated the development of regression: if you selected an exceptionally tall (or short) parent, their child was almost always **less** extreme.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(psychTools)\nheights <- psychTools::galton\nmod <- lm(child ~ parent, data = heights)\nheights <- broom::augment(mod)\n\nheights %>%\n  ggplot(aes(x = parent, y = child)) +\n  geom_jitter(alpha = .3) +\n  geom_smooth(method = \"lm\", se = FALSE) +\n  geom_hline(aes(yintercept = 72), color = \"red\") +\n  geom_vline(aes(xintercept = 72), color = \"red\") +\n  theme_bw(base_size = 20)\n```\n\n::: {.cell-output-display}\n![](lec-05_regression_files/figure-revealjs/unnamed-chunk-23-1.png){width=960}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Regression to the mean\n\n**Regression to the mean**: a random variable that produces an extreme score on a first measurement tends to produce a less extreme score on a second measurement.\n\n::: callout-warning\nThis is a threat to internal validity whenever an intervention is assigned **based on** first-measurement scores.\n\nTutoring the students who bombed the midterm? They would have improved somewhat *anyway*.\n:::\n\n------------------------------------------------------------------------\n\n## 🛠️ Activity Stop 2: Parts B & C\n\n::: callout-tip\n**One Line, Two Stories** · \\~35 min · Pairs\n:::\n\n**Part B (\\~25 min):** Do older people read more books?\n\n- You will get *p* = .027 — and then one person who reported reading **1,000 books** will make it disappear\n- The p-value flips on a judgment call **you** make\n\n**Part C (\\~10 min):** The t-test / regression equivalence, in your own file\n\n[Open the activity](../class-activities/wk5_linear-model.html){.button target=\"_blank\"}\n\n------------------------------------------------------------------------\n\n## ✍️ Wrap-Up\n\nFinish these at the bottom of your activity file:\n\n1.  A slope, stated in the units of a study, **without using the word \"slope.\"**\n2.  One intercept from today that is meaningless, and why.\n3.  One thing that is still muddy → put it in your journal this week.\n\n------------------------------------------------------------------------\n\n## For next time\n\n📋 **Lab 6 — Reading the Line**\n\n- Almost no coding. I give you the output; you tell me what it means.\n- Uses the Lab 5 data plus a new context\n\n📖 Chapter 15 — ST\n\n::: callout-important\n## Schedule change\n\nThe lab schedule has moved up from the PDF syllabus. Website = current version.\n:::\n",
    "supporting": [
      "lec-05_regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}