---
title: Main Project
---

## Final Group Project

The goal of the final project for PSYC 641 is to develop a research proposal similar to what you might see as a pre-registration. You will be placed into groups, which will be your "research lab group". Your group will be tasked with developing a study to answer a central question (e.g., How does mood impact sleep in youth?). As a group, you will develop the **Research Deign** of a single study to accomplish the main research question. Your individual portion will then consist of using a subset of the data from the study to answer an even more specific question (e.g., What role does positive affect play in the relationship between stress and sleep?).

The best way to think about this is you and your team have been given a small grant to study a main focus. Since resources are limited, we want to collect as much data as reasonably possible to address as many different questions as possible. This project will mimic a real-world lab collaboration effort.

------------------------------------------------------------------------

### Initial Proposal

**Goal:** To create a proposal for the final project.

**Overview:** You and your group will define a broad theory/aim/research question. From there, each group member will identify a specific focus. Think of this as starting one set of data collection that will have a central focus, but each of you will have a specific component. It may make sense to think about the data collection technique (e.g., cross-sectional, longitudinal, experimental, etc.) as a group and then identify the component that you will focus on.

The goal of this assignment is to clearly identify the overarching theory of your group as well as the specific research question or aim that you seek to accomplish for your portion of the project.

Work with your group members to identify a central theory or question that you are interested in examining. This can be an extension of a current research project, or something that is new and novel. You can build upon the theory that was started at the beginning of your group, but you don’t have to.

**Structure:** 2+ pages double spaced. Calibri, Arial or Times New Roman font. 1-inch margins. Minimum of 3 citations. Begin with a brief introduction to the topic and identify the broad theory of your group. This will then lead into the rationale for your specific portion. Highlight the importance of your research question and be sure to have this stated clearly. It can be helpful to have these identified as “Aims” of the project.

This specific assignment is not set to be a complete evaluation of how you create a study. Instead, I want you to be able to communicate your thought process in a structured way resulting in a single focus or aim.

------------------------------------------------------------------------

## Design & Measures Section Draft

### Research Question & Hypothesis (Individual)

-   Provide the overarching research question/aim that your group is focusing on (i.e., why are you doing this study)

-   Identify your specific research question within the larger study of your group

### Study Procedures/Design (Group)

-   Specify whether your study will be experimental, quasi-experimental, or non-experimental and justify your choice. Also indicate the type of design that you are planning to use (e.g., cross-sectional, longitudinal, cohort design, etc.)

-   Describe your sampling method and justify why it is appropriate for your study

    -   Provide information on what the recruitment strategies are going to be

    -   Discuss any potential sampling biases and how they will be addressed.

-   Walk through what the participant will be experiencing during their visit or throughout their participation in the study

-   What kind of space and physical materials will you need (computer, eye-tracker, EEG, etc.)

-   Be sure to discuss any ethical issues that may arise in your study and how you will address them

### Measurement - Operationalizing the Construct (Individual)

-   Clearly define and operationalize all constructs involved in your research

-   Explain how you will measure or manipulate these constructs in your study

-   Identify the specific questionnaires or how you will be examining these constructs

## Diagram of Proposed Analysis (Individual)

-   Using the DAG framework, identify the model that you want to examine. This can just be an image.
