{
  "hash": "58c2c1b5a91b589260da9411045238e3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 07: Variability & Model Fit with JAMOVI\"\nsubtitle: \"Date: October 8, 2026\"\nfooter:  \"[course-website](https://dharaden.github.io/psyc640/)\"\nlogo: \"images/640_hex.png\"\nformat:\n  revealjs:\n    theme: [default, brand, clean.scss]\n    multiplex: false\n    transition: fade\n    slide-number: true\n    incremental: false\n    chalkboard: true\n    overview: false\n    scrollable: true\n    code-line-numbers: true\neditor: visual\nexecute:\n  echo: true\n  freeze: auto\n---\n\n## Today...\n\n**How good is this model, actually?**\n\n- Where the variance goes: $SS_{total} = SS_{model} + SS_{residual}$\n- R², one more time — and what it is *not*\n- The typical miss, in real units\n- The F test as a ratio\n- Why R² can only go **up**, and what to use instead\n- 👀 A sneak peek at two predictors\n\n::: callout-note\nThis is the **JAMOVI** version. Same data, same numbers as the R deck. JAMOVI is genuinely *better* than base R at one thing today — comparing nested models — so stick around for Part 3.\n:::\n\n------------------------------------------------------------------------\n\n## Our data: the ASAP study 😴\n\n400 adolescents, measured on sleep, stress, and mood.\n\n<a href=\"../files/data/asap_data.csv\" download=\"asap_data.csv\">Download the ASAP data (.csv)</a>\n\n> ☰ **Menu → Open → Browse →** `asap_data.csv`\n\n> **Analyses → Exploration → Descriptives** · `T1_SleepDur`, `T1_PeerStress`, `T1_AcadStress`, `T1_Dep`\n\n| Variable | N | Mean | SD |\n|-------------------|-------------------|-------------------|-------------------|\n| `T1_SleepDur` (hours) | 400 | 9.45 | 1.00 |\n| `T1_PeerStress` | 400 | 7.93 | 1.77 |\n| `T1_AcadStress` | 400 | 5.02 | 1.83 |\n| `T1_Dep` | 400 | 9.84 | **2.15** |\n\n> **Research question:** Does how long adolescents sleep predict depressive symptoms?\n\n# Part 1: Where Does the Variance Go?\n\n------------------------------------------------------------------------\n\n## Start with the dumbest possible model\n\nSuppose you had **no predictor at all**. What is your best guess for anyone's depression score?\n\n. . .\n\nThe **mean**: 9.84. That's it. That's the model.\n\n. . .\n\nHow wrong is that model? Add up every squared miss:\n\n$$SS_{total} = \\sum(Y_i - \\bar{Y})^2 = 1840.5$$\n\nThis is the **total variability** we are trying to account for. Everything from here is about shrinking it.\n\n------------------------------------------------------------------------\n\n## Now add a predictor\n\n> **Analyses → Regression → Linear Regression**\n>\n> Dependent Variable: `T1_Dep` · **Covariates:** `T1_SleepDur`\n>\n> Model Fit: tick **R²**, **Adjusted R²**, **RMSE**, **Overall Model Test**\n>\n> Model Coefficients: tick **Omnibus ANOVA Test**\n\n| Predictor | Estimate | SE | t | p |\n|-------------|-------------|-------------|-------------|-------------|\n| Intercept | 15.031 | 0.985 | 15.26 | \\< .001 |\n| T1_SleepDur | **−0.549** | 0.104 | **−5.30** | **\\< .001** |\n\nEach additional hour of sleep is associated with **0.55 fewer** points of depression. But today's question is: **how much better is this line than the mean?**\n\n------------------------------------------------------------------------\n\n## Three distances, one observation\n\nFor any single adolescent:\n\n::::: columns\n::: {.column width=\"50%\"}\n$$\\underbrace{Y_i - \\bar{Y}}_{\\text{total}} = \\underbrace{\\hat{Y_i} - \\bar{Y}}_{\\text{model}} + \\underbrace{Y_i - \\hat{Y_i}}_{\\text{residual}}$$\n:::\n\n::: {.column width=\"50%\"}\n- **Total**: how far this person is from the overall mean\n- **Model**: how far the *line* moved them from the mean\n- **Residual**: how far the line still missed\n:::\n:::::\n\n. . .\n\nSquare them, add them up across all 400 people, and the same decomposition holds:\n\n$$SS_{total} = SS_{model} + SS_{residual}$$\n\n------------------------------------------------------------------------\n\n## See it in the numbers\n\nThe **Omnibus ANOVA Test** table you just ticked:\n\n| Term | Sum of Squares | df | Mean Square | F | p |\n|------------|------------|------------|------------|------------|------------|\n| T1_SleepDur | **121.2** | 1 | 121.2 | 28.05 | \\< .001 |\n| Residuals | **1719.4** | 398 | 4.32 |  |  |\n\n::: incremental\n- $SS_{model}$ = **121.2** — variability the line accounts for\n- $SS_{residual}$ = **1719.4** — variability it does not\n- Together: 121.2 + 1719.4 = **1840.5** = $SS_{total}$ ✅\n:::\n\n------------------------------------------------------------------------\n\n## R² is just a share\n\n$$R^2 = \\frac{SS_{model}}{SS_{total}} = \\frac{121.2}{1840.5} = .066$$\n\n**Model Fit Measures**\n\n| R | R² | Adjusted R² | RMSE |\n|------------------|------------------|------------------|------------------|\n| 0.257 | **0.0658** | 0.0635 | 2.073 |\n\n. . .\n\n**6.6%** of the variability in depression is accounted for by sleep duration.\n\nWhich means **93.4% is not**. Both halves of that sentence are the finding.\n\n------------------------------------------------------------------------\n\n## Small R², strong evidence\n\n::::: columns\n::: {.column width=\"50%\"}\n**R² = .066**\n\nSleep duration tells us very little about any individual adolescent's depression.\n:::\n\n::: {.column width=\"50%\"}\n**p \\< .001**\n\nWith n = 400, we are confident the slope is not zero.\n:::\n:::::\n\n. . .\n\n::: callout-important\nThese are answers to **different questions**. \"Is there an effect?\" and \"how much does it explain?\" are not the same, and a p-value only answers the first.\n:::\n\n. . .\n\nThis is normal in psychology. Behavior has many causes; one predictor rarely owns much of the variance.\n\n# Part 2: Fit in Real Units\n\n------------------------------------------------------------------------\n\n## R² is unitless. That's a problem.\n\n\".066\" does not tell you whether this model is useful for a clinician.\n\n. . .\n\n**RMSE** does. It is roughly the size of a typical miss, in the units of the outcome:\n\n$$RMSE \\approx \\sqrt{\\frac{SS_{residual}}{n}} = \\sqrt{\\frac{1719.4}{400}} = 2.07$$\n\n::: callout-note\nJAMOVI's RMSE divides by *n*; R's \"residual standard error\" divides by the degrees of freedom (2.08 here). Same idea, trivially different arithmetic — don't let the two labels confuse you.\n:::\n\n------------------------------------------------------------------------\n\n## The comparison that matters\n\n::: incremental\n- Guess the **mean** for everyone → you are off by about **2.15** points on average\n- Use the **model** → you are off by about **2.07** points\n:::\n\n. . .\n\nWe bought ourselves about **0.08 points** of accuracy.\n\n. . .\n\n::: callout-tip\nThat is the honest way to describe a small R² to a non-statistician: *not* \"6.6% of variance,\" which means nothing to most people, but \"knowing how long a teenager slept barely improves our guess about their mood.\"\n:::\n\n------------------------------------------------------------------------\n\n## The F test is a ratio\n\n$$F = \\frac{MS_{model}}{MS_{residual}} = \\frac{121.2}{4.32} = 28.05$$\n\n**Overall Model Test**\n\n| F | df1 | df2 | p |\n|------------------|------------------|------------------|------------------|\n| **28.05** | 1 | 398 | \\< .001 |\n\n::: incremental\n- If the model explained **nothing**, F would hover around 1\n- With one predictor, $F = t^2$: $(-5.30)^2 = 28.05$ ✅ — the same test again\n:::\n\n# Part 3: Adding Predictors 👀\n\n------------------------------------------------------------------------\n\n## JAMOVI's best trick: Model Builder\n\n> **Linear Regression → Model Builder**\n>\n> **Block 1:** `T1_SleepDur`\n>\n> Click **+ Add New Block** → **Block 2:** `T1_PeerStress`\n\n. . .\n\nNow tick **Model Comparisons** under Model Fit.\n\nJAMOVI will fit *both* models and test the difference between them — which is exactly the question \"did peer stress earn its place?\"\n\n------------------------------------------------------------------------\n\n## Does peer stress help?\n\n**Model Comparisons**\n\n| Comparison | ΔR² | F | df1 | df2 | p |\n|------------|------------|------------|------------|------------|------------|\n| Model 1 − Model 2 | **0.027** | 11.78 | 1 | 397 | **\\< .001** |\n\n**Model Fit Measures**\n\n| Model | R² | Adjusted R² | RMSE |\n|------------------|------------------|------------------|------------------|\n| 1. Sleep only | .0658 | .0635 | 2.073 |\n| 2. \\+ peer stress | **.0928** | **.0882** | **2.043** |\n\n::: incremental\n- $\\Delta R^2$ = **.027** — peer stress accounts for 2.7% *beyond* sleep\n- The typical miss dropped from 2.073 to 2.043\n:::\n\n------------------------------------------------------------------------\n\n## Now let's add something useless\n\n> **+ Add New Block** → **Block 3:** `T1_AcadStress`\n\n| Predictor | Estimate | SE | t | p |\n|-------------|-------------|-------------|-------------|-------------|\n| T1_AcadStress | **−0.007** | 0.057 | −0.12 | **0.902** |\n\nAcademic stress is as close to nothing as you will ever see.\n\n------------------------------------------------------------------------\n\n## Watch what R² does\n\n| Model | R² | Adjusted R² | RMSE |\n|------------------|------------------|------------------|------------------|\n| 1. Sleep only | .0658 | .0635 | 2.073 |\n| 2. \\+ peer stress | .0928 | .0882 | 2.043 |\n| 3. \\+ academic stress | **.0928** | **.0859** ⬇️ | 2.043 |\n\n::: incremental\n- R² **did not go down** — it never can\n- Adjusted R² **did**\n- And Model Comparisons reports the block as non-significant, *p* = .90\n:::\n\n------------------------------------------------------------------------\n\n## Why R² can only climb\n\nAdding a predictor gives the model one more knob to turn. At worst the coefficient sits near zero and fit stays the same; usually it catches a sliver of noise and R² ticks up.\n\n. . .\n\n$$R^2_{adj} = 1 - (1 - R^2)\\frac{n - 1}{n - k - 1}$$\n\nEvery predictor $k$ costs you something. Adjusted R² only rises if the new variable earns its place.\n\n::: callout-important\n**R² is not a model-selection tool.** The biggest R² always belongs to the model with the most predictors. Week 11 gives us honest ways to compare models — and JAMOVI's Model Comparisons table is the first one.\n:::\n\n------------------------------------------------------------------------\n\n## JAMOVI ↔ R cheat sheet\n\n| What you want | JAMOVI | R |\n|------------------------|------------------------|------------------------|\n| R², adjusted R² | Model Fit Measures | `glance(fit)` |\n| Typical miss | Model Fit → **RMSE** | `glance(fit)$sigma` |\n| Sums of squares | Model Coefficients → **Omnibus ANOVA Test** | `anova(fit)` |\n| Overall F | Model Fit → Overall Model Test | `glance(fit)$statistic` |\n| Compare nested models | **Model Builder** blocks + Model Comparisons | `anova(fit1, fit2)` |\n| ΔR² | Model Comparisons table | subtract two `glance()` rows |\n\n------------------------------------------------------------------------\n\n## ⏱️ One last thing: look at the residuals {background-color=\"#EFE6F7\"}\n\nWe spent all day computing $SS_{residual}$. Let's actually **look** at the residuals instead of just squaring them.\n\n> **Linear Regression → Assumption Checks**\n>\n> Tick **Residual plots**\n\nJAMOVI gives you residuals against fitted values (plus a Q-Q plot). For the ASAP model it is a shapeless cloud centered on zero — which is what \"nothing obviously wrong\" looks like.\n\n------------------------------------------------------------------------\n\n## What you are glancing for\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lec-07_fit_JAMOVI_files/figure-revealjs/unnamed-chunk-1-1.png){width=960}\n:::\n:::\n\n\n::: incremental\n- **Curve** → the line is the wrong shape for these data\n- **Funnel** → the model is more wrong for some people than others\n- **Strange point** → one observation may be running the whole model (remember the 1,000-books reader?)\n:::\n\n. . .\n\n::: callout-note\nThat is the entire diagnostic toolkit for now: **tick the box, look for a pattern.** Week 10 turns each of these into a named assumption with a proper test. For the midterm, the glance is enough.\n:::\n\n------------------------------------------------------------------------\n\n## 🛠️ Activity: Does the Algorithm Know What a Hit Is?\n\n::: callout-tip\n**Week 7 Exercises** · \\~45 min · Pairs\n:::\n\nSpotify data: 952 popular songs, with danceability, energy, valence, acousticness — and streams.\n\n- Four audio features together explain about **1%** of streams\n- One boring variable explains **62%**\n- You will find it, and then explain why the fancy features lost\n\n[Open the activity](../class-activities/wk7_fit.html){.button target=\"_blank\"}\n\n------------------------------------------------------------------------\n\n## ✍️ Wrap-Up\n\nFinish these at the bottom of your activity file:\n\n1.  In one sentence, explain R² to someone who has never taken statistics.\n2.  Why can a predictor be statistically significant and still barely improve a model?\n3.  One thing that is still muddy → journal.\n\n------------------------------------------------------------------------\n\n## For next time\n\n📋 **Lab 8 — How Good Is This Model?**, due **Tuesday 10/13 at 11:59pm**\n\n::: callout-warning\n**10/13 is during Fall Break.** The lab is submitted online as usual — nothing to hand in physically, and no class that Monday or Tuesday.\n:::\n\n- Model fit on a real anxiety dataset, in the units people care about\n- Ends with a **sneak peek**: one predictor that looks useless alone, and what happens when you add a second\n\n📖 Chapter 10 — ROS (for next week's multiple regression)\n\n::: callout-important\n## 📂 Midterm Project — posted today\n\nThe [**Midterm Project**](../labs/midterm-project.html) is up on the website now. **Due Tuesday, 10/27 at 11:59pm.** It is worth 200 points (20% of your grade).\n\n- **Parts 1-5 use only what you already know** - cleaning, scoring, describing, one-predictor models. You can start this weekend.\n- **Part 6 needs multiple regression**, which is next class (10/15).\n- You pick your own research question. Read the whole thing before you leave today.\n\nNo lab is due in Weeks 9 or 10, so that time is yours for the project.\n:::\n",
    "supporting": [
      "lec-07_fit_JAMOVI_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}