{
  "hash": "f6939d870ed4cc74f31be8185ae3ac4c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 07: Variability & Model Fit\"\nsubtitle: \"Date: October 8, 2026\"\nfooter:  \"[course-website](https://dharaden.github.io/psyc640/)\"\nlogo: \"images/640_hex.png\"\nformat:\n  revealjs:\n    theme: [default, brand, clean.scss]\n    multiplex: false\n    transition: fade\n    slide-number: true\n    incremental: false\n    chalkboard: true\n    overview: false\n    scrollable: true\n    code-line-numbers: true\neditor: visual\nexecute:\n  echo: true\n  freeze: auto\n---\n\n## Today...\n\n**How good is this model, actually?**\n\n- Where the variance goes: $SS_{total} = SS_{model} + SS_{residual}$\n- R², one more time — and what it is *not*\n- The residual standard error: your typical miss, in real units\n- The F test as a ratio\n- Why R² can only go **up**, and what to use instead\n- 👀 A sneak peek at two predictors\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(here)\nlibrary(tidyverse)\nlibrary(rio)\nlibrary(broom)\nlibrary(psych)\n\noptions(scipen = 999)\n\nasap <- import(here(\"files\", \"data\", \"asap_data.csv\"))\n```\n:::\n\n\n------------------------------------------------------------------------\n\n## Our data: the ASAP study 😴\n\n400 adolescents, measured on sleep, stress, and mood.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nasap %>%\n  select(T1_SleepDur, T1_PeerStress, T1_AcadStress, T1_Dep) %>%\n  describe(fast = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              vars   n mean   sd median   min   max range  skew kurtosis   se\nT1_SleepDur      1 400 9.44 1.00   9.41  6.45 12.35  5.90  0.16    -0.25 0.05\nT1_PeerStress    2 400 7.93 1.77   7.89  2.86 13.34 10.48  0.23     0.21 0.09\nT1_AcadStress    3 400 5.02 1.83   4.97 -0.35 10.63 10.98  0.07    -0.12 0.09\nT1_Dep           4 400 9.84 2.15  10.05  1.08 15.29 14.21 -0.35     0.25 0.11\n```\n\n\n:::\n:::\n\n\n> **Research question:** Does how long adolescents sleep predict depressive symptoms?\n\n# Part 1: Where Does the Variance Go?\n\n------------------------------------------------------------------------\n\n## Start with the dumbest possible model\n\nSuppose you had **no predictor at all**. What is your best guess for anyone's depression score?\n\n. . .\n\nThe **mean**. That's it. That's the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(asap$T1_Dep)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.8442\n```\n\n\n:::\n:::\n\n\n. . .\n\nHow wrong is that model? Add up every squared miss:\n\n$$SS_{total} = \\sum(Y_i - \\bar{Y})^2 = 1840.5$$\n\nThis is the **total variability** we are trying to account for. Everything from here is about shrinking it.\n\n------------------------------------------------------------------------\n\n## Now add a predictor\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_sleep <- lm(T1_Dep ~ T1_SleepDur, data = asap)\ntidy(fit_sleep)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic   p.value\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)   15.0       0.985     15.3  1.000e-41\n2 T1_SleepDur   -0.549     0.104     -5.30 1.96 e- 7\n```\n\n\n:::\n:::\n\n\n. . .\n\nEach additional hour of sleep is associated with **0.55 fewer** points of depression.\n\nBut our question today is different: **how much better is this line than the mean?**\n\n------------------------------------------------------------------------\n\n## Three distances, one observation\n\nFor any single adolescent:\n\n::::: columns\n::: {.column width=\"50%\"}\n$$\\underbrace{Y_i - \\bar{Y}}_{\\text{total}} = \\underbrace{\\hat{Y_i} - \\bar{Y}}_{\\text{model}} + \\underbrace{Y_i - \\hat{Y_i}}_{\\text{residual}}$$\n:::\n\n::: {.column width=\"50%\"}\n- **Total**: how far this person is from the overall mean\n- **Model**: how far the *line* moved them from the mean\n- **Residual**: how far the line still missed\n:::\n:::::\n\n. . .\n\nSquare them, add them up across all 400 people, and the same decomposition holds:\n\n$$SS_{total} = SS_{model} + SS_{residual}$$\n\n------------------------------------------------------------------------\n\n## See it in the numbers\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(fit_sleep)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: T1_Dep\n             Df  Sum Sq Mean Sq F value       Pr(>F)    \nT1_SleepDur   1  121.16  121.16  28.045 0.0000001965 ***\nResiduals   398 1719.39    4.32                         \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n::: incremental\n- $SS_{model}$ = **121.2** — variability the line accounts for\n- $SS_{residual}$ = **1719.4** — variability it does not\n- Together: 121.2 + 1719.4 = **1840.5** = $SS_{total}$ ✅\n:::\n\n------------------------------------------------------------------------\n\n## R² is just a share\n\n$$R^2 = \\frac{SS_{model}}{SS_{total}} = \\frac{121.2}{1840.5} = .066$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(fit_sleep) %>% select(r.squared, adj.r.squared, sigma, statistic, p.value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n  r.squared adj.r.squared sigma statistic     p.value\n      <dbl>         <dbl> <dbl>     <dbl>       <dbl>\n1    0.0658        0.0635  2.08      28.0 0.000000196\n```\n\n\n:::\n:::\n\n\n. . .\n\n**6.6%** of the variability in depression is accounted for by sleep duration.\n\nWhich means **93.4% is not**. Both halves of that sentence are the finding.\n\n------------------------------------------------------------------------\n\n## Small R², strong evidence\n\n::::: columns\n::: {.column width=\"50%\"}\n**R² = .066**\n\nSleep duration tells us very little about any individual adolescent's depression.\n:::\n\n::: {.column width=\"50%\"}\n**p \\< .001**\n\nWith n = 400, we are confident the slope is not zero.\n:::\n:::::\n\n. . .\n\n::: callout-important\nThese are answers to **different questions**. \"Is there an effect?\" and \"how much does it explain?\" are not the same, and a p-value only answers the first.\n:::\n\n. . .\n\nThis is normal in psychology. Behavior has many causes; one predictor rarely owns much of the variance.\n\n# Part 2: Fit in Real Units\n\n------------------------------------------------------------------------\n\n## R² is unitless. That's a problem.\n\n\".066\" does not tell you whether this model is useful for a clinician.\n\n. . .\n\nThe **residual standard error** does. It is roughly the size of a typical miss, in the units of the outcome:\n\n$$RSE = \\sqrt{\\frac{SS_{residual}}{n - k - 1}} = \\sqrt{\\frac{1719.4}{398}} = 2.08$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(fit_sleep)$sigma\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.078476\n```\n\n\n:::\n\n```{.r .cell-code}\nsd(asap$T1_Dep)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.147764\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## The comparison that matters\n\n::: incremental\n- Guess the **mean** for everyone → you are off by about **2.15** points on average\n- Use the **model** → you are off by about **2.08** points\n:::\n\n. . .\n\nWe bought ourselves about **0.07 points** of accuracy.\n\n. . .\n\n::: callout-tip\nThat is the honest way to describe a small R² to a non-statistician: *not* \"6.6% of variance,\" which means nothing to most people, but \"knowing how long a teenager slept barely improves our guess about their mood.\"\n:::\n\n------------------------------------------------------------------------\n\n## The F test is a ratio\n\n$$F = \\frac{MS_{model}}{MS_{residual}} = \\frac{\\text{variance the model explains, per predictor}}{\\text{variance it doesn't, per leftover df}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(fit_sleep) %>% select(statistic, df, df.residual, p.value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n  statistic    df df.residual     p.value\n      <dbl> <dbl>       <int>       <dbl>\n1      28.0     1         398 0.000000196\n```\n\n\n:::\n:::\n\n\n::: incremental\n- $F$ = 28.05 on 1 and 398 df\n- If the model explained **nothing**, F would hover around 1\n- With one predictor, $F = t^2$: $(-5.30)^2 = 28.05$ ✅ — the same test again\n:::\n\n# Part 3: Adding Predictors 👀\n\n------------------------------------------------------------------------\n\n## Does peer stress help?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_two <- lm(T1_Dep ~ T1_SleepDur + T1_PeerStress, data = asap)\ntidy(fit_two)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term          estimate std.error statistic  p.value\n  <chr>            <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)     13.0      1.14       11.5  1.74e-26\n2 T1_SleepDur     -0.504    0.103      -4.89 1.47e- 6\n3 T1_PeerStress    0.201    0.0585      3.43 6.57e- 4\n```\n\n\n:::\n:::\n\n\n. . .\n\nBoth predictors are significant. The sleep slope barely moved (−0.55 → −0.50).\n\n------------------------------------------------------------------------\n\n## What happened to fit?\n\n| Model               | R²       | Adjusted R² | RSE       |\n|---------------------|----------|-------------|-----------|\n| Sleep only          | .066     | .064        | 2.078     |\n| Sleep + peer stress | **.093** | **.088**    | **2.051** |\n\n::: incremental\n- $\\Delta R^2$ = **.027** — peer stress accounts for 2.7% *beyond* sleep\n- The typical miss dropped from 2.078 to 2.051\n- Both numbers point the same way: a modest improvement\n:::\n\n------------------------------------------------------------------------\n\n## Now let's add something useless\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_three <- lm(T1_Dep ~ T1_SleepDur + T1_PeerStress + T1_AcadStress, data = asap)\ntidy(fit_three)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term          estimate std.error statistic  p.value\n  <chr>            <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)   13.0        1.14      11.4   3.29e-26\n2 T1_SleepDur   -0.503      0.104     -4.84  1.83e- 6\n3 T1_PeerStress  0.202      0.0590     3.42  6.91e- 4\n4 T1_AcadStress -0.00703    0.0570    -0.123 9.02e- 1\n```\n\n\n:::\n:::\n\n\nAcademic stress: *b* = −0.007, *p* = .90. As close to nothing as you will ever see.\n\n------------------------------------------------------------------------\n\n## Watch what R² does\n\n| Model              | R²        | Adjusted R²  | RSE          |\n|--------------------|-----------|--------------|--------------|\n| Sleep only         | .0658     | .0635        | 2.078        |\n| \\+ peer stress     | .0928     | .0882        | 2.051        |\n| \\+ academic stress | **.0928** | **.0859** ⬇️ | **2.053** ⬆️ |\n\n::: incremental\n- R² **did not go down** — it never can\n- Adjusted R² **did**, and the typical miss got **worse**\n:::\n\n------------------------------------------------------------------------\n\n## Why R² can only climb\n\nAdding a predictor gives OLS one more knob to turn. At worst it sets the coefficient near zero and fit stays the same; usually it catches a sliver of noise and R² ticks up.\n\n. . .\n\n$$R^2_{adj} = 1 - (1 - R^2)\\frac{n - 1}{n - k - 1}$$\n\nEvery predictor $k$ costs you something. Adjusted R² only rises if the new variable earns its place.\n\n::: callout-important\n**R² is not a model-selection tool.** The biggest R² always belongs to the model with the most predictors. Week 11 gives us honest ways to compare models.\n:::\n\n------------------------------------------------------------------------\n\n## ⏱️ One last thing: look at the residuals {background-color=\"#EFE6F7\"}\n\nWe spent all day computing $SS_{residual}$. Let's actually **look** at the residuals instead of just squaring them.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\naugment(fit_two) %>% \n  ggplot(aes(x = .fitted, y = .resid)) +\n  geom_point(alpha = .4) +\n  geom_hline(yintercept = 0, linetype = \"dashed\") +\n  geom_smooth(se = FALSE, color = \"#B3261E\") +\n  labs(x = \"Fitted (predicted depression)\", y = \"Residual\") +\n  theme_bw(base_size = 16)\n```\n\n::: {.cell-output-display}\n![](lec-07_fit_files/figure-revealjs/unnamed-chunk-11-1.png){width=960}\n:::\n:::\n\n\nA shapeless cloud centered on zero. That is what \"nothing obviously wrong\" looks like.\n\n------------------------------------------------------------------------\n\n## What you are glancing for\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(640)\nn <- 200\nx <- runif(n, 0, 10)\n\nsims <- bind_rows(\n  tibble(kind = \"1. Healthy\",          x = x, y = 2 + 0.8 * x + rnorm(n, 0, 2)),\n  tibble(kind = \"2. Curve (wrong shape)\", x = x, y = 2 + 0.8 * x^2 + rnorm(n, 0, 6)),\n  tibble(kind = \"3. Funnel (spread grows)\", x = x, y = 2 + 0.8 * x + rnorm(n, 0, 0.4 * x)),\n  tibble(kind = \"4. One strange point\",  x = x, y = 2 + 0.8 * x + rnorm(n, 0, 2))\n) %>% \n  mutate(y = if_else(kind == \"4. One strange point\" & row_number() == n(), y + 40, y))\n\nsims %>% \n  group_by(kind) %>% \n  group_modify(~ augment(lm(y ~ x, data = .x))) %>% \n  ggplot(aes(x = .fitted, y = .resid)) +\n  geom_point(alpha = .4, size = 1) +\n  geom_hline(yintercept = 0, linetype = \"dashed\") +\n  facet_wrap(~ kind, scales = \"free\") +\n  labs(x = \"Fitted\", y = \"Residual\") +\n  theme_bw(base_size = 13)\n```\n\n::: {.cell-output-display}\n![](lec-07_fit_files/figure-revealjs/unnamed-chunk-12-1.png){width=960}\n:::\n:::\n\n\n::: incremental\n- **Curve** → the line is the wrong shape for these data\n- **Funnel** → the model is more wrong for some people than others\n- **Strange point** → one observation may be running the whole model (remember the 1,000-books reader?)\n:::\n\n. . .\n\n::: callout-note\nThat is the entire diagnostic toolkit for now: **plot the residuals, look for a pattern.** Week 10 turns each of these into a named assumption with a proper test. For the midterm, the glance is enough.\n:::\n\n------------------------------------------------------------------------\n\n## 🛠️ Activity: Does the Algorithm Know What a Hit Is?\n\n::: callout-tip\n**Week 7 Exercises** · \\~45 min · Pairs\n:::\n\nSpotify data: 952 popular songs, with danceability, energy, valence, acousticness — and streams.\n\n- Four audio features together explain about **1%** of streams\n- One boring variable explains **62%**\n- You will find it, and then explain why the fancy features lost\n\n[Open the activity](../class-activities/wk7_fit.html){.button target=\"_blank\"}\n\n------------------------------------------------------------------------\n\n## ✍️ Wrap-Up\n\nFinish these at the bottom of your activity file:\n\n1.  In one sentence, explain R² to someone who has never taken statistics.\n2.  Why can a predictor be statistically significant and still barely improve a model?\n3.  One thing that is still muddy → journal.\n\n------------------------------------------------------------------------\n\n## For next time\n\n📋 **Lab 8 — How Good Is This Model?**, due **Tuesday 10/13 at 11:59pm**\n\n::: callout-warning\n**10/13 is during Fall Break.** The lab is submitted online as usual — nothing to hand in physically, and no class that Monday or Tuesday.\n:::\n\n- Model fit on a real anxiety dataset, in the units people care about\n- Ends with a **sneak peek**: one predictor that looks useless alone, and what happens when you add a second\n\n📖 Chapter 10 — ROS (for next week's multiple regression)\n\n::: callout-important\n## 📂 Midterm Project — posted today\n\nThe [**Midterm Project**](../labs/midterm-project.html) is up on the website now. **Due Tuesday, 10/27 at 11:59pm.** It is worth 200 points (20% of your grade).\n\n- **Parts 1-5 use only what you already know** - cleaning, scoring, describing, one-predictor models. You can start this weekend.\n- **Part 6 needs multiple regression**, which is next class (10/15).\n- You pick your own research question. Read the whole thing before you leave today.\n\nNo lab is due in Weeks 9 or 10, so that time is yours for the project.\n:::\n",
    "supporting": [
      "lec-07_fit_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}