{
  "hash": "d7d372fe3ec4edd9eec9d5f7ee3990cf",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 06: Comparing Groups as Regression\"\nsubtitle: \"Date: October 1, 2026\"\nfooter:  \"[course-website](https://dharaden.github.io/psyc640/)\"\nlogo: \"images/640_hex.png\"\nformat:\n  revealjs:\n    theme: [default, brand, clean.scss]\n    multiplex: false\n    transition: fade\n    slide-number: true\n    incremental: false\n    chalkboard: true\n    overview: false\n    scrollable: true\n    code-line-numbers: true\neditor: visual\nexecute:\n  echo: true\n  freeze: auto\n---\n\n## Today...\n\n**Groups, as lines**\n\n- Why a t-test *is* a regression (we prove it properly this time)\n- Dummy coding: how R turns a group into a number\n- Three or more groups: ANOVA is the same machine\n- Why not just run a bunch of t-tests?\n- Effect size: *d*, R², and which one to report\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(here)\nlibrary(tidyverse)\nlibrary(rio)\nlibrary(broom)\nlibrary(psych)\nlibrary(emmeans)\n\noptions(scipen = 999)\n\ntipi <- import(here(\"files\", \"data\", \"final_tipi.csv\")) %>%\n  # case_when(variable of interest == old_value ~ new value)\n  mutate(year_group = case_when(year_school == 1 ~ \"First year\",\n                                year_school == 2 ~ \"Sophomore\",\n                                year_school >= 3 ~ \"Junior+\"))\n```\n:::\n\n\n------------------------------------------------------------------------\n\n## Where we left off\n\nLast week, in Part C of the activity:\n\n::: incremental\n- You ran a **t-test** on two groups and got *t* = −2.29, *p* = .022\n- You ran `lm()` on the same two groups and got **the same** *t* and *p*\n- The **intercept** turned out to be one group's mean, and the **slope** the difference between the means\n:::\n\n. . .\n\nToday: *why*, and what happens when there are **three** groups.\n\n------------------------------------------------------------------------\n\n## Our data:  😴🏫\n\nWe are going back to the **TIPI dataset** from Week 3 — the one with 99 students, their personality scores, and how much they sleep.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntipi %>%\n  count(year_group)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  year_group  n\n1 First year 39\n2    Junior+ 37\n3  Sophomore 23\n```\n\n\n:::\n:::\n\n\n> **Research question:** Do students further along in school sleep differently than first-years?\n\n# Part 1: Two Groups\n\n------------------------------------------------------------------------\n\n## Start with two\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntwo_years <- tipi %>%\n  filter(year_group %in% c(\"First year\", \"Junior+\"))\n\ntwo_years %>%\n  group_by(year_group) %>%\n  summarize(n = n(),\n            M = mean(hours_of_sleep),\n            SD = sd(hours_of_sleep))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  year_group     n     M    SD\n  <chr>      <int> <dbl> <dbl>\n1 First year    39  6.13 1.28 \n2 Junior+       37  6.92 0.640\n```\n\n\n:::\n:::\n\n\n. . .\n\nJuniors and above sleep about **0.79 hours** — roughly 47 minutes — more per night. Is that more than noise?\n\n------------------------------------------------------------------------\n\n## The test you already know\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(hours_of_sleep ~ year_group, data = two_years, var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  hours_of_sleep by year_group\nt = -3.3751, df = 74, p-value = 0.001178\nalternative hypothesis: true difference in means between group First year and group Junior+ is not equal to 0\n95 percent confidence interval:\n -1.2575205 -0.3239071\nsample estimates:\nmean in group First year    mean in group Junior+ \n                6.128205                 6.918919 \n```\n\n\n:::\n:::\n\n\n*t*(74) = −3.38, *p* = .001.\n\nStudents ranked as juniors or higher reported significantly greater amounts of sleep (M = 6.92, SD = 0.64) compared to freshman (M = 6.13, SD = 1.28; *p* = .001).\n\n------------------------------------------------------------------------\n\n## The same question as a line\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_two <- lm(hours_of_sleep ~ year_group, data = two_years)\nsummary(mod_two)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = hours_of_sleep ~ year_group, data = two_years)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-5.1282  0.0811  0.0811  0.8718  1.0811 \n\nCoefficients:\n                  Estimate Std. Error t value             Pr(>|t|)    \n(Intercept)         6.1282     0.1635  37.490 < 0.0000000000000002 ***\nyear_groupJunior+   0.7907     0.2343   3.375              0.00118 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.021 on 74 degrees of freedom\nMultiple R-squared:  0.1334,\tAdjusted R-squared:  0.1217 \nF-statistic: 11.39 on 1 and 74 DF,  p-value: 0.001178\n```\n\n\n:::\n:::\n\n\n. . .\n\n::: callout-important\nSame *t* (the sign just depends on which group R treats as \"first\"). Same *p*. The t-test is a regression with **one categorical predictor**.\n:::\n\n------------------------------------------------------------------------\n\n## But how do you put a *group* in an equation?\n\n$$\\hat{Y_i} = b_0 + b_1X_i$$\n\n$X$ has to be a **number**. \"Junior+\" is not a number.\n\n. . .\n\nSo we make one. **Dummy coding**:\n\n| Group      | coded as |\n|------------|----------|\n| First year | **0**    |\n| Junior+    | **1**    |\n\nThat's it. That is the whole trick.\n\n------------------------------------------------------------------------\n\n## Read the equation twice\n\n$$\\widehat{sleep} = 6.13 + 0.79(junior^+)$$\n\n::::: columns\n::: {.column width=\"50%\"}\n**First year** → plug in 0\n\n$$6.13 + 0.79(0) = 6.13$$\n\nThe **intercept** is the mean of the group coded 0.\n:::\n\n::: {.column width=\"50%\"}\n**Junior+** → plug in 1\n\n$$6.13 + 0.79(1) = 6.92$$\n\nThe **slope** is the **difference** between the group means.\n:::\n:::::\n\n. . .\n\nA \"line\" through a predictor with two values can only ever produce **two** predicted values: the two group means.\n\n------------------------------------------------------------------------\n\n## The group that gets the 0 is the *reference*\n\nR picks it for you: **alphabetically**. \"First year\" beats \"Junior+\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntwo_years %>%\n  mutate(year_group = fct_relevel(year_group, \"Junior+\")) %>%\n  lm(hours_of_sleep ~ year_group, data = .) %>%\n  summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = hours_of_sleep ~ year_group, data = .)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-5.1282  0.0811  0.0811  0.8718  1.0811 \n\nCoefficients:\n                     Estimate Std. Error t value             Pr(>|t|)    \n(Intercept)            6.9189     0.1678  41.227 < 0.0000000000000002 ***\nyear_groupFirst year  -0.7907     0.2343  -3.375              0.00118 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.021 on 74 degrees of freedom\nMultiple R-squared:  0.1334,\tAdjusted R-squared:  0.1217 \nF-statistic: 11.39 on 1 and 74 DF,  p-value: 0.001178\n```\n\n\n:::\n:::\n\n\n. . .\n\nThe intercept becomes 6.92, the slope flips to −0.79, and *t*, *p*, R² and every residual stay exactly where they were.\n\n------------------------------------------------------------------------\n\n## What about Welch?\n\n`t.test()` defaults to **Welch's** t-test (unequal variances). `lm()` always assumes **equal** variances, like Student's t-test.\n\n. . .\n\nLook back at those SDs: **1.28** for first-years, **0.64** for juniors+. The first-years are twice as spread out.\n\n::: callout-note\nThat is exactly the situation Welch was built for. Here the groups are nearly the same size (39 vs 37), so the two tests agree — but with unequal *n* **and** unequal spread, they would not. Know which one you ran.\n:::\n\n------------------------------------------------------------------------\n\n## Effect size: two flavors\n\n\n::: {.cell}\n\n```{.r .cell-code}\neffectsize::cohens_d(hours_of_sleep ~ year_group, data = two_years)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohen's d |         95% CI\n--------------------------\n-0.77     | [-1.24, -0.31]\n\n- Estimated using pooled SD.\n```\n\n\n:::\n\n```{.r .cell-code}\nglance(mod_two) %>% select(r.squared, statistic, p.value)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  r.squared statistic p.value\n      <dbl>     <dbl>   <dbl>\n1     0.133      11.4 0.00118\n```\n\n\n:::\n:::\n\n\n::: incremental\n- **Cohen's *d* = −0.78** (0.78 in magnitude; the sign just reflects group order) — the difference in standard deviations. \"How separated are the groups?\"\n- **R² = .133** — the proportion of variance in sleep accounted for by year group. \"How much does knowing the group help?\"\n:::\n\n. . .\n\nSame model. Report *d* for a two-group comparison; R² scales up to everything we do next.\n\n------------------------------------------------------------------------\n\n## 🛠️ Activity Stop 1: Same Question, Three Ways\n\n::: callout-tip\n**Part A: Follow along** · \\~20 min · Pairs\n:::\n\nNew data — the Pokémon set from your in-class check:\n\n- Run the t-test, then the regression, on the same two groups\n- Find the intercept in the group means\n- Flip the reference group and predict what will change **before** you run it\n\n[Open the activity](../class-activities/wk6_groups.html){.button target=\"_blank\"}\n\n------------------------------------------------------------------------\n\n## ☕ Break {background-color=\"#C9ADE0\"}\n\n**10 minutes**\n\nWhen we come back: **three** groups.\n\n# Part 2: Three or More Groups\n\n------------------------------------------------------------------------\n\n## Put the sophomores back\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntipi %>%\n  group_by(year_group) %>%\n  summarize(n = n(),\n            M = mean(hours_of_sleep),\n            SD = sd(hours_of_sleep))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  year_group     n     M    SD\n  <chr>      <int> <dbl> <dbl>\n1 First year    39  6.13 1.28 \n2 Junior+       37  6.92 0.640\n3 Sophomore     23  6.48 0.898\n```\n\n\n:::\n:::\n\n\n. . .\n\nSophomores land in the middle. Now we have **three** means — and three possible comparisons.\n\n------------------------------------------------------------------------\n\n## Why not just run three t-tests? 🤔\n\nfirst-year vs sophomore · first-year vs junior+ · sophomore vs junior+\n\n. . .\n\nEach test has a 5% false-positive rate. We set that when we accept our cutoff of p \\< .05. If the three tests were **independent**, the chance of at least one false positive would be:\n\n$$1 - (1 - .05)^3 = .143$$\n\n. . .\n\nThey are *not* independent — the three tests reuse the same three groups — so that formula overstates it a bit. Let's just **check**.\n\n------------------------------------------------------------------------\n\n## Build a world where nothing is true\n\nSame idea as the Inference Machine in Week 4: simulate studies where we **know** the null is true, then count how often we fool ourselves.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(640)\n\none_study <- function(n = 30) {\n  # three groups drawn from the SAME population: no real differences\n  a <- rnorm(n)\n  b <- rnorm(n)\n  c <- rnorm(n)\n  \n  # run all three pairwise t-tests\n  p_ab <- t.test(a, b, var.equal = TRUE)$p.value\n  p_ac <- t.test(a, c, var.equal = TRUE)$p.value\n  p_bc <- t.test(b, c, var.equal = TRUE)$p.value\n  \n  # keep the smallest p-value\n  min(p_ab, p_ac, p_bc)\n}\n\nsmallest_p <- replicate(1000, one_study())\n\n# how often do we get at least one \"significant\" result by chance?\nmean(smallest_p < 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.114\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## 1,000 studies where nothing was going on\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntibble(smallest_p = smallest_p) %>% \n  ggplot(aes(x = smallest_p, fill = smallest_p < .05)) +\n  geom_histogram(binwidth = .025, boundary = 0, color = \"white\") +\n  geom_vline(xintercept = .05, linetype = \"dashed\") +\n  scale_fill_manual(values = c(\"grey70\", \"#B3261E\"), guide = \"none\") +\n  labs(x = \"Smallest p-value in the study\", y = \"Number of studies\",\n       title = \"Three groups, three t-tests, zero real differences\") +\n  theme_bw(base_size = 16)\n```\n\n::: {.cell-output-display}\n![](lec-06_groups_files/figure-revealjs/unnamed-chunk-10-1.png){width=960}\n:::\n:::\n\n\nAbout **12%** of these studies produced at least one \"significant\" difference. None of them were real.\n\n------------------------------------------------------------------------\n\n## It gets worse fast\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(640)\n\nnum_groups <- 5\nsample <- 30\n\none_study <- function(n = 30, k = 3) {\n  # k groups, all drawn from the SAME population - no real differences\n  d <- tibble(group = rep(LETTERS[1:k], each = n),\n              y     = rnorm(n * k))\n  \n  # run every pairwise t-test, keep the smallest p-value\n  combn(LETTERS[1:k], 2, simplify = FALSE) %>% \n    map_dbl(function(pair) {\n      t.test(y ~ group, data = filter(d, group %in% pair), \n             var.equal = TRUE)$p.value\n    }) %>% \n    min()\n}\n\nsmallest_p <- map_dbl(1:1000, function(i) one_study(sample, num_groups))\n\nprop_sig <- mean(smallest_p < .05)\n\ntibble(smallest_p = smallest_p) %>% \n  ggplot(aes(x = smallest_p, fill = smallest_p < .05)) +\n  geom_histogram(binwidth = .025, boundary = 0, color = \"white\") +\n  geom_vline(xintercept = .05, linetype = \"dashed\") +\n  scale_fill_manual(values = c(\"grey70\", \"#B3261E\"), guide = \"none\") +\n  labs(x = \"Smallest p-value in the study\", \n       y = \"Number of studies\",\n       title = paste(num_groups, \"groups,\", choose(num_groups, 2),\n       \"t-tests, zero real differences\"), \n       subtitle = paste0(round(prop_sig * 100, 1),\n                                    \"% of studies found p < .05\")) +\n  theme_bw(base_size = 16)\n```\n\n::: {.cell-output-display}\n![](lec-06_groups_files/figure-revealjs/unnamed-chunk-11-1.png){width=960}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## It gets worse fast\n\n| Groups | Pairwise tests | False-positive rate      |\n|--------|----------------|--------------------------|\n| 2      | 1              | **4.9%** ← as advertised |\n| 3      | 3              | **12.3%**                |\n| 4      | 6              | **20.2%**                |\n| 5      | 10             | **29.2%**                |\n\n[*20,000 simulated studies per row, n = 30 per group, all groups from the same population.*]{style=\"font-size:0.7em\"}\n\n::: incremental\n- The naive formula ($1-.95^{10}$ = 40% for five groups) **overstates** it, because the tests overlap\n- But the honest number is still **six times** the rate you think you are running\n:::\n\n. . .\n\nThis is why we start with **one** omnibus test, and why pairwise comparisons get **corrected**.\n\n------------------------------------------------------------------------\n\n## Two groups needed one dummy. Three need two.\n\n| Group                      | `Junior+` | `Sophomore` |\n|----------------------------|-----------|-------------|\n| **First year** (reference) | 0         | 0           |\n| Junior+                    | 1         | 0           |\n| Sophomore                  | 0         | 1           |\n\n::: incremental\n- $k$ groups → $k - 1$ dummy variables\n- Every group gets a unique pattern of 0s and 1s\n- The reference group is the one that is **all zeros**\n:::\n\n. . .\n\nR builds these columns for you the moment it sees a factor.\n\n------------------------------------------------------------------------\n\n## The model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_year <- lm(hours_of_sleep ~ year_group, data = tipi)\nsummary(mod_year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = hours_of_sleep ~ year_group, data = tipi)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-5.1282  0.0811  0.0811  0.8718  1.0811 \n\nCoefficients:\n                    Estimate Std. Error t value             Pr(>|t|)    \n(Intercept)           6.1282     0.1592  38.501 < 0.0000000000000002 ***\nyear_groupJunior+     0.7907     0.2281   3.466             0.000791 ***\nyear_groupSophomore   0.3501     0.2613   1.340             0.183570    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.994 on 96 degrees of freedom\nMultiple R-squared:  0.1114,\tAdjusted R-squared:  0.0929 \nF-statistic: 6.018 on 2 and 96 DF,  p-value: 0.003449\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Reading it\n\n$$\\widehat{sleep} = 6.13 + 0.79(junior^+) + 0.35(sophomore)$$\n\n::: incremental\n- **Intercept 6.13** = mean sleep of **first-years** (the reference)\n- **+0.79** = juniors+ sleep 0.79 hours more **than first-years**, *t*(96) = 3.47, *p* \\< .001\n- **+0.35** = sophomores sleep 0.35 hours more **than first-years**, *t*(96) = 1.34, *p* = .184\n- Every coefficient is a comparison **to the reference group** — not to each other\n:::\n\n. . .\n\nSo where is sophomore vs junior+? **It isn't in this table.**\n\n------------------------------------------------------------------------\n\n## The omnibus F test\n\nAt the bottom of that output:\n\n> F(2, 96) = 6.02, **p = .003**, R² = **.111**\n\n::: incremental\n- $H_0$: all three population means are equal\n- A small *p* says **at least one** group differs — it does not say which\n- This is the ANOVA you already know. Same model, different summary.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(mod_year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: hours_of_sleep\n           Df Sum Sq Mean Sq F value   Pr(>F)   \nyear_group  2 11.893  5.9463  6.0181 0.003449 **\nResiduals  96 94.855  0.9881                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## ANOVA *is* regression\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# the classic way\nsummary(aov(hours_of_sleep ~ year_group, data = tipi))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value  Pr(>F)   \nyear_group   2  11.89   5.946   6.018 0.00345 **\nResiduals   96  94.85   0.988                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n. . .\n\nSame F. Same p. `aov()` is a wrapper around `lm()` that prints a sums-of-squares table instead of coefficients.\n\n::: callout-note\nR² here is what ANOVA calls $\\eta^2$ (eta squared): **11.1%** of the variance in sleep is accounted for by year in school.\n:::\n\n------------------------------------------------------------------------\n\n## Getting the comparison the table hid\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(mod_year, pairwise ~ year_group, adjust = \"none\")$contrasts\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast               estimate    SE df t.ratio p.value\n First year - (Junior+)   -0.791 0.228 96  -3.466  0.0008\n First year - Sophomore   -0.350 0.261 96  -1.340  0.1836\n (Junior+) - Sophomore     0.441 0.264 96   1.670  0.0983\n```\n\n\n:::\n:::\n\n\n::: incremental\n- First year vs Junior+: **significant** (Tukey *p* = .002)\n- First year vs Sophomore: not significant (*p* = .38)\n- Sophomore vs Junior+: not significant (*p* = .22)\n:::\n\n. . .\n\nThe omnibus test was significant because of **one** of the three comparisons. Without the pairwise step you would not know which.\n\n------------------------------------------------------------------------\n\n## Writing it up\n\n> Average nightly sleep differed significantly across year in school (*F*(2, 96) = 6.02, *p* = .003, $\\eta^2$ = .11). First-year students reported the least sleep (*M* = 6.13, *SD* = 1.28), followed by sophomores (*M* = 6.48, *SD* = 0.90) and juniors or above (*M* = 6.92, *SD* = 0.64). Tukey-adjusted comparisons indicated that juniors and above slept significantly more than first-year students (*p* = .002); no other pairwise comparison was significant.\n\n. . .\n\n::: callout-tip\nNotice the shape: **omnibus test → group descriptives → which pairs differ**. In that order, every time.\n:::\n\n------------------------------------------------------------------------\n\n## And the obvious caveat\n\nNobody was **randomly assigned** to be a first-year.\n\n::: incremental\n- Maybe upper-year students have more control over their schedules\n- Maybe the heavy-sleep-deprivation majors drop out before junior year\n- Maybe first-years live in noisier housing\n:::\n\n. . .\n\nThe model is fine. The **causal claim** is not available — same lesson as Lab 6. Next week's lab is the exception that proves the rule: a study where people *were* randomly assigned.\n\n------------------------------------------------------------------------\n\n## Did we forget to visualize??\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntipi %>% \n  ggplot(aes(year_group, hours_of_sleep, \n             fill = year_group)) + \n  geom_violin() + \n  geom_jitter(width = .1) + \n  labs(title = \"Hours of Sleep by Year in School\", \n       x = \"Year\", \n       y = \"Hours of Sleep\") + \n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](lec-06_groups_files/figure-revealjs/unnamed-chunk-16-1.png){width=960}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## The big picture so far\n\n| What you want        | The model     | What people call it              |\n|----------------------|---------------|----------------------------------|\n| Continuous predictor | `y ~ x`       | Regression                       |\n| 2 groups             | `y ~ group`   | t-test                           |\n| 3+ groups            | `y ~ group`   | One-way ANOVA                    |\n| Several predictors   | `y ~ x1 + x2` | **Multiple regression (Week 8)** |\n\n. . .\n\nOne machine. You are just changing what goes on the right-hand side.\n\n------------------------------------------------------------------------\n\n## 🛠️ Activity Stop 2: Parts B & C\n\n::: callout-tip\n**Same Question, Three Ways** · \\~30 min · Pairs\n:::\n\n**Part B:** three Pokémon types, from descriptives to a written-up result\n\n**Part C:** choose a reference group on purpose, and see what changes (and what doesn't)\n\n[Open the activity](../class-activities/wk6_groups.html){.button target=\"_blank\"}\n\n------------------------------------------------------------------------\n\n## For next time\n\n📋 **Lab 7 — Does the Therapy Work?**, due **Tuesday 10/6 at 11:59pm**\n\n- A real three-arm randomized trial: Individual CBT, Group CBT, Waitlist\n- You fit the model, pick the reference group, and write the results\n- Five participants dropped out — you will have to decide what to say about that\n\n📖 Chapter 8 — ROS · Chapters 5 & 14.5 — ST · Chapter 15.4 — LSR\n\n::: callout-note\nHeads up: the **midterm project** is handed out in two weeks (10/15) and due 10/27. Lab 8 is due Tue 10/13, which is during Fall Break — submit it online as usual.\n:::\n",
    "supporting": [
      "lec-06_groups_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}